### ISSUE TITLE
Qbittorrent update

### ISSUE THREAD

**Issue by Kapppa** [truenas/charts#1008]
Qbittorrent just had a security update, would appreciate if the app could be updated.

**Comment by stavros-k** [comment]
Hello, thanks for the report, It will be update as soon as the `4.5.2` tag is released in the upstream repo https://hub.docker.com/r/linuxserver/qbittorrent/tags?page=1&name=4.5.2

**Comment by Kapppa** [comment]
> Hello, thanks for the report, It will be update as soon as the `4.5.2` tag is released in the upstream repo https://hub.docker.com/r/linuxserver/qbittorrent/tags?page=1&name=4.5.2

It has been updated.
