### ISSUE TITLE
[Bug] Minio migrate error

### ISSUE THREAD

**Issue by BololZ** [truenas/charts#1020]
Hey,

During update of chart Minio from 1.7.9 to 1.7.13, I've got an error :
```
/migrations/migrate", line 90, in migrate
    "/mnt", k8s_config['dataset'], "releases", values["release_name"], "volumes/ix_volumes", 
app_dataset
KeyError: 'release_name'
```

Maybe values are incomplete ?

**Comment by Qubad786** [comment]
@BololZ this has been fixed in https://ixsystems.atlassian.net/browse/NAS-119238..
