### ISSUE TITLE
https probes (plex)

### ISSUE THREAD

**Issue by xeor** [truenas/charts#1058]
Plex has an option I like to enable to force https-only (network > Secure connections > required).
Plex deals with certificates, but the service will then only listen on https, making the probes (which are http only) fail.

Might it be a good idea to enable an option for what type of probe you want?

* https://github.com/truenas/charts/blob/master/charts/plex/1.7.33/templates/deployment.yaml#L70-L96
* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes

**Comment by xeor** [comment]
Another way, which might be even better to solve this would be to have a way to patch the kubernetes yaml files generated.
Like https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing or https://fluxcd.io/flux/guides/helmreleases/#refer-to-values-in-configmap-and-secret-resources

**Comment by stavros-k** [comment]
I'm not sure if Plex stops listening to `http` when `required` is selected.
Even on their `HEALTHCHECK` on their Dockerfile the `http` is hardcoded and not dynamic.

Are there any proofs that it does indeed stops listening to `http`? And it's not a redirect?

**Comment by xeor** [comment]
When I set the value to required, the server continue to work, but was killed by k8s by failed liveness-probe

```
  Warning  Unhealthy  8m29s                  kubelet            Readiness probe failed: Get "http://10.x.x.x:32400/identity": dial tcp 10.x.x.x:32400: connect: connection refused
  Warning  Unhealthy  8m14s (x5 over 29m)    kubelet            Startup probe failed: Get "http://10.x.x.x:32400/identity": dial tcp 10.16.x.x:32400: connect: connection refused
  Warning  Unhealthy  14s (x90 over 8m9s)    kubelet            Startup probe failed: Get "http://10.x.x.x:32400/identity": EOF
```

I got a couple of minutes between each time it got killed, so I was able to set the config back without too much issues.
When the config was back, health-checks are succeeding again.

**Comment by stavros-k** [comment]
I've switched to to tcp probe, which should work no matter the http protocol.

**Comment by xeor** [comment]
Confirming the fix working like a charm!

Wow, that was efficient fix! ~30 minutes for reporting, fixing, testing, releasing, upgrading, verifying! 🥇
