### ISSUE TITLE
Community charts suggestion: qbittorrent

### ISSUE THREAD

**Issue by Emalton** [truenas/charts#1095]
It would be great if qbittorrent was added!

**Comment by kmoore134** [comment]
This is already added to the community train:

https://github.com/truenas/charts/tree/master/community/qbittorrent

It will become visible on 22.12.2 next week, or if you are impatient, you can go to Apps -> Manage Catalogs -> Official -> Edit (Three Dot Menu) and select the community train under "Preferred Trains"
