### ISSUE TITLE
Hard to pull images on ghcr.io & Cannot update the storage configuration after installing

### ISSUE THREAD

**Issue by BreakVoid** [truenas/charts#1112]
After I install the new community version of qBittorrent, I found two issues.

1. The previous official chart of qBittorrent uses the images from linuxserver(lscr.io/linuxserver/qbittorrent:<version>), while the current community version uses the images from ghcr.io, which is hard to pull in China. I have to manually pull it by setting a proxy. Could it use the previous image source?

2. The storage configuration cannot be modified after installation (as shown in the figure).
<img width="744" alt="截屏2023-04-12 11 50 23" src="https://user-images.githubusercontent.com/8384350/231345070-101734b6-e01d-43c7-a430-555eb894242c.png">

My TrueNAS version: 22.12.2

**Comment by alexislefebvre** [comment]
Do you have the same issues when you download images from Red Hat's [Quay Container Registry](https://quay.io/)? It may be used as an alternative to GHCR, if it's possible to build images once then push them to GHCR and Quay. Then TrueNAS would have to allow to choose between GHCR and Quay as the source of the images.

Example:

```bash
docker pull quay.io/prometheus/prometheus
```

**Comment by BreakVoid** [comment]
The following command is executed successfully on my NAS.
```docker pull quay.io/prometheus/prometheus```
I think it should be a good solution if there is no other issue.

**Comment by stavros-k** [comment]
A better improvement here would be to "Support at least 2 registries when possible"

**Comment by stavros-k** [comment]
Unfortunately there are currently no plans to support multiple registries per image as it's not always in sync and hard to maintain.

But you can now use docker/docker compose in 24.10 and later, and use any image you want.
Also the ability to convert apps to custom yaml apps is coming on next release https://github.com/truenas/webui/pull/11109
So it should help as well
