### ISSUE TITLE
Unable to locate 'ix-chart'

### ISSUE THREAD

**Issue by leroyvandijk** [truenas/charts#1115]
Hi,

I'm having this issue since the last truenas update this morning.
I can't press the button Launch Docker Image in TrueNAS Scale. I'm running TrueNAS-SCALE-22.12.2

This is the error that is printed to the console:

`[ENOENT] Unable to locate 'ix-chart' at '/mnt/SSD/ix-applications/catalogs/github_com_truenas_charts_git_master/charts/ix-chart'`

Is there some kind of fix for this?

Kind regards,

Leroy

**Comment by Qubad786** [comment]
Fixed in https://github.com/truenas/charts/pull/1116

**Comment by Qubad786** [comment]
@leroyvandijk you need to refresh the official catalog and it will work ✅

**Comment by leroyvandijk** [comment]
Thanks, it works!
