### ISSUE TITLE
[Request] Ingress Support

### ISSUE THREAD

**Issue by Heavybullets8** [truenas/charts#1120]
Traefik is a popular and widely-used Ingress controller for Kubernetes that supports dynamic configuration and is easy to integrate with various backends.

The per app options suggested include:
- **Input a domain name**: Allowing users to specify a domain name for each application.
- **Choose your certificate created from the credentials > certificates page**: Allowing users to select an SSL/TLS certificate for securing the domain, if they choose. 
- **Choose the path**: Specifying the path for the application, which is a part of the URL.
- **Middlewares**: Allowing users to apply additional middleware configuration (e.g., authentication, rate limiting, etc.) for the application.

This feature would make it easier for TrueNAS SCALE users to manage their applications through a reverse proxy and access them via a domain name.

**Comment by Dremor** [comment]
The lack of Ingresses is the main reason I have to only use Truecharts charts. 

As an user, I expect to be able to put a domain name like any other website, and to get access the right service, over https, without having to remember on which port I put that specific service.

**Comment by CompPhy** [comment]
I was actually thinking about this today and came across this thread.  In today's charts we already have nginx-proxy-manager working, but it's explicitly NOT allowed to use host network.  Maybe another solution here is to just require that host network is bound on a separate bridged interface?

For example, I would setup a bridge interface on the TrueNAS network side; with a unique IP address on the network.  Then nginx-proxy-manager binds that interface specifically and not the main network interface, where TrueNAS UI is being hosted.

Maybe I'm missing something here, but shouldn't that allow nginx to bind on port 80/443 and act like an ingress controller?  In theory, this gives TrueNAS a way to handle ingress without it having to be directly supported through the TrueNAS UI.  Sure, the end user has to setup nginx-proxy-manager themselves, but at least it gives some option for using standard ports.

Although, admittedly, I think we would all prefer if there was just an ingress controller already there.  Even if it was on a nested URL, underneath the TrueNAS UI, it sure would be nice if TrueNAS just had some built-in ingress support.
