### ISSUE TITLE
Community qBittorrent support for VPN

### ISSUE THREAD

**Issue by wadebee** [truenas/charts#1133]
Would it be possible to add the necessary config to allow for VPN setup? 

I know the TrueChart qBittorrent install supports VPN but I would like to move to the IX Community offering if this enhancement is available.

**Comment by adamreed90** [comment]
This is a great container, this would be a great replacement for the underlying image the chart is using. https://github.com/binhex/arch-qbittorrentvpn

**Comment by R7JANV1** [comment]
Unfortunately, it is not possible to use this app without the VPN function.

**Comment by R7JANV1** [comment]
Unfortunately, it is not possible to use this app without the VPN function.

**Comment by Marimax01** [comment]
You can create a container with your VPN (I used cybergosht) it will behave like a proxy that must be entered in the qBittorent parameters (via UI)

**Comment by Tontze** [comment]
> This would be a great replacement for the underlying image the chart is using. https://github.com/binhex/arch-qbittorrentvpn

Im using this via docker compose yaml. Works.

**Comment by stavros-k** [comment]
After https://github.com/truenas/apps/issues/743 is implemented, you could probably have a vpn app, and then connect any other app to use that network.

Please follow the linked issue. Until then you can use a custom app.

Thanks
