### ISSUE TITLE
Radarr update failed

### ISSUE THREAD

**Issue by Maxoobidou** [truenas/charts#1143]
Hello,

When trying to update Radarr from 4.4.4.7068_1.0.2 to 4.4.4.7068_1.0.3, I get the following error message :
![image](https://user-images.githubusercontent.com/131298128/233169778-6acde008-18ac-4329-8b74-65faeea8b40b.png)

Truenas SCALE 22.12.2, everything is working smooth except for that.

**Comment by Maxoobidou** [comment]
Here is what is inside the "More info" box : 

> Error: Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/middlewared/job.py", line 426, in run
>     await self.future
>   File "/usr/lib/python3/dist-packages/middlewared/job.py", line 461, in __run_body
>     rv = await self.method(*([self] + args))
>   File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1318, in nf
>     return await func(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1186, in nf
>     res = await f(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 115, in upgrade
>     await self.upgrade_chart_release(job, release, options)
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 265, in upgrade_chart_release
>     config, context = await self.middleware.call(
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1386, in call
>     return await self._call(
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1335, in _call
>     return await methodobj(*prepared_call.args)
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 338, in normalise_and_validate_values
>     dict_obj = await self.middleware.call(
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1386, in call
>     return await self._call(
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1335, in _call
>     return await methodobj(*prepared_call.args)
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 71, in validate_values
>     verrors.check()
>   File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
>     raise self
> middlewared.service_exception.ValidationErrors: [EINVAL] chart_release_create.radarrStorage.config.hostPath: '.' 'path' not allowed to be mounted

**Comment by aednichols** [comment]
What is your setting for [host path safety checks](https://www.truenas.com/docs/scale/scaletutorials/apps/customizing-advanced-kubernetes-settings/configuring-host-path-safety-checks/)?

**Comment by Maxoobidou** [comment]
Disabling it worked. That's weird I have no share set up.
I'll re-enable it now that the update installed.

Thank you !

**Comment by stavros-k** [comment]
Glad you resolved your issue, I'll close the issue for now, if you encounter anything, please let me know.
Thanks

**Comment by kpervin** [comment]
@stavros-k given that apps can be initialized when Host Path Safety Checks are in place, why can apps not be updated when this is the case?
