### ISSUE TITLE
Cannot update Sonarr or Radarr

### ISSUE THREAD

**Issue by kpervin** [truenas/charts#1168]
|App Name|Version|
|------------|--------|
|Sonarr|3.0.10.1567_1.0.2|
|Radarr|4.4.4.7068_1.0.4|

TrueNAS SCALE version: 22.12.2

Anytime I try to update these community charts, I get the following error: `chart_release_create.sonarrStorage.config.hostPath: '.' 'path' not allowed to be mounted`

![markuphero-vqWrxCsvquqejBjLreJy](https://user-images.githubusercontent.com/7747148/235373244-e7049366-954d-473a-90b7-b61c93b1270c.png)

**Comment by Maxoobidou** [comment]
Does the procedure described here solves it ?
https://github.com/truenas/charts/issues/1143

**Comment by Qubad786** [comment]
@kpervin i am not able to reproduce with latest sonarr version..
Can you create a ticket at https://ixsystems.atlassian.net/ and make sure to attach a debug of the system after reproducing the problem ✅ ?

**Comment by kpervin** [comment]
@Qubad786 I will do that if I run into the issue going forward, as I did disabled Host Path Security and updated fine. If the issue persists, I will send a bug report.

**Comment by kpervin** [comment]
@Qubad786 this is still an issue with the newest update:

Sonarr 1.0.5 -> 1.0.6
Radarr 1.0.7 -> 1.0.8

**Comment by Qubad786** [comment]
@kpervin please go through https://www.truenas.com/docs/_includes/createdebugscale/
