### ISSUE TITLE
Nginx Proxy Manager do not start on bare-metal HDD based pools, but works on virtual disks and SSDs

### ISSUE THREAD

**Issue by Dremor** [truenas/charts#1212]
I got a strange one for you today.

Nginx Proxy Manager seem to be unable to start, for an unknown reason. But specifically on HDD based pools, not virtual one (from a virtualized TrueNAS), nor SSDs based one.

I've setup 3 different pools as follow:

- 2x4To Ironwolf, mirrored, unencrypted
- 2x4To Ironwolf, mirrored, encrypted
- 2x500Go WD Red SSDs, encrypted

For each pool I did the following, from the freshly created pool.

- Set K3S to said pool, from the UI
- Start a new nginx-proxy-manager deployment
- Wait for it do come online and accessible

On the SSDs array, no problem. On both HDDs arrays, nginx-proxy-manager refuse to start and go on a boot loop.

No other deployment, be it from the official or community trains, seem to be affected.

Should I call an exorcist for my HDDs? ^^"

**Comment by Dremor** [comment]
May be linked to this issue : https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2889

**Comment by mr47** [comment]
Tested with latest charts it's the same for me, clean apps install HDDs

**Comment by mr47** [comment]
[nginx-proxy-manager-2_nginx-proxy-manager-2-6d685f5cd-8xpwd_nginx-proxy-manager-2.log](https://github.com/truenas/charts/files/11548661/nginx-proxy-manager-2_nginx-proxy-manager-2-6d685f5cd-8xpwd_nginx-proxy-manager-2.log)


[k3s kubectl describe pod.txt](https://github.com/truenas/charts/files/11548681/k3s.kubectl.describe.pod.txt)

**Comment by mr47** [comment]
cc @stavros-k

**Comment by n3wtype** [comment]
Despite PR https://github.com/truenas/charts/pull/1216 it's still not working. 

logs from app:
`2023-05-30 09:04:09.402151+00:00[1;34m❯ [1;36mConfiguring npm user ...[0m
2023-05-30 09:04:55.764835+00:00[1;34m❯ [1;36mConfiguring npm group ...[0m
2023-05-30 09:04:56.104728+00:00[1;34m❯ [1;36mChecking paths ...[0m
2023-05-30 09:05:03.677691+00:00[1;34m❯ [1;36mSetting ownership ...[0m`

output from ps (chown from nginx-proxy-manager lives since 6m:
`
root@truenas[~]# ps aux | grep chown
root     2945469  0.0  0.0   2552   964 ?        D    11:05   0:00 chown -R 1000:1000 /opt/certbot
root     2962101  0.0  0.0   5136   560 pts/1    S+   11:10   0:00 grep chown
root@truenas[~]# date
Tue May 30 11:11:01 CEST 2023` 

strace from chown process:
`
root@truenas[~]# strace -tp 2945469
strace: Process 2945469 attached
11:11:43 fchownat(4, "LICENSE.BSD", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:47 fchownat(4, "REQUESTED", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:47 fchownat(4, "AUTHORS.rst", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:50 fchownat(4, "WHEEL", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:54 fchownat(4, "METADATA", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:55 fchownat(4, "RECORD", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:56 close(4)                       = 0
11:11:56 fchownat(7, "cryptography-2.8.dist-info", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:11:56 fchownat(7, "configargparse.py", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
11:12:00 newfstatat(7, "parsedatetime", {st_mode=S_IFDIR|0755, st_size=8, ...}, AT_SYMLINK_NOFOLLOW) = 0
11:12:00 openat(7, "parsedatetime", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 3
11:12:00 fstat(3, {st_mode=S_IFDIR|0755, st_size=8, ...}) = 0
11:12:00 fcntl(3, F_GETFL)              = 0x38800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE|O_NOFOLLOW|O_DIRECTORY)
11:12:00 fcntl(3, F_SETFD, FD_CLOEXEC)  = 0
11:12:00 fcntl(3, F_DUPFD_CLOEXEC, 3)   = 4
11:12:00 getdents64(3, 0x55825e4a3760 /* 8 entries */, 131072) = 248
11:12:00 getdents64(3, 0x55825e4a3760 /* 0 entries */, 131072) = 0
11:12:00 close(3)                       = 0
11:12:00 fchownat(4, "__init__.py", 1000, 1000, AT_SYMLINK_NOFOLLOW) = 0
`

As you can see in strace output chown is making syscalls every few second and is totally to slow. Underlaying storage is mirror of healthy SSD disks.

**Comment by Dremor** [comment]
> Tested with latest charts it's the same for me, clean apps install, HDDs

In my case it works after 6-7 min, HDD with metadata on an SSD mirror (recommended setup by Truecharts). Still slow as hell.

**Comment by n3wtype** [comment]
I can confirm that workaround works. Still root cause exists.

**Comment by J-Stuff** [comment]
> There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> 
> ```dotenv
> S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> ```
> 
> This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools

Thank you SO MUCH. I've been looking for a workaround for ages while being stuck on v2.9.22

**Comment by asaura08** [comment]
> There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> 
> ```dotenv
> S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> ```
> 
> This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools

It´s works, thx

**Comment by kmoore134** [comment]
Confirmed that work-around worked here as well

**Comment by roburtooo** [comment]
> There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> 
> ```dotenv
> S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> ```
> 
> This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools

How to add this env variable and where ? Please help.

**Comment by fastSimulations** [comment]
> > There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> > ```dotenv
> > S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools
> 
> How to add this env variable and where ? Please help.

When you install NGINX Proxy Manager in TrueNas you can add additional environment variables.

There is a button beside the words "additional environmental variables" that says add, click it.

Then enter "S6_STAGE2_HOOK" in the Name field and "sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh" in the Value field.

**Comment by roburtooo** [comment]
> > > There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> > > ```dotenv
> > > S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools
> > 
> > 
> > How to add this env variable and where ? Please help.
> 
> When you install NGINX Proxy Manager in TrueNas you can add additional environment variables.
> 
> There is a button beside the words "additional environmental variables" that says add, click it.
> 
> Then enter "S6_STAGE2_HOOK" in the Name field and "sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh" in the Value field.

This method works ;)))))
Thx.

**Comment by RaulGw4** [comment]
> There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> 
> ```dotenv
> S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> ```
> 
> This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools

![Screenshot_1](https://github.com/truenas/charts/assets/116492323/a06ab917-ac7e-4e7d-8671-4020fc9f104b)
![Screenshot_2](https://github.com/truenas/charts/assets/116492323/9a248073-1b55-42d8-9c3a-f5cfa6c4aab8)
![Screenshot_3](https://github.com/truenas/charts/assets/116492323/76c213b5-5d93-40d2-b41c-138f1a0be2b1)
![Screenshot_4](https://github.com/truenas/charts/assets/116492323/da163c4d-0e5c-44ee-9495-15bcdb7ed3e0)

I also have a similar issue as other people. I have tried your hack but with no luck. I have no idea what to do from here.

**Comment by fastSimulations** [comment]
> > There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> > ```dotenv
> > S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/116492323/341131665-a06ab917-ac7e-4e7d-8671-4020fc9f104b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjY1LWEwNmFiOTE3LWFjN2UtNGU3ZC04NjcxLTQwMjBmYzlmMTA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDEzMzg1MzM0YWQ5MjZkMDVmYTM5ZTkwMjBiNzlhNzBkNWQ1NDQ1NDJhYzFjOWJiZmE5NDk5M2NiODJjNGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xIYJXjEZeYGbG8o4CsBxLFuvkoWrklX_nUtgf8WgJIY) ![Screenshot_2](https://private-user-images.githubusercontent.com/116492323/341131667-9a248073-1b55-42d8-9c3a-f5cfa6c4aab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjY3LTlhMjQ4MDczLTFiNTUtNDJkOC05YzNhLWY1Y2ZhNmM0YWFiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGMxNmZiOWVkZWZlYTQxZTg4NmIyY2EwYWYyMTI3NWJmYjBmMjU3ZGQ3OGIxZGYwMWY3YWY3NDhkODM3Zjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6M6ej5fdaaDU0vq2dp9fiEIBJ4yXgtP9Q5hs6v1EowM) ![Screenshot_3](https://private-user-images.githubusercontent.com/116492323/341131671-76c213b5-5d93-40d2-b41c-138f1a0be2b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjcxLTc2YzIxM2I1LTVkOTMtNDBkMi1iNDFjLTEzOGYxYTBiZTJiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTdjOGE3MmUwZjA1YTI2NDE4ZjRjYTIyYTc2MzEzZTg4YjYzN2JjOWFiNmNhMGUyZTIyMzcxMTUwOTdhOGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PF1g0UOqasYyYGEu3Z-h2ojT5sp2MAPHQ3gYTXKAK7Y) ![Screenshot_4](https://private-user-images.githubusercontent.com/116492323/341131673-da163c4d-0e5c-44ee-9495-15bcdb7ed3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjczLWRhMTYzYzRkLTBlNWMtNDRlZS05NDk1LTE1YmNkYjdlZDNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGRlYzY1Y2I4M2E4NjViOWFhMTY5ZmExMGVkMGQ1NTRkZmIzMDliNzUyOGI2ZGE5ZTFiOWFlYzdiMTZhMDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3DZ52Baus1TQx4MSF_Zg1atbPpjMYfMh03IPMy8pogw)
> 
> I also have a similar issue as other people. I have tried your hack but with no luck. I have no idea what to do from here.

Hi there, you've entered the details incorrectly in the proxy manager setup

in the ENV variable:

your first line is correct with 'S6_STAGE2_HOOK'

However, your second line is wrong.  You entered 'S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh'

you do not enter the part with S6_STAGE2_HOOK again, your value line should be simply this:

'sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh'

cheers!

**Comment by RaulGw4** [comment]
> > > There is a dirty hack to fix this issue is using s6 hook Add to env variable following:
> > > ```dotenv
> > > S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This will remove the last line that was added in version 2.10+ chown -R "$PUID:$PGID" /opt/certbot with takes a long time on HDD pools
> > 
> > ![Screenshot_1](https://private-user-images.githubusercontent.com/116492323/341131665-a06ab917-ac7e-4e7d-8671-4020fc9f104b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjY1LWEwNmFiOTE3LWFjN2UtNGU3ZC04NjcxLTQwMjBmYzlmMTA0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDEzMzg1MzM0YWQ5MjZkMDVmYTM5ZTkwMjBiNzlhNzBkNWQ1NDQ1NDJhYzFjOWJiZmE5NDk5M2NiODJjNGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xIYJXjEZeYGbG8o4CsBxLFuvkoWrklX_nUtgf8WgJIY) ![Screenshot_2](https://private-user-images.githubusercontent.com/116492323/341131667-9a248073-1b55-42d8-9c3a-f5cfa6c4aab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjY3LTlhMjQ4MDczLTFiNTUtNDJkOC05YzNhLWY1Y2ZhNmM0YWFiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGMxNmZiOWVkZWZlYTQxZTg4NmIyY2EwYWYyMTI3NWJmYjBmMjU3ZGQ3OGIxZGYwMWY3YWY3NDhkODM3Zjk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6M6ej5fdaaDU0vq2dp9fiEIBJ4yXgtP9Q5hs6v1EowM) ![Screenshot_3](https://private-user-images.githubusercontent.com/116492323/341131671-76c213b5-5d93-40d2-b41c-138f1a0be2b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjcxLTc2YzIxM2I1LTVkOTMtNDBkMi1iNDFjLTEzOGYxYTBiZTJiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTdjOGE3MmUwZjA1YTI2NDE4ZjRjYTIyYTc2MzEzZTg4YjYzN2JjOWFiNmNhMGUyZTIyMzcxMTUwOTdhOGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PF1g0UOqasYyYGEu3Z-h2ojT5sp2MAPHQ3gYTXKAK7Y) ![Screenshot_4](https://private-user-images.githubusercontent.com/116492323/341131673-da163c4d-0e5c-44ee-9495-15bcdb7ed3e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDc3NzcsIm5iZiI6MTcxOTI0NzQ3NywicGF0aCI6Ii8xMTY0OTIzMjMvMzQxMTMxNjczLWRhMTYzYzRkLTBlNWMtNDRlZS05NDk1LTE1YmNkYjdlZDNlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNFQxNjQ0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGRlYzY1Y2I4M2E4NjViOWFhMTY5ZmExMGVkMGQ1NTRkZmIzMDliNzUyOGI2ZGE5ZTFiOWFlYzdiMTZhMDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3DZ52Baus1TQx4MSF_Zg1atbPpjMYfMh03IPMy8pogw)
> > 
> > I also have a similar issue as other people. I have tried your hack but with no luck. I have no idea what to do from here.
> 
> Hi there, you've entered the details incorrectly in the proxy manager setup
> 
> in the ENV variable:
> 
> your first line is correct with 'S6_STAGE2_HOOK'
> 
> However, your second line is wrong.  You entered 'S6_STAGE2_HOOK=sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh'
> 
> you do not enter the part with S6_STAGE2_HOOK again, your value line should be simply this:
> 
> 'sed -i $d /etc/s6-overlay/s6-rc.d/prepare/30-ownership.sh'
> 
> cheers!

🤦‍♂️
I did not see that at all.
Thanks man!
