### ISSUE TITLE
Nextcloud migration not possible

### ISSUE THREAD

**Issue by ghost** [truenas/charts#1273]
To migrate from an existing Nextcloud to the Nextcloud app there must be a way to access the database to import the existing database dump.

**Comment by R7JANV1** [comment]
A possible solution would be to expose the database (for example with a checkbox).

insert a button that makes the database accessible externally on port 5432 when the check box is activated. If the check box is not checked, the behavior would be the same as it is now.

**Comment by R7JANV1** [comment]
Or make it possible to make ports accessible yourself, as is also the case with your own containers.

![grafik](https://github.com/truenas/charts/assets/90777102/deb898e3-f1de-4f51-baf6-2b2fd5293e91)

**Comment by stavros-k** [comment]
With https://github.com/truenas/charts/pull/1484 and https://github.com/truenas/charts/pull/1387
It should be possible to perform db actions. Keep in mind that the details will be display on the WebUI only on Cobia releases.
