### ISSUE TITLE
Nginx Proxy Manager permissions keep reverting back to apps:apps after a while (3-4 days)

### ISSUE THREAD

**Issue by MadMungo** [truenas/charts#1275]
As per the title, my Nginx proxy manager install will keep having its permissions set back to apps:apps from the default 1000:1000 set during the install/setup of the app. I use Hostpath for the storage, it is where I have all my app configs and dose not have any sharing setup.

**Comment by stavros-k** [comment]
This chart does not have any tasks changing permissions at any time.
Is the this host path used for other apps/tasks? Maybe those apps perform and action that changes the permissions?

**Comment by MadMungo** [comment]
Yes I do and thanks for the heads up.

The culprit is my Jackett docker image, every time it updates, it chowns the config folder. I have changed the layout of my config folder to hopefully prevent it from happening in future.
