### ISSUE TITLE
qbittorrent can't use

### ISSUE THREAD

**Issue by chxbw** [truenas/charts#1290]
I have installed qbittorrent in version 22.12.3.1 of SCALE, but I cannot open qbittorrent's web interface. I tried to open it using my device's IP address and port, but it doesn't work. Do you know what could be the problem? Also, I am unable to mount the download directory to the SMB directory.

![1](https://github.com/truenas/charts/assets/81037550/34da243a-409d-42de-9807-6dd1c5db98ea)
![2](https://github.com/truenas/charts/assets/81037550/02f6d350-f538-4ea4-baef-b0665f0ec6db)
![3](https://github.com/truenas/charts/assets/81037550/a1944e64-1a70-4b56-9ce4-253dcb6dd3de)

**Comment by stavros-k** [comment]
Does other apps work?
Looks like the whole node is not in a working state.

**Comment by stavros-k** [comment]
Considering there is no answer for over a month, I'll close the issue.
If you still experience issues, please let me know.
