### ISSUE TITLE
JellyFin port mismatch

### ISSUE THREAD

**Issue by daaain** [truenas/charts#1296]
I might have got this totally wrong, but the chart doesn't seem to use the Web Port setting on the form.

Trying to open the default 30013 for the web UI (by clicking on the Web Portal button) leads nowhere, but using 8096 that I found in [a guide](https://forum.level1techs.com/t/getting-started-with-truenas-scale-part-3-installing-jellyfin-via-the-gui-apps-explainer/183512) I was reading in despair it worked.

<img width="512" alt="image" src="https://github.com/truenas/charts/assets/69962/3d86dd6a-bad5-4c73-b18e-a0b0f92e76d1">

<img width="764" alt="image" src="https://github.com/truenas/charts/assets/69962/42e02910-3ca5-4eed-b5bd-9b59aebfae9f">

I actually also just noticed that 8096 port displayed on the app popup too:

<img width="795" alt="image" src="https://github.com/truenas/charts/assets/69962/bbe836f5-d466-49ba-8914-2242afd99cd9">

**Comment by stavros-k** [comment]
Hello, when using Host Network the internal port of the container is not always configurable.
In this case it is not. I'm issued a fix, to hide the port field when hostnetwork is enabled and also take this into account for the "Web Portal" button

Thanks

**Comment by daaain** [comment]
Oh, I had the feeling it might be related to the Host Network setting...

Thanks a lot for the quick fix!
