### ISSUE TITLE
Community Charts Suggestion: Unifi Controller

### ISSUE THREAD

**Issue by CompPhy** [truenas/charts#1367]
It would be nice to have UniFi Network Server (aka UniFi Controller) in community charts.  The linuxserver.io folks make a nice docker build already, so maybe we can just use that?  I might be able to take a crack at this one in the future, if no one else gets to it first.

https://ui.com/download
https://docs.linuxserver.io/images/docker-unifi-controller
https://hub.docker.com/r/linuxserver/unifi-controller

**Comment by BlauerHunger** [comment]
truecharts already has a chart for that, maybe that helps in adding one here
