### ISSUE TITLE
iPhone videos not playing with current photoprism install

### ISSUE THREAD

**Issue by immanuelsmith** [truenas/charts#1404]
1. What is not working as documented?

Video playback of iPhone HEVC video is not working.
2. How can we reproduce it?

Add an originals directory containing an iPhone video and index it. Try to open it from the videos folder or by manually browsing to its location. It will fail to play and instead show a 1-second video of CRT static
3. What behavior do you expect?

The video should play. It plays regular MP4's
4. What could be the cause of your problem?

I think it has something to do with transcoding. I have tried to turn off the FFPMEG transcoder and it has no effect.
5. Can you provide us with example files for testing, error logs, or screenshots?

I don't have any I can share as they are all personal videos, but any regular iPhone HEVC video will cause the issue (has to be .mov format, NOT slo-mo or any other type of video requiring a settings change).

Log with FFMPEG disabled:
2023-07-25 07:13:31 ERRO video: transcoding '******/05404_IMG_1747.MOV' failed

Log with FFMPEG enabled:
2023-07-25 06:43:09 ERRO video: transcoding '****/01544_3A325C8B-B91A-40D6-B3BB-5DAC880D4CE6.MOV' failed
2023-07-25 06:43:09 WARN libx264: failed transcoding ****/01544_3A325C8B-B91A-40D6-B3BB-5DAC880D4CE6.MOV [145.628904ms]
2023-07-25 06:43:09 INFO libx264: transcoding ****/01544_3A325C8B-B91A-40D6-B3BB-5DAC880D4CE6.MOV to avc
6. Which software versions do you use?

Photoprism Build [221118-e58fee0]
Current community build for truenas as of 7/25

From Truenas -
Version:
g20221118
Plugin:
photoprism
Release:
12.4-RELEASE-p3

Stock MariaDB database, no changes made to anything.
7. On what kind of device is PhotoPrism installed?

NAS with a AMD Ryzen 5 3600 6-Core Processor, 16GB of ECC memory, 3x6TB drives in a ZFS pool (Raid 5). It has an Nvidia card for display output but I don't think it is supported by truenas core for any sort of video acceleration
8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

I don't think so.

Issue was posted here as well https://github.com/photoprism/photoprism/discussions/3574

**Comment by stavros-k** [comment]
Based on the linked issue, you are using TrueNAS Core.
I'll suggest to create a ticket at https://jira.ixsystems.com/

I'll close this one now, as it's not related to the Photoprism chart.

Thanks

**Comment by immanuelsmith** [comment]
> Based on the linked issue, you are using TrueNAS Core. I'll suggest to create a ticket at https://jira.ixsystems.com/
> 
> I'll close this one now, as it's not related to the Photoprism chart.
> 
> Thanks

it is not an ixsystems truenas plugin, it is a community maintained plugin. where do I go to get assistance with that?

**Comment by stavros-k** [comment]
> > Based on the linked issue, you are using TrueNAS Core. I'll suggest to create a ticket at https://jira.ixsystems.com/
> > I'll close this one now, as it's not related to the Photoprism chart.
> > Thanks
> 
> it is not an ixsystems truenas plugin, it is a community maintained plugin. where do I go to get assistance with that?

In that case, most likely on the TrueNAS forums https://www.truenas.com/community/
