### ISSUE TITLE
The newest version of Tdarr requires NVIDIA drivers for GPU processing that are not present in the latest version of TrueNAS

### ISSUE THREAD

**Issue by TristanHarms** [truenas/charts#1409]
When updating Tdarr to the latest chart version, GPU transcoding will fail with the following messages:

> Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
> The minimum required Nvidia driver for nvenc is 520.56.06 or newer

This is because the current driver version of TrueNAS is `515.65.01`.

There are several sources confirming this behavior, e.g. [this GitHub post](https://github.com/HaveAGitGat/Tdarr/issues/797#issuecomment-1651877407) and [this discord message](https://discord.com/channels/623392507828371476/623799920574595092/1128089775790887032).

I could create a PR myself to downgrade the version of Tdarr as this means the latest chart version is literally unusable for every TrueNAS user that doesn't upgrade their kernel/nvidia-drivers themselves (which is not recommended, to say at the least), but I first wanted to create an issue to start the discussion. Thoughts?

**Comment by Qubad786** [comment]
@stavros-k can you create a ticket for middleware?
It appears we should have nvidia drivers later then 515..
