### ISSUE TITLE
Questions vocabulary missing textarea/toml input

### ISSUE THREAD

**Issue by razvanphp** [truenas/charts#1427]
Hello,

While implementing and adapting the [gitlab-runner chart](https://gitlab.com/lab-scale/catalog/-/blob/main/charts/gitlab-runner/0.9.0/questions.yaml?ref_type=heads) in our own train/catalog, me & @jonct realised there is no way to specify a custom config multi-line text via the web interface.

In this case, it is toml config format, please see the [example in the official chart](https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml?ref_type=heads#L316).

Something in values.yaml as complicated as:
```
config: |
  [runners.cache]
    Type = "s3"
    Path = "path/to/prefix"
    Shared = false
    [runners.cache.s3]
      ServerAddress = "s3.amazonaws.com"
      AccessKey = "AWS_S3_ACCESS_KEY"
      SecretKey = "AWS_S3_SECRET_KEY"
      BucketName = "runners-cache"
      BucketLocation = "eu-west-1"
      Insecure = false
      ServerSideEncryption = "KMS"
      ServerSideEncryptionKeyID = "alias/my-key"

```

To our understanding, this cannot be implemented elegantly without new UX, but please let us know if we're missing something. The idea is not to implement [dozens of configs possible](https://docs.gitlab.com/runner/configuration/advanced-configuration.html), but to allow advanced usage and full customisation for power users.

Original discussion can be seen [here](https://gitlab.com/lab-scale/catalog/-/issues/1).

BTW, we would love to have it included in the community train.

Thank you in advance!
R

**Comment by stavros-k** [comment]
Partial solved by: https://github.com/truenas/catalog_validation/pull/88
(Still needs UI work)

**Comment by razvanphp** [comment]
Great, thank you!

Now that I think of it, theoretically we can also use this to customise `values.yaml`
