### ISSUE TITLE
Plex has no TV tuner hardware access

### ISSUE THREAD

**Issue by Blazin64** [truenas/charts#143]
One of Plex's major features is the ability to view and record TV broadcasts. Unfortunately, the current chart does not have access to the `/dev/dvb/` directory. This prevents the use of USB and PCIe-based TV tuner devices.

It would be fantastic if TV tuner access could be implemented for the Plex chart.

I don't know how much this would involve, but I'm guessing this would at least require a Kubernetes device plugin. Maybe something like [k8s-generic-device-plugin](https://github.com/rkojedzinszky/k8s-generic-device-plugin), [k8s-host-device-plugin](https://github.com/everpeace/k8s-host-device-plugin), or [smarter-device-manager](https://gitlab.com/arm-research/smarter/smarter-device-manager) could be used?

**Comment by Ornias1993** [comment]
> > > One of Plex's major features is the ability to view and record TV broadcasts. Unfortunately, the current chart does not have access to the `/dev/dvb/` directory. This prevents the use of USB and PCIe-based TV tuner devices.
> > > It would be fantastic if TV tuner access could be implemented for the Plex chart.
> > > I don't know how much this would involve, but I'm guessing this would at least require a Kubernetes device plugin. Maybe something like [k8s-generic-device-plugin](https://github.com/rkojedzinszky/k8s-generic-device-plugin), [k8s-host-device-plugin](https://github.com/everpeace/k8s-host-device-plugin), or [smarter-device-manager](https://gitlab.com/arm-research/smarter/smarter-device-manager) could be used?
> > 
> > 
> > TrueCharts Plex might be better suited to your wishes, as we allow all sorts of random device mounts from /dev ;-)
> 
> Your right Truecharts does well with add directory's but Dev/ folders that require drivers needs the support of Jira Team as well
> 
> The reporter needs' to see if the Dev folder even exists on the host system and host system is able to properly use device as intended otherwise adding dev dir without proper drivers will do nothing but if the contributor wants to help the more eyes on it the better. i would make Sure the docker image support the tunner devices. I seem to remember a while ago that feature was not support in the docker image i do not mean the current docker image but an earlier one

Im telling you you dont need the Jira Team, we ALREADY support this out-of-the-box.

We even added it to every App 2 weeks ago instead of only select Apps.

**Comment by Ornias1993** [comment]
@sonicaj or @Qubad786 can be closed.

**Comment by sonicaj** [comment]
@Saberwolf64 we allow mounting host paths inside the app. Apart from that ensuring that the docker image has support for specific features, i am sorry we wouldn't be ensuring that as we have no intention of shipping our own image for plex. We are using upstream docker image of plex - so feel free to create an issue with them please to request that they add proper support on that end. If you notice anything missing on our end wrt that, let us know and we can account for it appropriately then. Thanks!
