### ISSUE TITLE
[Issue] Nextcloud: Could not update breached passwords database

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#1443]
Steps to reproduce:
1. Install Nextcloud
2. Install the Passwords App
3. Wait some time
4. See the following notification pop up
![Bildschirmfoto vom 2023-08-13 13-43-48](https://github.com/truenas/charts/assets/137991389/9ce90fe1-cd01-466e-bab7-95d554f5dbb9)

https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Notifications/Breached-Passwords-Update-Failure-Notification

**Comment by stavros-k** [comment]
Hello, can you check nextcloud's logs, see if there is more info there?

**Comment by stavros-k** [comment]
Looks like it requires a `max_execution_time` to be 2hours(!).

https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Services/Password-Security-Check-Services#big-local-database-25m-passwords

I'll see if we can efficiently provide a field for changing the `max_execution_time`

**Comment by stavros-k** [comment]
You might have to reset the counter of failed tries.
https://git.mdns.eu/nextcloud/passwords/-/wikis/Administrators/Notifications/Breached-Passwords-Update-Failure-Notification

Beyond that, I'd suggest contacting the support channels of the specific plugin
