### ISSUE TITLE
Fail to upload snapshot files to nextcloud (HTTPError: Response code 413 (Request Entity Too Large)) ! 

### ISSUE THREAD

**Issue by 645340633** [truenas/charts#1455]
I use homeaassistant addon ( [hassio-nextcloud-backup](https://github.com/Sebclem/hassio-nextcloud-backup)) to backup the snapshot  files, but occurs Fail to upload snapshot files to nextcloud (HTTPError: Response code 413 (Request Entity Too Large)) ! 
![issue](https://github.com/truenas/charts/assets/80463778/ed09f4c2-c5c9-4703-887f-102290db24e9) What should I do to solve the problem

My snapshot backup file is 6GB ,This is what I set，but it seems doesn't work
![1](https://github.com/truenas/charts/assets/80463778/653f4568-ac84-481e-ab0c-2a9c7226c6d1)
![2](https://github.com/truenas/charts/assets/80463778/a10582b2-d3b6-44a8-9767-95b1ccbdc9c4)

**Comment by stavros-k** [comment]
Hello, 

1. Do you use a reverse proxy? 
2. Is your instance configured to use certificate?

**Comment by 645340633** [comment]
> Hello,
> 
> 1. Do you use a reverse proxy?
> 2. Is your instance configured to use certificate?

I just use  its own certificate，don't use another reverse proxy。This is what I set


![11111](https://github.com/truenas/charts/assets/80463778/ddfe3b58-b65b-48cb-b200-7a5e0f98fe52)
![2222222](https://github.com/truenas/charts/assets/80463778/c13779c8-efa8-4037-915a-ef2daed1ce35)
