### ISSUE TITLE
Unealthy apps in OFFICIAL Community

### ISSUE THREAD

**Issue by rgge119** [truenas/charts#1495]
WARNING
planka (community train), joplin (community train), firefly-iii (community train) Applications in OFFICIAL Catalog are not healthy.

**Comment by stavros-k** [comment]
I just refreshed and it seems ok.
Can you try refreshing your catalog again?

Thanks

**Comment by rgge119** [comment]
Thanks for the follow up.
I still get the error.

This is what I get when I hover over the info dot:

`questions_configurations.questions.0.schema.attrs.0. schema schema must be specified for variable `

**Comment by stavros-k** [comment]
I'm not sure why this would show up.
But can you please try again? The catalog file was regenerated this morning.

Also, what SCALE version are you running?

**Comment by rgge119** [comment]
On Angelfish.

```
root@truenas[~]# midclt call -job catalog.validate TRUENAS
Status: (none)
Total Progress: [________________________________________] 0.00%
[ENOENT] ALL: Catalog TRUENAS does not exist
root@truenas[~]#
```

**Comment by Qubad786** [comment]
@rgge119 please update your machine to latest stable version first and then share the output of the same command..thanks!
