### ISSUE TITLE
Update request: collabora (outdated app)

### ISSUE THREAD

**Issue by BlauerHunger** [truenas/charts#1509]
The collabora chart is currently served in a 22.05.12.2 version, while the latest version of the image on docker hub is 23.05.3.1.1. The app notifies users that it wants to be updated, but TrueNAS SCALE shows no availabe update. 

Please update this chart.

**Comment by BlauerHunger** [comment]
My TrueNAS SCALE still shows 21.11.4.1.1_1.2.14 as the latest version

**Comment by BlauerHunger** [comment]
The latest image version on docker hub is 23.05.4.1.1

**Comment by stavros-k** [comment]
I've opened another PR that should fix the automated upgrade.
After its merged it should automatically open a request for update in the next 24h
