### ISSUE TITLE
Nextcloud : Creation of dynamic property $lockingProvider is deprecated

### ISSUE THREAD

**Issue by Nusephived** [truenas/charts#1517]
Hi!

Nextcloud logs are flooded with `Creation of dynamic property OCA\Maps\Hooks\FileHooks::$lockingProvider is deprecated at nextcloud/apps/maps/lib/Hooks/FileHooks.php#46`

Maybe linked with PHP version I don't really know.

**Comment by stavros-k** [comment]
See: https://github.com/nextcloud/maps/issues/1023
