### ISSUE TITLE
Nextcloud and Collabora: Possibility to connect Nextcloud and Collabora without truenas certificate.

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#1543]
As far as I know, it is currently only possible to connect Nextcloud and Collabora if the Truenas default certificate is used for Nextcloud and Collabora.

It would be nice if the connection also works without truenas certificate.

**Comment by stavros-k** [comment]
Hello, I don't think we have such a limitation in our side.
But so far I have only seen collabora + nextcloud with a certificate in place.
Either self signed or from lets encrypt or other providers.
