### ISSUE TITLE
immich android app and permissions uploads dataset

### ISSUE THREAD

**Issue by CirKanus** [truenas/charts#1555]
Hi,

With de common permissions; user and group: apps

The android app cannot upload files into uploads dataset; if I allow others to write then de problem is resolved, but from a security point of view...

With permissions do I use to allow the app to write in uploads dataset?

**Comment by stavros-k** [comment]
Hello, you have to check the immich logs to see what's the reason it cannot save to the `uploads` directory.

Currently immich runs as a `root` user, as at the time the app was added the non-root implementation had some issues.

**Comment by stavros-k** [comment]
I'm gonna close this for now, if you find something that should be fixed on our side, please let me know.

Thanks
