### ISSUE TITLE
Nextcloud and Collabora cannot be connected

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#1560]
I just tried the following setup (freshly set up):
Nextcloud (without certificate)
Collabora (without certificate)

In Nextcloud I entered the required information in the Office tab, the Nextcloud recognizes the Collabora instance and shows a green check mark for confirmation but still the documents cannot be opened.

Also the admin button of the Colllabora instance does not work.

**Comment by stavros-k** [comment]
If you do not have a reverse proxy in front or do not use the built in certificate selector, you have to adjust the "extra parameters".
For that you have to consult the Collabora's documentation.

**Comment by stavros-k** [comment]
Yep works fine here.
Both NC and Collabora without cert or reverse proxies.
Disabled ssl.termination and ssl.enable on collabora, and used the `http://IP.of.my.server:9980` (with disabled cert checks in nextcloud admin settings)

**Comment by dajavax** [comment]
This is a bug, whatever you write in "Server Name" gets appended with the port configured (this isn't compatible with using proxies). So if you have a proxy in proxy:9443 the server name passed to Collabora is proxy:9443:9980. The workaround I have found is to pass it in extra parameters instead "--o:server_name=proxy:9443".
