### ISSUE TITLE
[Immich] Postgress database new password not applied after reinstalling the app 

### ISSUE THREAD

**Issue by dani162** [truenas/charts#1606]
Hi, I am currently trying to get the Immich Community App to work for me (true nas scale). In the storage configuration I have mapped a host path to the various storage options.

After the first installation everything worked without problems.
After that I wanted to test if I can just reinstall the app afterwards - remove app - install app (mapped again with all host paths).

1) I actually expected that this should be possible, but after the reinstallation the app does not start anymore, am I right in assuming that this should actually work?

I tried to analyze the problem a bit, it seems that after each installation a random password is automatically generated for the Postgres database (the old password changed to something new) - environment variables DB_PASSWORD (Immich container) and POSTGRES_PASSWORD (Postgress container) are the same for both, but I suspect that the old password is still stored in the database files, which is stored in the host path.

I am not entirely shure, of this is the right place to report this issue, or if its just a user error from my side (is my assumption correct?). So if i am wrong here feel free to just close this issue :)

![image-1](https://github.com/truenas/charts/assets/34603476/2e05751e-8802-4986-a983-4db4c52e017a)
![image](https://github.com/truenas/charts/assets/34603476/82c3b1dd-04cf-4b29-8106-32d2ce79a71b)

**Comment by stavros-k** [comment]
Yes, on every new install a new password is generated. But, no the old password is not saved in the host files, at least I'm not aware if postgres does this automatically, but I suspect it is not, its not secure to do so.

On a running installation you can connect to the database with pgAdmin (exists as an App in the catalog) and take a backup (or restore a backup). On Cobia there will be connection details displayed on the webUI (https://github.com/truenas/charts/pull/1398)
Additionally on every upgrade a backup is automatically created on the path set for the database backups.

Its worth noting that Filesystem DB files does not guarantee a working backup solution. You need to have a gracefully shutdown database in order to backup those files safely.
Postgres recommends pg_dump (which is what is used for the backup creation)

**Comment by dani162** [comment]
> Yes, on every new install a new password is generated. But, no the old password is not saved in the host files, at least I'm not aware if postgres does this automatically, but I suspect it is not, its not secure to do so.

Apparently the password is stored in the file system, but not as plain text, but as a hash value, so the changed environment variable is not picked up after new install.

How I came to this conclusion:
1) copy the password from the environment variable inside the immich postgress container
2) Connected with pgAdmin to the database (worked)
3) reinstalled immich
4) tried to connect with pgAdmin to the database with the new generated password - couldn't connect
5) tried to connect with the old password - could connect

![image](https://github.com/truenas/charts/assets/34603476/58cb7e9f-e715-4017-9f4b-1d340e57a4ad)

**Comment by dani162** [comment]
As a workaround you can open the shell of the Postgress Container and reset the password manually.

1. Open a shell of the Immich Postgress Container over the TrueNAS UI
2. Execute the following Commands
```bash
cd ~/data/
psql immich immich -c "ALTER USER immich PASSWORD '$POSTGRES_PASSWORD';"
```
-> Immich should complete the deploying phase and just start normally.

**Comment by stavros-k** [comment]
> Apparently the password is stored in the file system, but not as plain text, but as a hash value, so the changed environment variable is not picked up after new install.

That sounds possible, postgres would need some way to verify that password, but also does not help, while the chart generates kubernetes manifests, does not have access to the file system anyway, but even if it had, we wouldn't be able to get the original value from the hash.

**Comment by dani162** [comment]
So we somehow need to apply the new password in the deployment or startup phase of the postgres container, right?

**Comment by dani162** [comment]
> That means we will have to override postgres's container, entrypoint command. Which is not very wise.
> What will happen if someone mounts a wrong directory and we reset it's password?

Good Point

> I think this actions is best to be performed manually, what do you think?

I agree

On other Solution would be to let the user chose an password for the postgresql database at installation time. So the user has the option to reinstall the app, if he provide the old password (or set one at the initial install), and the app is not stuck at the deployment phase.

**Comment by stavros-k** [comment]
> Another solution would be to let the user choose a password for the postgresql database during installation. This way the user has the option to reinstall the application if they provide the old password and the application does not get stuck in the deployment phase.

Yes, that would be another solution, but usually restoring a database, is recommended to do that from a dump and not from the raw data.

To restore from raw data is ok only, if the last database instance using that data was gracefully stopped.
But having to reinstall it, most of the time means that something went wrong.

Given that there is a solution already for that scenario (the one you mentioned).
I think we should keep the password situation as is.

A dump is already being created on each upgrade, and you can also create one using pgAdmin app or by connecting to container's shell. pgAdmin can also be used to restore that dump. 

On Cobia which has a new UI for apps, you will be able to see the
database connection details on the UI for easier access.

Note, that database dumps must be performed in frequent intervals. Which is the only format that databases guarantees to be restorable.
