### ISSUE TITLE
Liveness probe failed

### ISSUE THREAD

**Issue by IsmaStifler** [truenas/charts#1698]
Hello, I don't know if it will be an isolated case, but when I update to cobia
TrueNAS-SCALE-23.10.0.1 I moved the pool of apps to an SSD, after a while I started to have problems with nextcloud, I understood that the configuration records perhaps the system could not find the route, so I decided to delete the app and reinstall it, yes it installed the app in the default pvc route everything is correct, if for example I change the storage data to the RAID of the hard drives to have more storage in the initial installation correct, but if you turn off and add another route or simply restart, it starts give error "Liveness probe failed: HTTP probe failed with statuscode: 500" or "403"

It happens to me since I updated the version, and the cloud version of truechart

But in version 22 of nextcloud cloud it enters an infinite boot and never finishes booting, and as I say it is when you customize the storages, before it did not happen, even touching the config.php file to add the domain, same error "Liveness probe failed "

2023-11-02 02:09:08Deleting load balancer
2023-11-02 02:09:08Deleted LoadBalancer DaemonSet kube-system/svclb-nextcloud-90c4db4d
2023-11-02 02:09:08Deleted load balancer
2023-11-02 02:09:08Scaled down replica set nextcloud-cnpg-main-rw-85858f45b5 to 0 from 2
2023-11-02 02:09:08Deleted pod: nextcloud-cnpg-main-rw-85858f45b5-xcx7r
2023-11-02 02:09:08Stopping container pgbouncer
2023-11-02 02:09:08Deleted pod: nextcloud-cnpg-main-rw-85858f45b5-79qfh
2023-11-02 02:09:08Stopping container pgbouncer
2023-11-02 02:09:08Scaled down replica set nextcloud-imaginary-6f89889dfb to 0 from 1
2023-11-02 02:09:08Deleted pod: nextcloud-imaginary-6f89889dfb-4bvzh
2023-11-02 02:09:08Stopping container nextcloud
2023-11-02 02:09:08Scaled down replica set nextcloud-64d7f87b6c to 0 from 1
2023-11-02 02:09:08Deleted pod: nextcloud-64d7f87b6c-xzdb9
2023-11-02 02:09:08Stopping container nextcloud
2023-11-02 02:09:08Scaled down replica set nextcloud-nginx-6c4fcd6bfc to 0 from 1
2023-11-02 02:09:08Stopping container nextcloud
2023-11-02 02:09:08Deleted pod: nextcloud-nginx-6c4fcd6bfc-5vwqm
2023-11-02 02:09:08Scaled down replica set nextcloud-notify-6d695b4c5 to 0 from 1
2023-11-02 02:09:08Deleted pod: nextcloud-notify-6d695b4c5-phsst
2023-11-02 02:09:08Stopping container nextcloud
2023-11-02 02:09:08delete Pod nextcloud-redis-0 in StatefulSet nextcloud-redis successful
2023-11-02 02:09:08Stopping container nextcloud-redis
2023-11-02 02:06:17Job completed
2023-11-02 02:06:17Saw completed job: nextcloud-nextcloud-cron-28314785, status: Complete
2023-11-02 02:05:55Startup probe failed: dial tcp 172.16.0.192:7867: connect: connection refused
2023-11-02 02:05:45Created container nextcloud
2023-11-02 02:05:45Started container nextcloud
2023-11-02 02:05:45Created container nextcloud

It always stays at this point, whether to update or turn it off or on.

I also have problems with access on port 80

I checked it, I thought it was my router sending me to my router configuration page, but when I installed seafile instead and tested, it accessed port 80 correctly, redirecting its port 13080

So nextcloud in my case has a problem with access, port, startup, and app configuration

https://www.truenas.com/community/threads/app-nextcloud-liveness-probe-failed.113873/

**Comment by stavros-k** [comment]
You are not using the TrueNAS Nextcloud app, but the TrueCharts version.
You have to reach out to them for support.

Thanks

**Comment by IsmaStifler** [comment]
![image](https://github.com/truenas/charts/assets/19431908/a933e014-4bc8-44e1-b602-0766378a47e3)
use both versions even if my report is with the chart

**Comment by stavros-k** [comment]
All the provided logs and info are for truecharts. Not the official app.

I've just tried the official app and worked without issues.

I'd need logs and info for the official app in order to be able to check further.

Thanks

**Comment by IsmaStifler** [comment]
there you have the errors of the app


![image](https://github.com/truenas/charts/assets/19431908/5cf03438-0bf1-4d30-99f0-456939f865b3)

**Comment by IsmaStifler** [comment]
![image](https://github.com/truenas/charts/assets/19431908/2000d3fb-55bc-4a5e-adc2-dbed69fd22d0)

**Comment by stavros-k** [comment]
What does the logs of nextcloud show?

On the `Workloads` card select the "Logs" icon and select the nextcloud pod and container.

**Comment by IsmaStifler** [comment]
this?


![image](https://github.com/truenas/charts/assets/19431908/5e58f678-2250-4132-a1cd-76a70fc1cf08)


[nextcloud_nextcloud-postgres-6db6cf6fd6-zfphl_nextcloud-postgres.log](https://github.com/truenas/charts/files/13239858/nextcloud_nextcloud-postgres-6db6cf6fd6-zfphl_nextcloud-postgres.log)

**Comment by stavros-k** [comment]
Looks like by editing the file you changed the permissions of that file which blocks nextcloud of reading it.
You have to check Nextcloud's documentation to see what is the expected permissions on that file/directory.

Alternatively, deploy a new instance and see what are the permissions there and apply to your broken instance.

**Comment by IsmaStifler** [comment]
Basically I assign myself permissions to edit from SMB but in the past I did not have this problem with previous versions of truenas, I just leave everything the same but I assign my user to the data

**Comment by IsmaStifler** [comment]
Before I could also edit the
Nextcloud data directory*

**Comment by stavros-k** [comment]
> Basically I assign myself permissions to edit from SMB but in the past I did not have this problem with previous versions of truenas, I just leave everything the same but I assign my user to the data

There wasn't any change on our end regarding this. Nextcloud was always picky on what permissions it's files has.

Here is the exact check nextcloud's code is doing for the data directory 
https://github.com/nextcloud/server/blob/9e564088da235f72399a257249bf4221f188cde6/lib/private/legacy/OC_Util.php#L744

But I see in your logs that the main issue is that nextcloud requires `/var/www` to be executable and readable.

Note that nextcloud wants the files to be accessible by `www-data (33)`
This log entry comes from apache, which is what nextcloud uses as webserver.

**Comment by IsmaStifler** [comment]
same problem

![image](https://github.com/truenas/charts/assets/19431908/8e63c46c-29a6-4ba5-a5ac-a1d53f829008)
![image](https://github.com/truenas/charts/assets/19431908/4b7eaacf-853b-4a36-b1d3-7f2807f1800f)



and don't touch permissions of /var/www/html/data

**Comment by stavros-k** [comment]
Please re-check Nextcloud logs and see if it now can read/execute the files.

**Comment by IsmaStifler** [comment]
I put the default permissions back removing all


![image](https://github.com/truenas/charts/assets/19431908/556cf32e-2acb-4496-9b33-5a4bb3ae2a4d)

**Comment by IsmaStifler** [comment]
do the test yourself, install an instance with the data in another raid, give yourself permission to modify the config, and try again to relaunch the app

**Comment by stavros-k** [comment]
> I put the default permissions back removing all
> 
> ![image](https://user-images.githubusercontent.com/19431908/280036140-556cf32e-2acb-4496-9b33-5a4bb3ae2a4d.png)

Resetting permission back to root, after nextcloud installation will not work.
As nextcloud only applies the permissions at installation. after that only checks if its accessible.
You have to switch permissions to `www-data (33)` or re-install and let nextcloud do it.

I'd suggest after editing the config file with a different user, to restore the permissions back to `www-data (33)`.

**Comment by IsmaStifler** [comment]
I'm going to create a dataset with permissions already prearranged, and I'll assign it to nextcloud later and see what happens

**Comment by IsmaStifler** [comment]
everything is correct, with pre-assigned permissions, I can assign the data volume and then let nextcloud assign the permissions and it is correct


I just found the solution
