### ISSUE TITLE
Cron in Nextcloud

### ISSUE THREAD

**Issue by IsmaStifler** [truenas/charts#1739]
Hello, I've been dealing with this problem for a long time, I read several articles and I tried it, I configured it every 15 minutes as they say, I tried configuring the cron etc., nothing works correctly for me

What should I do?

https://github.com/truenas/charts/pull/1503
https://github.com/truenas/charts/issues/1306
https://github.com/truenas/charts/issues/1472
https://github.com/truenas/charts/pull/1361

https://www.truenas.com/community/threads/cron-in-nextcloud-scale-cobia-beta-1.112075/

**Comment by stavros-k** [comment]
Can you provide more details?
What does "nothing works correctly" exactly means?

Are there any errors? If so, what are those?
Can you share the configuration you have regarding cron?
Both on SCALE UI and Nextcloud.

Thanks

**Comment by IsmaStifler** [comment]
TrueNAS-SCALE-23.10.0.1

Nombre:
nextcloud
App Version:
27.1.3
Chart Version:
1.6.52
Last Updated:
N/A
Source:
[github.com/nextcloud/docker](https://github.com/nextcloud/docker)[github.com/nextcloud/helm](https://github.com/nextcloud/helm)[github.com/truenas/charts/tree/master/charts/nextcloud](https://github.com/truenas/charts/tree/master/charts/nextcloud)
Developer:
N/A
Catalog:
TrueNAS
Train:
charts

**Comment by IsmaStifler** [comment]
k3s kubectl get -o name -n ix-nextcloud pods | xargs -I{} k3s kubectl exec -n ix-nextcloud --stdin --tty {} -- /usr/local/bin/php cron.php

k3s kubectl exec -n ix-nextcloud -c nextcloud -i `k3s kubectl get -o wide -n ix-nextcloud pods | grep 'nextcloud-[0-9]' | awk '{ print $1; }'` -- su -s /bin/bash www-data -c 'php -d memory_limit=-1 -f /usr/local/bin/php cron.php


Exec www-data


In Scale Cobia UI

If I put or activate cron in the app it doesn't start, I just discovered it now

**Comment by stavros-k** [comment]
I'm not following, I see in the forum post that you enter a command instead of a schedule in the `Schedule` field.
Have you tried entering a valid cron in that field?

I had personally verified that Cron is working, given a valid input.

If that doesn't work, what is the error indicating that it does not? 
How are you verifying that it does not work?

> You do not have to run any `k3s` commands in order for the cron to work.
> Cron runs in a seperate container, spawned by a CronJob managed by kubernetes.

**Comment by IsmaStifler** [comment]
> No te sigo, veo en la publicación del foro que ingresas un comando en lugar de un horario en el `Schedule`campo. ¿Has intentado ingresar un cron válido en ese campo?
> 
> Verifiqué personalmente que Cron está funcionando, dada una entrada válida.
> 
> Si eso no funciona, ¿cuál es el error que indica que no funciona? ¿Cómo estás comprobando que no funciona?
> 
> > No es necesario ejecutar ningún `k3s`comando para que el cron funcione. 
> > Cron se ejecuta en un contenedor separado, generado por un CronJob administrado por Kubernetes.



> I'm not following, I see in the forum post that you enter a command instead of a schedule in the `Schedule` field. Have you tried entering a valid cron in that field?
> 
> I had personally verified that Cron is working, given a valid input.
> 
> If that doesn't work, what is the error indicating that it does not? How are you verifying that it does not work?
> 
> > You do not have to run any `k3s` commands in order for the cron to work.
> > Cron runs in a seperate container, spawned by a CronJob managed by kubernetes.

Basically I changed the storage data to a raid with more capacity and cron does not run, so I tried to do it manually from the thunder UI every 15 minutes by executing those commands and it does not work either

**Comment by stavros-k** [comment]
I'm sorry, but I'll have to ask again for the error you are getting.
Without that I cannot help you, neither I can troubleshoot.

Can you please provide more concrete details?

**Comment by stavros-k** [comment]
Can you share the output of the following command?
```
k3s kubectl get cronjob -n ix-nextcloud
```

**Comment by IsmaStifler** [comment]
> Can you share the output of the following commands?
> 
> ```
> k3s kubectl get cronjob -n ix-nextcloud
> k3s kubectl get pods -n ix-nextcloud
> ```


![image](https://github.com/truenas/charts/assets/19431908/b236e23e-7ddd-41ca-ba80-728c1e91ae72)

**Comment by IsmaStifler** [comment]
![image](https://github.com/truenas/charts/assets/19431908/db59e381-d691-4d4f-8a19-1bdd6752afd0)
![image](https://github.com/truenas/charts/assets/19431908/4ac642db-7d97-4470-83f5-72a8714b988e)

**Comment by stavros-k** [comment]
> ![image](https://user-images.githubusercontent.com/19431908/282848529-b236e23e-7ddd-41ca-ba80-728c1e91ae72.png)

Okay, can you check the logs from the cronjob pods?

```
k3s kubectl logs -n ix-nextcloud nextcloud-cronjob-######-####
```

Replace `#` with the numbers/letters you got from the previous commands
Lets find out what the error is.

**Comment by IsmaStifler** [comment]
> k3s kubectl logs -n ix-nextcloud nextcloud-cronjob-######-####

ook

**Comment by stavros-k** [comment]
Rerun the get pods command, and get fresh pods with their id's

New pods spin every 15min so the previous one are cleaned up

**Comment by IsmaStifler** [comment]
> Vuelva a ejecutar el comando get pods, obtenga pods nuevos con sus identificaciones y utilícelos para obtener registros.
> 
> Las nuevas cápsulas giran cada 15 minutos para que las anteriores se limpien.

ok

**Comment by stavros-k** [comment]
Yea looks like the owner of config.php is `3001`, but it must be `33`

**Comment by IsmaStifler** [comment]
> Yea looks like the owner of config.php is `3001`, but it must be `33`

![image](https://github.com/truenas/charts/assets/19431908/5319a4a5-dbbf-4ab3-be99-fd34d0ce2427)
![image](https://github.com/truenas/charts/assets/19431908/94bc9c4d-d7e1-4e1e-b0e2-0f61f275be06)

**Comment by IsmaStifler** [comment]
@stavros-k 

Now I can't access the apps when the owner changes xD

![image](https://github.com/truenas/charts/assets/19431908/bfa6a75b-3c38-4530-ae97-3b0efd9b42b1)


https://help.nextcloud.com/t/cant-access-apps-and-settings-system/139403/3

**Comment by stavros-k** [comment]
Hello, in your Nextcloud_data directory there should be a nextcloud.log file, you can check there what the issue might be.

**Comment by IsmaStifler** [comment]
![image](https://github.com/truenas/charts/assets/19431908/0a858c49-b991-4c87-be10-ad1f84bdeaf9)
![image](https://github.com/truenas/charts/assets/19431908/75f7e175-d458-4cbe-932c-ca7edcad1c41)


> Hello, in your Nextcloud_data directory there should be a nextcloud.log file, you can check there what the issue might be.

**Comment by stavros-k** [comment]
I don't see anything helpful in the logs you shared. I suggest reaching to Nextcloud support channels.
Or if it is a specific Nextcloud App that has a problem, reach to the app's support channels

**Comment by IsmaStifler** [comment]
> I don't see anything helpful in the logs you shared. I suggest reaching to Nextcloud support channels. Or if it is a specific Nextcloud App that has a problem, reach to the app's support channels

Basically when assigning www-data permissions to the folder it lost the root permissions so access to the "apps" gives an error and all their functions

**Comment by stavros-k** [comment]
> > I don't see anything helpful in the logs you shared. I suggest reaching to Nextcloud support channels. Or if it is a specific Nextcloud App that has a problem, reach to the app's support channels
> 
> Basically when assigning www-data permissions to the folder it lost the root permissions so access to the "apps" gives an error and all their functions

I wish I could help you from the Chart side. Truth is that Nextcloud is very picky on what permissions each directory needs.
But without logs that show what directory needs what, your only help is dedicated nextcloud channels.

If you find any issues on the Chart that I can fix/help please let me know!

Thanks
