### ISSUE TITLE
Immich needs to be updated - currently broken for smartphone users

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/charts#1755]
The TrueNAS/charts version of Immich is 1.85.0, but the smartphone app on google play was updated to 1.86.0 yesterday, and now logins from smartphones are broken until the TrueNAS/charts version is updated to 1.86.

https://github.com/immich-app/immich/releases mentions the app breaking issue.

**Comment by Chaphasilor** [comment]
Actually, Immich has already been update here in the repo in #1751, but this time the change isn't being reflected in the Helm chart in TrueNAS. Maybe it's related to the recent release of Cobia?

Also, while we're at it, there is a major breaking change coming up in Immich v1.88 that removes two container and uses a different port config. I'm guessing this will require a migration of some kind and changes to the install form.  
More info in this discussion: https://github.com/immich-app/immich/discussions/5086

**Comment by stavros-k** [comment]
> Actually, Immich has already been update here in the repo in #1751, but this time the change isn't being reflected in the Helm chart in TrueNAS. Maybe it's related to the recent release of Cobia?

I've actually undone the update there, because a migration was needed first (see linked PR)

> Also, while we're at it, there is a major breaking change coming up in Immich v1.88 that removes two container and uses a different port config. I'm guessing this will require a migration of some kind and changes to the install form. More info in this discussion: [immich-app/immich#5086](https://github.com/immich-app/immich/discussions/5086)

I'm aware, will handle that right after the mentioned PR is merged

**Comment by Chaphasilor** [comment]
Awesome, tysm! <3  
It's amazing how responsive you are to these issues 😁

**Comment by TimvanDijkNL** [comment]
Jikes! 

Looks like 1.88 is going to be a good and bad update. It should reduce resource consumption a bit, but the migration part makes me a bit nervous.

**Comment by yewkay** [comment]
> Jikes!
> 
> Looks like v1.88 is going to be a good and bad update. It should reduce resource consumption a bit, but the migration part makes me a bit nervous.
> 
> Meantime i did find a workaround for the initial problem.. You can delete the Immich app downloaded via Google Play store and download the v1.85 version [here](https://apkpure.com/immich/app.alextran.immich/versions).

By deleting the app, will the phone retain all my previous info like the files synced?

**Comment by Chaphasilor** [comment]
@yewkay it will reset your settings and scan your whole local storage again, possibly trying to upload files to see if they're duplicates / already uploaded. But nothing deal-breaking.

**Comment by TimvanDijkNL** [comment]
Correct. You need to log in again, select the folders you wish to sync, turn on foreground/background and then hit the sync button.. in my case it uploaded a few new photo's that were made in the meantime and that was it... nothing special, back to the way it was.

**Comment by bdubs85** [comment]
Just to add additional context, this is also (of course) broken on iOS with no good way to be able to roll back the app version like on Android.
