### ISSUE TITLE
Tailscale should be updated to version 1.54

### ISSUE THREAD

**Issue by Cristiano1972** [truenas/charts#1756]
Hi,

The community app for Scale should be updated to last version. I've two linux clients connecting to Tailscale that are having some performance issues, in the new version they're announced some improvements to performance that may solve this problem.

[Substantially improve throughput](https://tailscale.com/kb/1320/performance-best-practices/#ethtool-configuration) for UDP packets over TUN device with recent Linux kernels

Thanks.

**Comment by stavros-k** [comment]
Closing this as its not an issue on our side to track!
Our automation monitors upstream releases and once its out, will get us notified!
Thanks!
