### ISSUE TITLE
Sonarr Not Installing 

### ISSUE THREAD

**Issue by jdogcoder** [truenas/charts#1764]
![image](https://github.com/truenas/charts/assets/65788728/7ba6af8b-d293-441e-89d3-c8c889802e53)

Failed to pull image "ghcr.io/onedr0p/sonarr:3.0.10.1567": rpc error: code = Unknown desc = context deadline exceeded

**Comment by stavros-k** [comment]
Hello, 
The above error indicates that the download does not complete in a timely manner. 

> I just checked and I can pull the image without issue.

Please make sure that you have access to github from your server.
Thanks

**Comment by jdogcoder** [comment]
I do, as other things pull just fine. I think it is due to the fact that the image is not one of the 2 recommended by sonar.

They recommend[ghcr.io/hotio/sonarr:release](https://ghcr.io/hotio/sonarr:latest) or [ghcr.io/linuxserver/sonarr:latest](https://ghcr.io/linuxserver/sonarr:latest) (see https://sonarr.tv/#downloads-v3-docker)

**Comment by stavros-k** [comment]
> I do, as other things pull just fine. I think it is due to the fact that the image is not one of the 2 recommended by sonar.
> 
> They recommend[ghcr.io/hotio/sonarr:release](https://ghcr.io/hotio/sonarr:latest) or [ghcr.io/linuxserver/sonarr:latest](https://ghcr.io/linuxserver/sonarr:latest) (see https://sonarr.tv/#downloads-v3-docker)

This has nothing to do with the failure to pull the image.

Plus the recommended images can only run as `root` user. The one we use run as an unprivileged user.
You can try from your host's shell to run

```
docker pull ghcr.io/onedr0p/sonarr:3.0.10.1567
```

**Comment by jdogcoder** [comment]
![CleanShot 2023-11-20 at 11 03 07@2x](https://github.com/truenas/charts/assets/65788728/0fa130ce-15f4-47f6-953c-09533037c8d8)

**Comment by stavros-k** [comment]
Okay after that's done, app should start automatically.

Probably your connection is not fast enough to download the image within 2min which exists in TrueNAS Bluefin.
The timeout of 2min should not be present in TrueNAS Cobia.

**Comment by jdogcoder** [comment]
It downloaded.....

**Comment by jdogcoder** [comment]
I will check...

What is Bluefin vs Cobia?

**Comment by jdogcoder** [comment]
Working now!

**Comment by stavros-k** [comment]
> What is Bluefin vs Cobia?

The TrueNAS SCALE Release names.
Based on the screenshot I see that you are running Bluefin now.
You can see that in System Settings -> General -> OS Version



> Working now!

Thanks for confirming



> Thanks for your help.

You welcome!

**Comment by jdogcoder** [comment]
![CleanShot 2023-11-20 at 11 11 52@2x](https://github.com/truenas/charts/assets/65788728/3482c76e-983c-4341-856a-8c01137cba35)

**Comment by jdogcoder** [comment]
No name 🤷🏻

**Comment by jdogcoder** [comment]
Ah got it! Thanks!
