### ISSUE TITLE
Immich: immutable "Additional Storage" fields

### ISSUE THREAD

**Issue by ben-basten** [truenas/charts#1774]
**Description:**

The current app setup configuration for Immich does not allow for mounting additional Host Path volumes under the "Additional Storage" section after the initial install.  I think that this is core functionality for Immich, and adding additional  volume mounts should be allowed at any time.

Mounting extra volumes is needed for the "[External Libraries](https://immich.app/docs/features/libraries#external-libraries)" feature, where Immich can index arbitrary paths in the file system for a user's photo library. After the initial deployment, attempting to add additional volumes only allows adding "ixVolume" datasets with a disabled dropdown selector, which isn't helpful since those datasets don't contain any media content.

Is it possible that [the immutable flag](https://github.com/truenas/charts/blob/master/community/immich/1.1.0/questions.yaml#L669) on the storage configuration is causing this behavior?

**Screenshot:**

<details>
  <summary>Click to view screenshot</summary>
  
![immich-additional-storage](https://github.com/truenas/charts/assets/45583362/30903f4f-9959-4609-a97a-aeca2e977412)

</details>

Notice the second item under "Additional Storage" was added after initial installation. The item's Type is set to "ixVolume" by default, but the dropdown is disabled and there's no way to change it.

**Comment by stavros-k** [comment]
It is fixed on the next SCALE release. Its a UI bug 
https://github.com/truenas/webui/pull/9174

**Comment by ben-basten** [comment]
Ok, thanks for the help @stavros-k! I appreciate the reference to the pull request for more context.
