### ISSUE TITLE
Portforward to the nginx-proxy-manager NodePort 

### ISSUE THREAD

**Issue by t-abraham** [truenas/charts#1779]
I am sorry to bring this stupid question. I am still learning TrueNAS. As mentioned by @stavros-k "I can't think of any reason to use hostnetwork here. A portforward to the NodePort Service should be enough" in this post [1117](https://github.com/truenas/charts/pull/1117) can anyone please tell me how to do that? I wish to use nginx-proxy-manager to proxy local domains to different services which are running in the apps of TrueNAS...

to my understanding, It is required for nginx-proxy-manager to be listening to port 80, 443, for the http, https services and other ports which are below 9000 (if i have streams setup in the nginx-proxy-manager)

**Comment by stavros-k** [comment]
You have to handle that on your router level. 
We cannot allow ports 80 and 443 as it could easily block you out of the TrueNAS WebUI and many ports < 9000 can possibly break other services..

**Comment by t-abraham** [comment]
well handling local port forwarding in the router level (mikrotik) is not possible. Since both the in/out interfaces are local and the NAT require a separated interface or at-least a different subnet.

In this event, is there any way to force nginx-proxy-manager on port 80,443 while i shift TrueNAS WebUI to 81,444?

**Comment by stavros-k** [comment]
> In this event, is there any way to force nginx-proxy-manager on port 80,443 while i shift TrueNAS WebUI to 81,444?

No, the minimum NodePort is `9000` https://github.com/truenas/middleware/blob/0ac986deef7736c1825fdf40683fdc0214132208/src/middlewared/middlewared/etc_files/rancher/k3s/flags.py#L26C1-L26C1

Otherwise you have to manually deploy it at your own risk using custom app button, and enable host network.

**Comment by t-abraham** [comment]
> > In this event, is there any way to force nginx-proxy-manager on port 80,443 while i shift TrueNAS WebUI to 81,444?
> 
> No, the minimum NodePort is `9000`
> 
> https://github.com/truenas/middleware/blob/0ac986deef7736c1825fdf40683fdc0214132208/src/middlewared/middlewared/etc_files/rancher/k3s/flags.py#L26C1-L26C1
> 
> Otherwise you have to manually deploy it at your own risk using custom app button, and enable host network.

This brings up the topic that in the latest verion of TrueNAS Scale `TrueNAS-SCALE-23.10.0.1` in the custom app deployment there is no option to enable host network and also in the custom app deployment the port limit of `9000` is applied (probably because enable host network is not there)

**Comment by t-abraham** [comment]
> Host network is still there
> 
> https://github.com/truenas/charts/blob/f6c0d2d1d9eff51fb8b5d33f8409d57180d95aa2/library/ix-dev/charts/ix-chart/questions.yaml#L373-L379
> 
> Maybe some kind of UI bug, needs investigation.
> 
> yes without hostnet the limit is 9000. With hostnet, you dont need to specify port forward, as it will bind directly to the host. (at your own risk)

![host_network](https://github.com/truenas/charts/assets/17075361/8a0c6dcd-e648-49f4-8ffa-42b81a62ba43)

yes may a UI bug. I just checked the custom app deployment options and there is none. Refer to the image

**Comment by t-abraham** [comment]
> Host network is still there
> 
> https://github.com/truenas/charts/blob/f6c0d2d1d9eff51fb8b5d33f8409d57180d95aa2/library/ix-dev/charts/ix-chart/questions.yaml#L373-L379
> 
> Maybe some kind of UI bug, needs investigation.
> 
> yes without hostnet the limit is 9000. With hostnet, you dont need to specify port forward, as it will bind directly to the host. (at your own risk)

i see the label has been changed `"Provide access to node network namespace for the workload"`. okey i will give it a try and get back

**Comment by stavros-k** [comment]
Advanced users can use Custom App!
But I can't have a toggle that can easily (even by misclick) block you out of the management interface of your server.

**Comment by t-abraham** [comment]
> Advanced users can use Custom App! But I can't have a toggle that can easily (even by misclick) block you out of the management interface of your server.

well you got a point... well then this solves the issues and doubts. Thanks again.
