### ISSUE TITLE
JellyFin app does not allow you add extra storage 

### ISSUE THREAD

**Issue by Saberwolf64** [truenas/charts#1799]
The current version of jellyfin does not allow you added extra storage also i can not change the data sets that are predefined in web ui 

![image](https://github.com/truenas/charts/assets/20310931/bd5b7559-3f71-4a60-9844-ac0c8d92a65d)

They are grayed out and no changes are available to be made

**Comment by stavros-k** [comment]
Hello the predefined storages are disabled after install.
But for additional storage there is a bug in the webui that is already fixed and will be available in the next SCALE release
https://github.com/truenas/webui/pull/9174

Thanks
