### ISSUE TITLE
Searxng add more additional variables

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#1808]
I have listed the most important variables here:
`contact_url`
`enable_metrics`
`privacypolicy_url`
`donation_url`
`default_lang`
`default_locale`
`infinite_scroll`
`center_alignment`
`autocomplete`
`safe_search`

**Comment by stavros-k** [comment]
As mentioned in the upstream [issue](https://github.com/searxng/searxng-docker/issues/8#issuecomment-1046272220) there is no support for additional variables.
There are few [here](https://docs.searxng.org/admin/installation-docker.html#command-line) and thats all!

Unless I'm missing something of course..
Please let me know if that's the case.
