### ISSUE TITLE
WebDAV server rejects requests from the home network but not outside the network

### ISSUE THREAD

**Issue by vtosevski** [truenas/charts#1817]
Dear Charts team,

I am using WebDAV app to sync files from my [Zotero](zotero.org) reference manager. For years this has worked well on TrueNAS CORE. After upgrading to TrueNAS SCALE (TrueNAS-SCALE-23.10.0.1) I am seeing issues in that sync requests get rejected. The Zotero client returns the error message:

> Your WebDAV server returned an HTTP 0 error for a GET request.

The WebDAV App (App Version: 2.4.58, Chart Version:1.0.14 ) is properly set up per online instructions and works fine when I try to access the share via browser. It is set up via HTTPS and certificate is correct and functions fine. Authorisation also works fine.

My Zotero client syncs without issues when I am outside my home but throws the above error when I try to sync from within the home network. Assessing the WebDAV share through a web browser via external address works fine from within the network.

The App log has the following information.

> [ssl:warn] [pid 1:tid 139803170060160] AH01909: localhost:30035:0 server certificate does NOT include an ID which matches the server name
[ssl:warn] [pid 1:tid 139803170060160] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[ssl:warn] [pid 1:tid 139803170060160] AH01909: localhost:30035:0 server certificate does NOT include an ID which matches the server name
[mpm_event:notice] [pid 1:tid 139803170060160] AH00489: Apache/2.4.58 (Unix) OpenSSL/3.0.11 configured -- resuming normal operations
[core:notice] [pid 1:tid 139803170060160] AH00094: Command line: 'httpd -D FOREGROUND'
[dav:error] [pid 9:tid 139801814607552] (70007)The timeout specified has expired: [client 192.168.1.1:58993] An error occurred while reading the request body (URI: /zotero/625Q9WVI.zip)  [408, #0]
[dav:error] [pid 8:tid 139802921920192] (70007)The timeout specified has expired: [client 192.168.1.1:58994] An error occurred while reading the request body (URI: /zotero/SBWXT6QV.zip)  [408, #0]
[dav:error] [pid 9:tid 139803154171584] (70007)The timeout specified has expired: [client 192.168.1.1:59072] An error occurred while reading the request body (URI: /zotero/SBWXT6QV.zip)  [408, #0]

I recognize above the references to the localhost but the Zotero client is configured with the external address that matches the certificate.

What can I do here? What causes this type of issue?

Thanks!

**Comment by stavros-k** [comment]
When you are inside your network, what does `nslookup dav.domain.tld` returns? (replace dav.domain.tld with your sub/domain).

If it reports your public IP, then your DNS is not resolving the local IP for webdav, but your external one.
And in this case all the traffic goes out the WAN and back into your LAN, limiting your self to your WAN speeds.

**Comment by stavros-k** [comment]
The certificate is not bound to the IP, but on the domain/subdomain.
If you edit your `hosts` (`/etc/hosts` in linux) file in your client machine like this:

> NAS IP     ->   webdav host
```
192.168.1.x     sub.domain.tld
```

it should send traffic directly to your webdav and still have a valid cert.

**Comment by vtosevski** [comment]
I am on Windows and editing the hosts file per your suggestion did not have a desired effect. After edit, the Zotero cannot establish the connection to the WebDAV server at all.

**Comment by stavros-k** [comment]
Is your TrueNAS IP the same the WebDAV listens to, or do you have your apps in a different interface?

Also if your router also does any port translation eg 443 -> 30035 (default https port for webdav app), now that you are bypassing your router, you have to manually append the port. eg dav.domain.tld:30035

**Comment by vtosevski** [comment]
thanks @stavros-k, appending the ports manually worked. The Zotero now syncs. I am not sure why the additional work and adjusting hosts file was needed, but I can leave it as it, as long as it works.
Thanks for your fast response and assistance!
Have a good weekend ahead!
