### ISSUE TITLE
Problems upgrading from Paperless-ngx `1.17.4_1.1.3` to `2.0.1_1.2.3`

### ISSUE THREAD

**Issue by peteryates** [truenas/charts#1826]
I'm quite new to TrueNAS and all the apps I've used have been rock solid so far, but Paperless-ngx is giving me a few problems when updating from `1.17.4_1.1.3` to `2.0.1_1.2.3`. It gets stuck in the deploying state.

![image](https://github.com/truenas/charts/assets/128088/9f357fd6-dbf0-4244-af7b-f37638766b05)

When looking at the logs for the app, they just contain this:

```
2023-12-02 09:38:44.906304+00:00Paperless-ngx docker container starting...
2023-12-02 09:38:44.910402+00:00Mapping UID and GID for paperless:paperless to 568:568
```

The history pane shows this message (I tried with/without host network checked to see if that made a difference, but it doesn't):

```
2023-12-02 08:02:22
Startup probe failed: Get "http://192.168.1.253:9088/": dial tcp 192.168.1.253:9088: connect: connection refused
```

Both PostgreSQL and Redis start fine and are ready to accept connections, and connecting to the database with pgAdmin confirms everything looks fine.

My config looks pretty sensible too, I suspect nothing out of the ordinary:

| Admin, user group | Network | Storage | Resources |
| ----- | ----- | ----- | ----- |
| ![Screenshot from 2023-12-02 09-43-29-obfuscated](https://github.com/truenas/charts/assets/128088/8d00aeed-b4fb-4d85-90f1-bcc63a122906) | ![Screenshot from 2023-12-02 09-44-31](https://github.com/truenas/charts/assets/128088/4163d90c-8907-4990-a0da-5a25da0c6d9e) |![Screenshot from 2023-12-02 09-44-42](https://github.com/truenas/charts/assets/128088/4ef46374-c371-4d05-9c00-b6a49f61d307) | ![Screenshot from 2023-12-02 09-44-51](https://github.com/truenas/charts/assets/128088/9c7c0c6e-9201-413f-b8c7-895bc3862892) |

I have been able to roll back and it's working again, but I thought I'd inform you anyway.

**Comment by peteryates** [comment]
Having dug a little deeper it seems that whenever Paperless-ngx is running `iowait` jumps right up. The minute I stop the app it comes back down to normal:

![image](https://github.com/truenas/charts/assets/128088/3267cea6-07fc-4c32-b267-ebdf448ae86c)

If I had a colossal library of documents I guess it'd make sense, but I have about 30. I'm on a  Intel(R) Xeon(R) E-2324G CPU @ 3.10GHz with 32GB EEC RAM and 4 Toshiba 12TB drives (which are fine, and not _that_ slow!).  Can't make sense of what's going on.

**Comment by stavros-k** [comment]
Looks like container is stuck in this line 
https://github.com/paperless-ngx/paperless-ngx/blob/e4acc3351957492889bfad01a8938237817f1638/docker/docker-entrypoint.sh#L13-L14

Which can take time on HDDs. Taking too much time leads kubernetes to kill the container and recreate it.
Its not that it processes your documents, but the container's internal files.
I'm not a fan either of that. 

As a workaround you can use built-in user and group of `1000` which will make paperless skip the whole process
https://github.com/paperless-ngx/paperless-ngx/blob/e4acc3351957492889bfad01a8938237817f1638/Dockerfile#L248

Sadly this is something coming from upstream that we cannot skip.

**Comment by jeremehancock** [comment]
I haven't been able to get passed this on my setup. So I just created an Ubuntu Server VM in Truenas Scale and installed Paperless-ngx on it using Docker. It is working flawlessly. I plan to move any apps that I have issues with into this VM and will probably not consider any more apps in Scale directly for now. Just figured I would post this in case it could help someone.

**Comment by peteryates** [comment]
Following @stavros-k's instructions I did the following to get it working:

1. ### Add user `paperless` with UID of `1000`
    ![image](https://github.com/truenas/charts/assets/128088/435bff79-4b7f-4512-8a18-0495162ce08b)
2. ### Change the ownership of my Datasets to the new `paperless` user ensuring both it and my `brotherscanner` user can see the 'Consumption Storage' directory
3. ### Change the "User and Group Configuration" settings so they run with the new `paperless` user
   ![image](https://github.com/truenas/charts/assets/128088/bd46322e-5434-4e52-9d72-ddf8fc564b49)
4. ### Now restarting the app should work

**Comment by r2p2** [comment]
Sorry for commenting a closed ticket. In case it is preferred, I can also open a new one. It seems (but not 100 % sure) that I am running into the same issue. Switched from Core to Scale last week and tried to install a fresh paperless ngx app with access to my datasets. That did not work so I tried 500 times to install a paperless ngx instance with all defaults (using the system created volumes). I was unable to find any hint on why my installation get stuck on deploying. After using 1000:1000 as uid/gid while keeping the rest to default, seemed to work.

UID and GID 1000 are already in use on my system and I am not keen on switching everything around. I would like to have a proper setup for keeping all my important documents managed by this app and I am worried, that if I start fiddeling things here and there, that I get into trouble later on in case a new update will take issue with my workarounds.
