### ISSUE TITLE
Request - Provide option to avoid running chown on host paths

### ISSUE THREAD

**Issue by elfalem** [truenas/charts#1829]
Several of the apps in the chart (e.g. Transmission, Jellyfin) will run `chown` to recursively change the owner and group on mounted directories. This is noted in the README file (e.g. from Transmission):

>When application is installed, a container will be launched with root privileges. This is required in order to apply the correct permissions to the Transmission directories. Afterward, the Transmission container will run as a non-root user (Default: 568).

While this could be useful for ensuring the app has the correct permissions to access the directories, it can create issues for others accessing the same directories with different users and groups. Please provide an option (perhaps a checkbox in the app installation screen) to bypass this behavior with the expectation that the system administrator will configure the correct permissions separately.

**Comment by stavros-k** [comment]
Its already being worked on
eg: https://github.com/truenas/charts/pull/1811

**Comment by elfalem** [comment]
Awesome! Thanks for your prompt reply and work on this and many other issues @stavros-k. It's greatly appreciated!

**Comment by stavros-k** [comment]
Considering more than a few apps now has this option, I'm going to close this.
Rest assured all the apps will get those options soon!

Thanks!
