### ISSUE TITLE
Mealie 1.0.0-RC1 chart bug.

### ISSUE THREAD

**Issue by duckhead** [truenas/charts#1845]
There is a small bug in the mealie version 1.0.0-RC1 chart. At installation, there are several directories created as ix_volumes:

/mnt/tank/ix-applications/releases/mealie/volumes/ix_volumes

These are:

```
drwxr-xr-x  7 root root    9 Dec  7 11:39 data
drwxr-xr-x  2 root root    2 Dec  6 21:16 pgBackup
drwx------ 19  999 docker 26 Dec  6 21:17 pgData

```

As part of the pod initialization, it expects to be able to write to the data/ subdirectory, and the permissions don't allow it. The fix is to change the ownership on the directory to apps:apps.

I'm not 100% sure about the other 2, pgData appears to work. I suspect nothing has used pgBackup yet. I don't see a way to exercise that. But, I'll bet that if I did, it would fail like data failed. The fix is to make that 999:docker.

I'm on BlueFin, and I understand it doesn't know about uid 999 yet, so don't be worried about that.

There is a mealie-install-permissions pod in mealie-postgress, but it doesn't touch these directories:

```
023-12-07 03:17:09.681597+00:00 Current Ownership and Permissions on [/mnt/directories/postgres_data]:
2023-12-07 03:17:09.686646+00:00 chown: 0 0
2023-12-07 03:17:09.687787+00:00 chmod: 755
2023-12-07 03:17:09.687930+00:00 Changing ownership to 999:999 on: [/mnt/directories/postgres_data]
2023-12-07 03:17:09.689308+00:00 Finished changing ownership
2023-12-07 03:17:09.689374+00:00 Ownership after changes:
2023-12-07 03:17:09.689949+00:00 999 999
```

**Comment by duckhead** [comment]
Also, while you are there, version 1.0.0-RC2 has been released and a bump would be nice.

**Comment by stavros-k** [comment]
I'll close this now, as the options for easier installation (eg permissions) will be a more global change and not limited to Mealie. 

If you still having issues after changing the permissions manually, please reply here.
