### ISSUE TITLE
Immich Upcoming Breaking Change

### ISSUE THREAD

**Issue by Chaphasilor** [truenas/charts#1848]
Just FYI, Immich v1.91 will have another breaking change that removes one container completely and changes the base image of another one.

The change is described in the v1.90 release notes here:  
https://github.com/immich-app/immich/releases/tag/v1.90.0

**Comment by jbgosselin** [comment]
The new release just dropped with the breaking change https://github.com/immich-app/immich/releases/tag/v1.91.0
