### ISSUE TITLE
Nextcloud: missing PHP modules

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#1868]
This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them: bz2.

**Comment by frederickjansen** [comment]
My sense is that Nextcloud should fix this is their Docker image if it's now a recommended module. There's an issue for that [here](https://github.com/nextcloud/docker/issues/2118).

**Comment by stavros-k** [comment]
Hey, I'm gonna reference this https://github.com/truenas/charts/issues/2123, just to keep track of it.
But I'll close it, as it's the same "issue" as the referenced one.

Subscribe to the linked one for updates

Thanks!

**Comment by frederickjansen** [comment]
Nextcloud at least is "fixing" this one in [v28.0.3](https://github.com/nextcloud/server/pull/43013).
