### ISSUE TITLE
Jellyfin - high cpu load streaming from a movie. is the igpu used?

### ISSUE THREAD

**Issue by netzwanze** [truenas/charts#1904]
High cpu load streaming from a movie. Is the igpu used?

Intel(R) Celeron(R) J4125 
TrueNAS-SCALE-22.12.4.2
jellyfin 10.8.13_1.2.2
Allocate 0 gpu.intel.com/i915 GPU

3389891 apps      20   0  418880  84752  12580 S **251.3**   0.3   1:01.90 ffmpeg

**Comment by stavros-k** [comment]
You have to Allocate `1` in order to use it.
Allocate `0` is equal to saying "Allow zero gpus to be used"

> Note that if you want other apps to also use the iGPU, you set `Allocate 1 GPU` to others too.
Just keep in mind that is up to 5 apps

**Comment by netzwanze** [comment]
So i have tested it. No other application has been assigned a gpu. The same problem

Allocate 1 gpu.intel.com/i915 GPU

1 stream mpg2 SD

1044795 apps      20   0  416236  69972   4728 S 207.9   0.2   1:25.99 ffmpeg

The  intel-gpu-tools (intel_gpu_top) would be good to see if the gpu is being used

Btw.

I have found a other problem.

I can not change the igpu if the app installed. I have to be first desinstall.  
My additional storage mount path in the container is no longer displayed in the install menu. I also have no selection option .I was able to reproduce the problem

`Error: [EINVAL] values.jellyfinStorage.additionalStorages: Item#0 is not valid per list types: [EINVAL] storageEntry.hostPathConfig.hostPath: attribute required `

**Comment by stavros-k** [comment]
> `Error: [EINVAL] values.jellyfinStorage.additionalStorages: Item#0 is not valid per list types: [EINVAL] storageEntry.hostPathConfig.hostPath: attribute required `

Can you please upgrade to Cobia and see if both issues persist?

Thanks

**Comment by netzwanze** [comment]
Hey Stavros-k,

i'm sorry but it's my productive system. I can test and send logs - but no upgrade. Only the problem with the igpu are all so in TRUECHARTS repro.

**Comment by netzwanze** [comment]
It's also a bit strange that i can't include nfs export as additional storage in the container. i use the nfs export to store the movies there.

**Comment by stavros-k** [comment]
> Hey Stavros-k,
> 
> i'm sorry but it's my productive system. I can test and send logs - but no upgrade. Only the problem with the igpu are all so in TRUECHARTS repro.

The additional storages error, should be fixed in Cobia. As for iGPU, if this happening on both catalogs, I'm not sure that this would be something coming from the Apps.
Maybe jellyfin does not support your igpu?
But it would be best to try on Cobia, 23.10.1 also released today

**Comment by netzwanze** [comment]
Good morning Stavros-k,

how can i get root access to the containers?  Where can i find the yaml for my jellyfin and can i edit it to start the container with my manual changes? I want to try something. wouldn't it be stupid not to use existing resources like hardware acceleration? 

I found this

https://github.com/jellyfin/jellyfin/issues/9229


Localy on my Truenas i have reactivate apt an installed the intel-gpu-tools and the intel-media-va-driver-non-free.
Locally the hardware acceleration works with ffmpeg. Now only the container has to be customized.


Thanks for your help

**Comment by stavros-k** [comment]
Hello, 

> how can i get root access to the containers?

You can't if the container already runs as **non** root. 
Containers are not meant to install packages at run time, we use the jellyfin's upstream container, 
so they have to add the missing packages (if any) on their image.

Or is it something else you need to to do?

Note that selecting a GPU should also add the supplementaryGroups `44` and `107` to the container..

**Comment by netzwanze** [comment]
How and where can I do that?

**Comment by stavros-k** [comment]
> How and where can I do that?

If you are referring to this

> selecting a GPU

It's at the end of the configuration page on TrueNAS UI, allocate `1` gpu.intel.com

![image](https://github.com/truenas/charts/assets/47820033/f64e6274-ff5c-485e-ac14-5e7b02f55309)

**Comment by netzwanze** [comment]
Unfortunately it does not work

![Bildschirmfoto vom 2024-01-04 17-40-13](https://github.com/truenas/charts/assets/62278695/257a7e75-989e-4b3e-ac21-3b382609789c)

![Bildschirmfoto vom 2024-01-04 17-43-26](https://github.com/truenas/charts/assets/62278695/e08fc120-13e8-4b4e-a450-35e8a861e737)

**Comment by netzwanze** [comment]
Sorry, it was my problem...

![Bildschirmfoto vom 2024-01-05 17-27-42](https://github.com/truenas/charts/assets/62278695/e5b5e6e7-4b4a-401e-8f9a-b64dcafa4895)

**Comment by stavros-k** [comment]
Glad you figured it out! Thanks for letting me know!
