### ISSUE TITLE
Gitea: 2FA not working

### ISSUE THREAD

**Issue by BlauerHunger** [truenas/charts#1908]
I'm running the gitea app version 1.21.2_1.1.4 and I'm not able to enable 2FA because it doesn't accept the passcodes generated from the shown qr code.

**Comment by stavros-k** [comment]
Can you provide more information?
Logs? Specific error? Have you tried Gitea's support channels?

Thanks

**Comment by BlauerHunger** [comment]
Just tried it again and it suddenly worked. Gitea never produced logs for this, and it happened until the first container restart (edit app -> save) since the last installed chart update. I assume it was due to having the wrong time inside the container because when it the error first appeared (leaving me the scratch code as the only way to login) the `date` command inside the container showed me the local time as UTC (e.g. 12:10 CET on the host showed as 12:10 UTC inside the container). I don't know why this happened and I don't know why this stopped happening now.
