### ISSUE TITLE
Transmission - RPC auth settings are overwritten

### ISSUE THREAD

**Issue by elfalem** [truenas/charts#1976]
I'm able to run the transmission app. However, I would like to add authentication to the web UI. According to documentation, this is done by changing the settings.json file in the app configuration.

Steps:
1. ensure app is stopped
2. edit settings.json as follows:
```
rpc-authentication-required: true,
rpc-password: "mypassword",
rpc-username; "myusername",
```
(The password value will be automatically hashed when the daemon next starts)
3. save changes and restart the app
Expected: navigating to the web UI of transmission will ask for username and password
Actual: no authentication is configured and settings.json file is reverted to the following:

```
rpc-authentication-required: false,
rpc-password: "{hashvalue",
rpc-username; "",
```

**Comment by stavros-k** [comment]
You should use the variables from the upstream container listed in our Readme https://github.com/truenas/charts/blob/master/library/ix-dev/community/transmission/README.md

Direct link for the envs available: 
https://github.com/onedr0p/containers/tree/main/apps/transmission

**Comment by elfalem** [comment]
I missed that part of the documentation. It's working with environment variables. Thank you!
