### ISSUE TITLE
please fixed truenas 

### ISSUE THREAD

**Issue by ford220102** [truenas/charts#1978]
I wish you could correct it and where can I report it to the main truth? You also have this problem because it looks like it's related to the SQL database and also it's OK under Ubuntu server

https://truecharts.org/docs/charts/stable/nextcloud/installation/

**Comment by stavros-k** [comment]
Hello, it seems you are using a TrueCharts App.
You have to reach to their support channels.

If you use one of the Official catalog apps, and you are having issues, feel free to create a new issue, and provide details what you tried and didn't work.

Thanks!

**Comment by ford220102** [comment]
@stavros-k But I have a lot of faulty ones from this one and there are debian connections, a lot of packages are missing, I don't know exactly what you did and if it keeps crashing, I don't know what's wrong with k3s and I can't find the exact one, e.g. missing php or something and not up to date quality But how if they don't understand what's going on?
