### ISSUE TITLE
Updating configuration on Minecraft app isn't possible

### ISSUE THREAD

**Issue by maxnatamo** [truenas/charts#2010]
Hello,

Currently, it doesn't seem like you can update the Minecraft app on TrueNAS Scale. Any update to the app, after creation, will throw an error:
`Error: [EINVAL] values.mcStorage.data.hostPathConfig.hostPath: attribute required`

This option, however, is blacked out in the panel, so it cannot be changed.

**Comment by stavros-k** [comment]
Hello, what is your TrueNAS Scale version?
Thanks

**Comment by maxnatamo** [comment]
I upgraded to TrueNAS-SCALE-23.10.1, and the problem has gone away.
