### ISSUE TITLE
"attempt to write a readonly database" after Kapowarr 2.0 update

### ISSUE THREAD

**Issue by Casuallynoted** [truenas/charts#2026]
Ever since I updated my Kapowarr app to version 2.0, it's been failing to launch and claims the sqlite database is read only.

**Comment by stavros-k** [comment]
If you are using hostPath, you have to adjust permissions yourself.
New Kapowarr version runs as root due to upstream changes. So make sure `0:0` have access to the mounted directories

I did a fresh install with ixVolumes and I didn't not see any errors

**Comment by Casuallynoted** [comment]
> If you are using hostPath, you have to adjust permissions yourself. New Kapowarr version runs as root due to upstream changes. So make sure `0:0` have access to the mounted directories
> 
> I did a fresh install with ixVolumes and I didn't not see any errors

Unfortunately I'm not using HostPath

**Comment by stavros-k** [comment]
I tried to set a password aswell (even changing log level), but does not save, snooping in the browser console, it fails with invalid comic vine API key.

**Comment by stavros-k** [comment]
Hello, closing this for now as it seems like an upstream issue(?).
If you find something that is on our side feel free to reply back to take another look.

Thanks
