### ISSUE TITLE
Community Chart not updated: cloudflared

### ISSUE THREAD

**Issue by razvanphp** [truenas/charts#2028]
The current situation in TrueNAS chart:

```
App Version:
2023.10.0
Chart Version:
1.2.2
```

Latest image in docker hub: [2024.1.1](https://hub.docker.com/r/cloudflare/cloudflared/tags)

Seems like there was also an `2024.1.0` tag, but now it disappeared... strange, just want to make sure the chart is automatically updated, so we avoid issues like #1347

PS: is this basically a clone of the TrueCharts version? Now confusion start to pile up with this community train... not sure if it's just me.

Thank you!
R

**Comment by stavros-k** [comment]
Hello, updates are [picked up](https://github.com/truenas/charts/pull/2025), 
Had to close this one because of some conflicts, tomorrow the update will be released

**Comment by razvanphp** [comment]
Ok, great, good to know.

Wouldn't it be easier to have the image tag as a parameter in the chart? This way, people can update it on their own...

**Comment by razvanphp** [comment]
PS: they just released [2024.1.2](https://hub.docker.com/layers/cloudflare/cloudflared/2024.1.2/images/sha256-d8fe729c4f2b2392bcaae002f60c7f22a4da90ab67215ccdc2efe4d817ff1c84?context=explore)

**Comment by stavros-k** [comment]
Fixed in #2033
