### ISSUE TITLE
Nextcloud - error when changing PHP memory limit

### ISSUE THREAD

**Issue by jwojtas10** [truenas/charts#2032]
I'm trying to change PHP memory limit from 512MB to 1024MB, but when I try to update settings it shows me: 
`[EFAULT] Failed to update App: Error: UPGRADE FAILED: cannot patch "nextcloud" with kind Deployment: The order in patch list: [map[name:OVERWRITEHOST value:192.168.0.18:9001] map[name:OVERWRITEHOST value:TOPSECRET] map[name:PHP_MEMORY_LIMIT value:1024M]] doesn't match $setElementOrder list: [map[name:POSTGRES_USER] map[name:POSTGRES_PASSWORD] map[name:OVERWRITECLIURL] map[name:OVERWRITEHOST] map[name:POSTGRES_HOST] map[name:POSTGRES_DB] map[name:NEXTCLOUD_DATA_DIR] map[name:PHP_UPLOAD_LIMIT] map[name:PHP_MEMORY_LIMIT] map[name:APACHE_DISABLE_REWRITE_IP] map[name:OVERWRITEHOST] map[name:OVERWRITEPROTOCOL] map[name:TRUSTED_PROXIES] map[name:NEXTCLOUD_TRUSTED_DOMAINS] map[name:NEXTCLOUD_ADMIN_USER] map[name:NEXTCLOUD_ADMIN_PASSWORD]]`

` Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 427, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 465, in __run_body
    rv = await self.method(*([self] + args))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 194, in nf
    rv = await func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 44, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 177, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 559, in do_update
    await self.middleware.call('chart.release.helm_action', chart_release, chart_path, config, 'update')
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1399, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 49, in helm_action
    raise CallError(f'Failed to {tn_action} App: {errmsg}')
middlewared.service_exception.CallError: [EFAULT] Failed to update App: Error: UPGRADE FAILED: cannot patch "nextcloud" with kind Deployment: The order in patch list:
[map[name:OVERWRITEHOST value:192.168.0.18:9001] map[name:OVERWRITEHOST value:TOPSECERT] map[name:PHP_MEMORY_LIMIT value:1024M]]
 doesn't match $setElementOrder list:
[map[name:POSTGRES_USER] map[name:POSTGRES_PASSWORD] map[name:OVERWRITECLIURL] map[name:OVERWRITEHOST] map[name:POSTGRES_HOST] map[name:POSTGRES_DB] map[name:NEXTCLOUD_DATA_DIR] map[name:PHP_UPLOAD_LIMIT] map[name:PHP_MEMORY_LIMIT] map[name:APACHE_DISABLE_REWRITE_IP] map[name:OVERWRITEHOST] map[name:OVERWRITEPROTOCOL] map[name:TRUSTED_PROXIES] map[name:NEXTCLOUD_TRUSTED_DOMAINS] map[name:NEXTCLOUD_ADMIN_USER] map[name:NEXTCLOUD_ADMIN_PASSWORD]]`

Changing to anything above 512MB will cause the error.

![image](https://github.com/truenas/charts/assets/50745238/c855dd4a-91f0-4998-9f2c-35d0c792a86a)

![image](https://github.com/truenas/charts/assets/50745238/42dab5f5-ee48-4187-96d2-42a3adcd13f5)

**Comment by stavros-k** [comment]
Looks like the `OVERWRITEHOST` appears twice. Do you have additional environment variables set?

**Comment by jwojtas10** [comment]
> Looks like the `OVERWRITEHOST` appears twice. Do you have additional environment variables set?

Yes, I have set OVERWRITEHOST and OVERWRITECLIURL additional enviroments, because changing lines in config.php doesn't work

**Comment by stavros-k** [comment]
The issue here is not the php memory limit, but the duplicate `OVERWRITEHOST`

The default `OVERWRITEHOST` is the nextcloud host + nodePort you define in the the UI

If you want to manually specify `OVERWRITEHOST`, leave `host` empty and set the custom variable as you do now.

**Comment by jwojtas10** [comment]
Thank you for help, I deleted Nextcloud host and now it all works. I'm closing this thread.
