### ISSUE TITLE
[BUG] Home Assistant - postgres Back-off restarting failed

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#2037]
Since the last Home Assistant update, the Postgres container no longer starts with the following error: Back-off restarting failed container home-assistant-postgres in pod home-assistant-postgres. I thought it could be due to the directory access rights again, but I noticed that Home Assistant does not give you the option to set your own directories for the postgres container.

How can the issue be solved?
Can the option to customize the storage paths also be added for the database container?

**Comment by stavros-k** [comment]
Can you please share logs of the postgres container? Lets see what the issue is first.

**Comment by stavros-k** [comment]
Looks like database data is corrupted. Did the system shutdown unexpectedly?

**Comment by stavros-k** [comment]
Hmm, did the first time happened also on upgrade?

**Comment by stavros-k** [comment]
Okay, I'll check some things that come to mind.
Thanks for the confirmation
