### ISSUE TITLE
Frigate Host network mode using ports under 9000

### ISSUE THREAD

**Issue by ramondsq** [truenas/charts#2045]
In order to receive the UDP RTSP stream of my camera ([issue at frigate](https://github.com/blakeblackshear/frigate/issues/9355)), I have to enable the `Host Network` option of app `frigate`, which uses `5000`, `8554` and `8555` ports by default. It works fine now. 

But it is frobidden to use ports under `9000` in apps. I wonder would there be any potential problem with this setting? Or still port forward the ports while `Host Network` is enabled just like `qbittorrent`.

**Comment by stavros-k** [comment]
In most cases UDP will require hostNetwork. 

9000 is the lower limit for `NodePort` when its used by kubernetes service.
Using hostNetwork bypasses that. This is why its recommended to only use hostNet only when required. (Like this case).

qBittorrent allows to change the internal (container) port that it listens to, so even with hostNet enabled, we can change the port that the container will bind on the host.

**Comment by ramondsq** [comment]
> In most cases UDP will require hostNetwork.
> 
> 9000 is the lower limit for `NodePort` when its used by kubernetes service. Using hostNetwork bypasses that. This is why its recommended to only use hostNet only when required. (Like this case).
> 
> qBittorrent allows to change the internal (container) port that it listens to, so even with hostNet enabled, we can change the port that the container will bind on the host.

I'm grateful for your assistance in explaining this to me.
