### ISSUE TITLE
Observations from the last two system updates

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#2048]
The extraction process took an extremely long time and lasted several hours. The server was restarted after the update, but both times the apps running on it were not. The error `smartd is not running` would also be displayed both times. Force restarting the server fixed the problem.

**Comment by stavros-k** [comment]
Hello, I'd suggest opening a ticket on the Jira tracker, so you can also attach a debug file in the private section.
That way someone could take a look!

I'll be closing this one now, as there isn't something specific with the charts themselves.

Thanks!
