### ISSUE TITLE
Frigate: Wrong go2rtc version included

### ISSUE THREAD

**Issue by Adam7288** [truenas/charts#2062]
Woefully out of date compared to the frigate core. Please update the internal go2rtc version to the latest:  1.8.5 as of the time of this writing. Causing all sorts of problems with webrtc. Thanks!

**Comment by stavros-k** [comment]
Quick check shows that go2rtc was updated few times **after** the latest stable release (June 2023)
https://github.com/blakeblackshear/frigate/pull/7122
https://github.com/blakeblackshear/frigate/pull/7250
https://github.com/blakeblackshear/frigate/pull/7657
https://github.com/blakeblackshear/frigate/pull/8691

When frigate releases the next stable version, the contained binary should be updated.

Closing this for now.

Thanks!
