### ISSUE TITLE
Official nextcloud deployment will become extremely slow

### ISSUE THREAD

**Issue by xinbinhan** [truenas/charts#2079]
Official nextcloud deployment will become extremely slow as long as these two options are checked.Has anyone encountered this problem? what is the reason?
![20240125152750](https://github.com/truenas/charts/assets/50063263/0978d6bf-bd70-4258-bf61-c178df5a06de)

**Comment by stavros-k** [comment]
ffmpeg can be very CPU intensive process. It processes videos and images.
That depends how Nextcloud uses it.

**Comment by xinbinhan** [comment]
Correction, what I said is slow is that deploying nextcloud is slow. It takes nearly an hour for it to run normally.

**Comment by stavros-k** [comment]
Selecting those options it will do `apt update` and `apt install`.
The time to complete depends on your connection speed and availability.

**Comment by xinbinhan** [comment]
Can these two be integrated together? There is no need to install it separately again, or whether it can be run as a separate pod, because the log of the installation process cannot be seen

**Comment by stavros-k** [comment]
Those binaries cannot run on a separate pod, as they have to be available for nextcloud process to use them.
We consume the upstream Nextcloud container, Nextcloud have to integrate them into their container in order to skip the installation on each startup.

**Comment by xinbinhan** [comment]
clear

**Comment by stavros-k** [comment]
Closing this!

Thanks
