### ISSUE TITLE
Official nextcloud cannot preview videos

### ISSUE THREAD

**Issue by xinbinhan** [truenas/charts#2080]
Official nextcloud cannot preview videos

**Comment by stavros-k** [comment]
Please share logs that indicate that so we can see if it's something we can fix or if its an upstream issue. 
Also sent what configurations have been made.

Thanks.

**Comment by xinbinhan** [comment]
Video cannot be previewed
![Uploading 企业微信截图_20240126132121.png…]()

**Comment by xinbinhan** [comment]
![20240126132853](https://github.com/truenas/charts/assets/50063263/91b8c479-720c-4600-974d-7cbdf9d40d9a)

**Comment by stavros-k** [comment]
Looks like permissions issue in the nextcloud's directories.
Make sure nextcloud have access to create directories there.
Usually the NC process runs as `33:33` user inside the container

**Comment by xinbinhan** [comment]
![WechatIMG60](https://github.com/truenas/charts/assets/50063263/db052d37-156f-4bb7-afa0-b4ef3ef84fcd)
![WechatIMG61](https://github.com/truenas/charts/assets/50063263/3ebead43-f3d9-4a26-ba26-fc9d546b2f4f)
This is the permission set by my data set, and there is nothing wrong with it.

**Comment by xinbinhan** [comment]
clear

**Comment by stavros-k** [comment]
Closing this for now, let me know if you find more details that the Chart/App might be the problem

Thanks!
