### ISSUE TITLE
Emby chart repo issue.

### ISSUE THREAD

**Issue by ParishMills** [truenas/charts#2087]
I haven't had any luck upgrading my existing Emby app (Truenas chart, not TrueCharts). I'm thinking it's Chart version issue, and you'll see why below.

MAIN APP
Name: emby2
App Version: 4.7.14.0
**_Chart Version: 1.0.29
Source: hub.docker.com/r/emby/embyserver_**
Catalog: TrueNAS
Train: charts

Error Message:
[EFAULT] Failed to upgrade App: Migration to 2.x.x is only allowed from 1.0.30 or higher

I ended up upgrading Truenas from 23.10.1 to 23.10.1.3. Didn't help with my app issue. For the record, I'm using 1 vdev and it's at 73%.

I decided to install another instance of Emby (named Emby-Discard) and set it to a different port. Normally I would assign custom storage for the config files and media locations, but for this I just kept all the defaults. I just wanted to see if there was any difference in the app or chart versions. I found 2 items different, which I've bolded and italicized above and below.

TEMPORARY INSTALL
Name: emby-discard
App Version: 4.7.14.0
**_Chart Version: 2.0.1
Source: emby.media, hub.docker.com/r/emby/embyserver, github.com/truenas/charts/tree/master/charts/emby_**
Catalog: TrueNAS
Train: charts

As you can see, both the chart versions and the sources are different. Both are from Truenas, and not Truecharts. Any idea on how to remedy this?

**Comment by ParishMills** [comment]
It's working now. When you click on update, in the update window -> version to update i could choose from two different versions and the lower one did the emby and chart update. Afterwards, I was able to update to the latest chart.

**Comment by stavros-k** [comment]
Glad it worked.

Closing this now!
