### ISSUE TITLE
[Feature] Allow not setting nodeport

### ISSUE THREAD

**Issue by Ornias1993** [truenas/charts#21]
Some users (for example: those using a reverse proxy) might not want to use a nodeport.
However: currently nodeport is required.

**Comment by Ornias1993** [comment]
I myself fixed it like this:
Fixing the serviceport and container port and only using `nameService.port` for either nodeport or Hostport.
This gives me the room to slightly alter the service to skip the "type" tag if it isn't either a nodeport or hostport situation.
Skipping the type tag for a port, should default to ClusterIP.

See:
https://github.com/truecharts/truecharts/commit/4b64ea3543006ef8bdf18aeaee1fbd8d485cfd2f

**Comment by sonicaj** [comment]
@Ornias1993 can you please clarify which chart you refer to which has a requirement of using `Node Port` service ? Am I correct in assuming that you don't refer to `ix-chart` here and the other supported charts ( nextcloud etc ) we have default to using `Node Port` ? However in your use case you use reverse proxy and don't want them to use `Node Port` ?

**Comment by Ornias1993** [comment]
All your charts as far as i'm aware do NOT support clusterIP. It's either hostnetwork/hostport or nodeip.
Which is extremely non-standard.
