### ISSUE TITLE
netboot.xyz: incorrect upgrade strategy

### ISSUE THREAD

**Issue by CompPhy** [truenas/charts#2104]
I just notice that we ended up using 0.7.0-nbxyz2 as the upstream version.  However, 0.7.0-nbxyz4 is the one that actually contains the NGINX_PORT fix.  Looking at the upgrade_strategy, maybe we need to match on something like `re.compile(r'\d+\.\d+\.\d+-nbxyz\d')`??  This one isn't quite right because of how they're tagging images between versions, we're trying to mash it into semantic_versioning but I'm not sure that's the right thing to do.

I can supply a PR, but would be open to suggestions on a better way to check their version here.

**Comment by stavros-k** [comment]
Last time I checked (for [jellyfin](https://github.com/truenas/charts/pull/2055)) it can handle more than 3 parts.
I suppose we can update the regex as you showed, and do `.replace("-nbxyz", ".")` and it should work.

Feel free to open a PR

**Comment by CompPhy** [comment]
What are your thoughts on adding this to my other PR???  It's already marked as Ready For Review, but we could just kill two birds with one stone.

**Comment by stavros-k** [comment]
Sure np!
