### ISSUE TITLE
Plex cannot update to new version.

### ISSUE THREAD

**Issue by MadMungo** [truenas/charts#2108]
Plex tried to update from version 1.7.60 to 2.0.0 and spat out an error that plex GID {env} cannot orveride already set GID.

I just checked the new version questions.yaml and it has the plex UID & GID hard coded to 586. 

I run my plex server with different  uid & gid set using env variables.

Please keep hardcoded stuff in the .yaml to a minimum, if it has a user changeable option/env variable it should remain user changeable.

**Comment by stavros-k** [comment]
Hello, remove the custom variables you have set,
upgrade and edit the app.
You will see new designated fields to set UID and GID.

The values in questions.yaml are not hardcoded, but a default.
Also during upgrade existing installations have UID and GID set to `1000` which is what plex uses by default.

Let me know if you have more issues.

**Comment by stavros-k** [comment]
I've opened a PR to handle that automatically, you can wait a bit to be merged and update them, so you won't need to do the manual step

Thanks

**Comment by MadMungo** [comment]
Thanks, did as advised and all working again.
