### ISSUE TITLE
netboot.xyz - Portal link does not work correctly when host network is enabled.

### ISSUE THREAD

**Issue by CompPhy** [truenas/charts#2128]
I'm going to enter a PR for this after entering this description.  I have proposed an upstream change which makes the web app port fully configurable within the container image.  This PR will remain as WIP pending approval of the upstream change.  netbootxyz/docker-netbootxyz#57

We setup the chart to use variables for TrueNAS port information.  Based on the current setup, if host network is enabled the portal gets bound on port 3000, not configurable.  However, the URL linked in TrueNAS uses the values.yaml which is defaulting to a higher port number.  This results in a broken link.

The current work around is to just put in port 3000 manually when accessing the web app in this configuration.  Ideally the container should just use the right port here.

**Comment by razvanphp** [comment]
Thank you for this, just noticed it too.

Theoretically if [webPort](https://github.com/truenas/charts/blob/master/community/netbootxyz/1.0.2/questions.yaml#L102) config would not be hidden for host network, then we can set it to 3000 manually.
