### ISSUE TITLE
Invidious: database "kemal" does not exist

### ISSUE THREAD

**Issue by Eliot-Mess** [truenas/charts#2130]
I reported this issue some days ago, and I just updated to the new fixed version.

https://github.com/truenas/charts/issues/2116

However, I still encounter the same error: **database "kemal" does not exist**

Am I installing this correctly? Do I need to create a PostgreS user manually by installing pgAdmin?

Thank you very much.

**Comment by stavros-k** [comment]
Hello, no you don't need to manually do that!
I think I pinpointed the issue. Looks like Both db user and db name is hardcoded somewhere in the invidious application.
