### ISSUE TITLE
[BUG] Collabora

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#2132]
If I want to update collabora to 23.05.8.4.1_2.0.1 the following error occurs:

[EFAULT] Failed to apply migration: Traceback (most recent call last): File "/mnt/Tank/ix-applications/catalogs/github_com_truenas_charts_git_master/charts/collabora/2.0.1/migrations/migrate", line 71, in print(json.dumps(migrate(json.loads(f.read())))) ^^ File "/mnt/Tank/ix-applications/catalogs/github_com_truenas_charts_git_master/charts/collabora/2.0.1/migrations/migrate", line 62, in migrate return migrate_common_lib(values) ^^ File "/mnt/Tank/ix-applications/catalogs/github_com_truenas_charts_git_master/charts/collabora/2.0.1/migrations/migrate", line 31, in migrate_common_lib 'password': values['config']['password'], ~^ KeyError: 'password'

**Comment by BlauerHunger** [comment]
now when trying to update it tells me that the set password doesn't meet requirements even though I can't set one because the "Enable WebUI" checkbox is not checked

**Comment by stavros-k** [comment]
Hmm.. You don't have a password set, right?

**Comment by stavros-k** [comment]
> [EFAULT] Failed to upgrade App: Migration to 2.x.x is only allowed from 1.2.30 or higher

Have you upgraded to 1.2.30 first?

**Comment by cjsanchez** [comment]
I'm not sure if it's noted anywhere, but using the '$' character in the password causes the error to show up:
```
Error: [EINVAL] values.collaboraConfig.password: Password must be at least 8 characters long and contain at least one of the following:< /br >
- Uppercase letter

- Lowercase letter

- Number

- Special character
```
