### ISSUE TITLE
Immich max upload size

### ISSUE THREAD

**Issue by yewkay** [truenas/charts#2142]
It seems that videos are not uploading to immich and the common solution was to increase the max upload size in Nginx.
I've seen the Nextcloud app had a setting implemented for this. Can we have this for Immich as well? Thank you

**Comment by stavros-k** [comment]
Hello, we don't setup our own nginx for Immich, we use the built in web server Immich ships in the image.
You have to reach out to Immich for a way to increase that.

I couldn't find anything on their docs regarding this setting, if there is something we can tweak, I'd be happy to expose that option.

Thanks

**Comment by yewkay** [comment]
thanks! Let me bounce off Immich.

**Comment by stavros-k** [comment]
Thanks, if you find something we can work from our side, please let me know.
Closing this for now!
