### ISSUE TITLE
photoprism upgrade not possible

### ISSUE THREAD

**Issue by TuKo1982** [truenas/charts#2171]
Last photoprism version was 231128_1.1.2 but 231128_2.2.0 requires 1.1.3 to allow upgrade

" [EFAULT] Failed to upgrade App: Migration to 2.x.x is only allowed from 1.1.3 or higher "

**Comment by ajtaylor6** [comment]
I also have this issue, and on my end I have no other option running version 1.1.2 but to upgrade to 2.0.0, there is no 1.1.3 upgrade option available.

**Comment by TheGroundZero** [comment]
+1'ing this

Also: 2.0.0 upgrade doesn't show any changelog

**Comment by stavros-k** [comment]
Hey, in case you have missed a fix is already open ( #2172 )! 
Once this is merged, it should allow you to upgrade to 1.1.3 and then to 2.0.x

Thanks

**Comment by zpackrat** [comment]
just reporting the same issue, stuck on 1.1.2 because there is no 1.1.3 available to upgrade to 2.

**Comment by LarsK1** [comment]
Hi @stavros-k ,
I just wanted to upgrade. But have seen, that the mid-version 1.1.3 has already been deleted? 
https://github.com/truenas/charts/commit/5b2150b07f3a55cccc29087e64e3e6a8753ab293

What's the recommended way of updating?

**Comment by stavros-k** [comment]
> Hi @stavros-k , I just wanted to upgrade. But have seen, that the mid-version 1.1.3 has already been deleted? [5b2150b](https://github.com/truenas/charts/commit/5b2150b07f3a55cccc29087e64e3e6a8753ab293)
> 
> What's the recommended way of updating?

Fix is up for that.. 
https://github.com/truenas/charts/pull/2188
Thanks

**Comment by LarsK1** [comment]
Thank you!
