### ISSUE TITLE
Missing Nextcloud llm dependencies

### ISSUE THREAD

**Issue by pabloeisenhut** [truenas/charts#2176]
**The following is required for the Nextcloud App llm:**

https://github.com/nextcloud/llm
https://apps.nextcloud.com/apps/llm

ERROR: Failed to install python dependencies: Failed to create python venv: python3 -m venv ./python returned The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.11-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /var/www/html/custom_apps/llm/python/bin/python3

**Comment by stavros-k** [comment]
Hey, I'm gonna reference this #2123, just to keep track of it.
But I'll close it, as it's the same "issue" as the referenced one.

Subscribe to the linked one for updates

Thanks!
