### ISSUE TITLE
firefly-iii: Does not accept value ** in additional Environment Variables "TRUSTED_PROXIES"

### ISSUE THREAD

**Issue by ServusNL** [truenas/charts#2197]
firefly-iii requires the env variable TRUSTED_PROXIES with value ** in order to work behind a proxy. See [documentation](https://docs.firefly-iii.org/references/faq/docker/#it-keeps-giving-me-csp-errors) and [git](https://github.com/firefly-iii/firefly-iii/issues/2319#issuecomment-506857511)

TRUSTED_PROXIES=**

The app does not accept the value: **

<img width="486" alt="image" src="https://github.com/truenas/charts/assets/42113454/7dd0bc3e-0156-48d8-a38e-872647877bab">
 
It gives the following error:
![image](https://github.com/truenas/charts/assets/42113454/d1a40bf4-7622-4920-9dd9-c4bbc4792198)

### Steps to reproduce:
Install app with: TRUSTED_PROXIES=**
**Result fails, can not deploy**
Change ** to "**"
**App deploys but env variable is not working**

**Comment by stavros-k** [comment]
I've opened a fix for the parsing error.
But I think you need `*` not `**` (based on the docs)

**Comment by ServusNL** [comment]
@stavros-k  Thanks for the swift fix!
