### ISSUE TITLE
[feature] Grab questions.yaml defaults from values.yaml

### ISSUE THREAD

**Issue by Ornias1993** [truenas/charts#22]
It is needlessly tedieus having to enter the defaults multiple times and might lead to mistakes.

**Comment by sonicaj** [comment]
@Ornias1993 this is not desirable with conditionals like `show_if. So we only want to conditionally populate some attributes values, which if we use `values.yaml`, have to be very careful to make sure we don't make any mistake and even with that it has the tendency to fail in some cases where we don't want to conditionally specify a default value for a variable as this condition is evaluated on runtime by user specified inputs.

Also i am not sure why you are populating `values.yaml` as it's not actually being used by the system when installing / updating chart release ?

**Comment by Ornias1993** [comment]
> Also i am not sure why you are populating values.yaml as it's not actually being used by the system when installing / updating chart release ?

Maybe... because that behavior isn't actually documented? ;-) 

But if thats the case, this issue can be closed... as only one default is actually present 👍
