### ISSUE TITLE
[paperless-ngx] cannot edit parameters after installing

### ISSUE THREAD

**Issue by TheTrueRandom** [truenas/charts#2206]
after installing paperless-ngx chart (2.5.3_1.2.26) it cannot be edited anymore. Changing any parameter (e.g. memory limit) will give following error:

```
Error: [EINVAL] values.paperlessStorage.data.hostPathConfig.hostPath: attribute required
[EINVAL]values.paperlessStorage.media.hostPathConfig.hostPath: attribute required [EINVAL]
values.paperlessStorage.consume.hostPathConfig.hostPath: attribute required [EINVAL]
values.paperlessStorage.trash.hostPathConfig.hostPath: attribute required [EINVAL]
values.paperlessStorage.pgData.hostPathConfig.hostPath: attribute required [EINVAL]
values.paperlessStorage.pgBackup.hostPathConfig.hostPath: attribute required
```

However, the volume selection is completely greyed out and cannot be changed anymore. I used hostPath for all of the volumes when installing the chart.
The deployment itself is running fine. 

![Screenshot_select-area_20240221234407](https://github.com/truenas/charts/assets/43322965/0c3bc095-e1d9-4993-ba5e-b41ea210b8a0)

TrueNAS-SCALE-Bluefin - TrueNAS SCALE Bluefin [release]

**Comment by stavros-k** [comment]
Please upgrade to TrueNAS SCALE Cobia. On Bluefin there was a UI bug causing this issue.
Thanks
