### ISSUE TITLE
Immich - Sticks on Deploying after upgrade

### ISSUE THREAD

**Issue by dayue1984** [truenas/charts#2215]
TrueNAS 23.10.2, immich works great before the upgrade. 

Container Name:immich-init-wait-url:
2024-02-23 12:36:30.898453+08:00Waiting for [http://immich:30041/api/server-info/ping] to be ready...
2024-02-23 12:36:33.938056+08:00wget: can't connect to remote host (172.17.2.44): Connection refused

**Comment by dajavax** [comment]
Unfortunately rolling back does not help.

**Comment by dajavax** [comment]
I believe this was missed: https://docs.pgvecto.rs/admin/upgrading.html#upgrade-from-01x

**Comment by stavros-k** [comment]
Hello, as per Immich upgrade notes, try to stop the application and re-start it.
I think this will make Immich detect the upgraded db version and do the migration steps itself.

In any other case, I'll need logs of the containers of the Immich app (server, microservices, database, etc)

**Comment by JuliusSenkus** [comment]
Hi, have similar issue, Immich is stuck after upgrade.

Using host path for `Immich Postgres Data Storage` and `Immich Postgres Backup Storage`, it seems that Immich postgres pod is stuck at setting permissions.

```
Back-off restarting failed container immich in pod immich-postgres***
Log:
chmod: changing permissions of '/var/lib/postgresql/data': Operation not permitted

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-02-23 11:02:54.882 EET [1] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
2024-02-23 11:02:54.882 EET [1] HINT:  The server must be started by the user that owns the data directory.
```

Tried to set permissions manually, but can not figure out what user or permissions level would satisfy Immich postgres pod. Any recommendations?

**Comment by stavros-k** [comment]
Postgres runs as `999:999` So this ID must have access.
0700 should be enough for the data dir

**Comment by JuliusSenkus** [comment]
That did the trick, thanks.

**Comment by JuliusSenkus** [comment]
Can confirm, that stopping and starting application also fixes the issue on my end mentioned at the start. Just personal note, that users should not fix application by starting and stopping it even if this is not direct TrueNAS implementation.

**Comment by dayue1984** [comment]
Thabk ypu all! I tried to stop and restart, and then restart the nas, finally removed and reinstall, but all these steps can not fix my immich thats keeps deploying.

**Comment by stavros-k** [comment]
If you are using hostPath and rolled back without rolling back the database data as well, you might have to restore from backup.

Seems to have been database structure changes from Immich + Vector-rs, and rolling back might have made undefined changes. And you might have to restore from backup

Try to upgrade to the latest version, let it sit for few minutes 5-10m. Stop and start the app. Wait few more minutes.

If that doesn't work, I'd suggest reach to Immich support channels and see if there is anything you can do to recover.

**Comment by dajavax** [comment]
@dayue1984 The following thread helped me get past that: https://github.com/immich-app/immich/discussions/7310

I basically had to follow the migration steps posted by [andonovski](https://github.com/andonovski) and then after restarting the containers I ran the extversion update posted by [mertalev](https://github.com/mertalev). This fixed it for me.

**Comment by dayue1984** [comment]
> @dayue1984 The following thread helped me get past that: [immich-app/immich#7310](https://github.com/immich-app/immich/discussions/7310)
> 
> I basically had to follow the migration steps posted by [andonovski](https://github.com/andonovski) and then after restarting the containers I ran the extversion update posted by [mertalev](https://github.com/mertalev). This fixed it for me.

Thank you very much! It works!

**Comment by dayue1984** [comment]
> @dayue1984 The following thread helped me get past that: [immich-app/immich#7310](https://github.com/immich-app/immich/discussions/7310)
> 
> I basically had to follow the migration steps posted by [andonovski](https://github.com/andonovski) and then after restarting the containers I ran the extversion update posted by [mertalev](https://github.com/mertalev). This fixed it for me.

Thank you very much! It works!
