### ISSUE TITLE
passbolt UI won't load from App URL

### ISSUE THREAD

**Issue by machinsk** [truenas/charts#2217]
I've deployed a self hosted passbolt instance commercially before through docker compose and portainer. I don't remember a "App URL" as shown in the TrueNAS deployment. I give it the ip address and port, but the connection is refused. ```http://192.168.10.142:30097``` Can't find much information on the deployment process on truenas or examples of people using it.

It wouldn't deploy without the http or https, behavior is the same with the default truenas cert or none. I am running tailscale, results are the same with ip addresses inside and outside the tailnet. I've checked and unchecked the ```Host Network``` box, nothing. The installation UI seems limited for the complexity of the app, and the 'help' descriptions could use improvement too.

**Comment by stavros-k** [comment]
Hello, can you please check the logs and see if there is anything there that would help?
The App URL is the`APP_FULL_BASE_URL` from Step 3 in this [document](https://help.passbolt.com/hosting/install/ce/docker.html)

If you select a certificate the App URL should start with `https://` and probaly would be good for the domain in the field and the domain in the cert match.

---

What changes would you suggest for improving the installation UI?

Thanks

**Comment by stavros-k** [comment]
Hello, closing this for now, if you still have issues, please let me know.

Thanks
