### ISSUE TITLE
Immich stuck on "Deploying" since latest update (chart 3.0.11 / 1.95.1)

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/charts#2232]
Immich seems stuck on "Deploying". I've included the pod logs:

[immich_immich-microservices-6c5688db97-lvj6n_immich.log](https://github.com/truenas/charts/files/14435567/immich_immich-microservices-6c5688db97-lvj6n_immich.log)
[immich_immich-machinelearning-5b879bd85f-8mqpv_immich.log](https://github.com/truenas/charts/files/14435568/immich_immich-machinelearning-5b879bd85f-8mqpv_immich.log)
[immich_immich-postgres-7966df599d-jtgqp_immich.log](https://github.com/truenas/charts/files/14435569/immich_immich-postgres-7966df599d-jtgqp_immich.log)
[immich_immich-redis-587d56548c-dg6h9_immich.log](https://github.com/truenas/charts/files/14435570/immich_immich-redis-587d56548c-dg6h9_immich.log)
[immich_immich-cb87b86df-ldhdj_immich.log](https://github.com/truenas/charts/files/14435571/immich_immich-cb87b86df-ldhdj_immich.log)

**Comment by stavros-k** [comment]
Hello, there are some info [on this issue](https://github.com/truenas/charts/issues/2215) and [on the Immich release notes](https://github.com/immich-app/immich/releases/tag/v1.95.1) on what you need to do.

**Comment by TimvanDijkNL** [comment]
After performing the mentioned stop / start, the error remains:

[immich_immich-postgres-6475c8ff6f-fl8tr_immich.log](https://github.com/truenas/charts/files/14438537/immich_immich-postgres-6475c8ff6f-fl8tr_immich.log)

**Comment by stavros-k** [comment]
Have you tried this? 
https://github.com/truenas/charts/issues/2215#issuecomment-1961506210

I suppose it points to this
https://github.com/immich-app/immich/discussions/7310#discussioncomment-8545598
and
https://github.com/immich-app/immich/discussions/7310#discussioncomment-8559595

**Comment by dajavax** [comment]
I actually meant this
https://github.com/immich-app/immich/discussions/7310#discussioncomment-8545598
and
https://github.com/immich-app/immich/discussions/7310#discussioncomment-8550802

I mention it in
https://github.com/immich-app/immich/discussions/7310#discussioncomment-8569663

As for how to run it, she'll into the postgres container and run psql command with immich user.

**Comment by TimvanDijkNL** [comment]
Ok, 

Let's see here... i shelled into the postgres container and copy-pasted the sql queries from @dajavax link:

`$ psql -U immich
psql (15.5 (Debian 15.5-1.pgdg120+1))
Type "help" for help.

immich=# CREATE SCHEMA IF NOT EXISTS vectors;
UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';

CREATE EXTENSION vectors;

ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';

SELECT pgvectors_upgrade();
NOTICE:  schema "vectors" already exists, skipping
CREATE SCHEMA
UPDATE 1
UPDATE 1
ERROR:  extension "vectors" already exists
ALTER EXTENSION
UPDATE 1
ERROR:  type "vecf16" already exists
WARNING:  pgvecto.rs is upgraded. Restart PostgreSQL to take effects.
 pgvectors_upgrade 
-------------------
 
(1 row)

immich=# command terminated with exit code 137`

then restarted Immich. It got stuck in deploying still, with the error:

`2024-02-29 09:04:15.789420+01:002024-02-29 09:04:15.789 CET [435] ERROR:  type "vecf16" already exists
2024-02-29 09:04:15.789485+01:002024-02-29 09:04:15.789 CET [435] STATEMENT:  ALTER EXTENSION vectors UPDATE TO '0.2.0`

So i ran the 2nd query from the linked comment:

`$ psql -U immich
psql (15.5 (Debian 15.5-1.pgdg120+1))
Type "help" for help.

immich=# UPDATE pg_catalog.pg_extension SET extversion = '0.2.0' WHERE extname = 'vectors';
UPDATE 1
immich=# quit
$ `

Then I restarted immich again, and it seems to work! 😀
