### ISSUE TITLE
Pi-Hole - Error when updating to version 2.0.5

### ISSUE THREAD

**Issue by beto868** [truenas/charts#2236]
I'm on Truenas Scale version 23.10.2 running the "pihole 2023.11.0" from the official Truenas catalog on version 1.0.25 and when trying to migrate to version 2.0.5 I run into the following error highlighted below:

Error: _'error converting YAML to JSON: yaml: line 34: found character that cannot start any token'_

**Comment by stavros-k** [comment]
Hello, can you share the output of `midclt chart.release.get_instance pihole | jq '.config'`
(Replace `pihole` with the name you gave to the app). Also don't forget to remove any sensitive info,like passwords

Thanks

**Comment by beto868** [comment]
I don't know if I did anything wrong. I went into the System Settings option → shell 
I typed the mentioned command and it gave this error below:

_admin@truenas[~]$ midclt chart.release.get_instance pihole | jq '.config'
usage: midclt [-h] [-q] [-u URI] [-U USERNAME] [-P PASSWORD] [-K API_KEY]
              [-t TIMEOUT]
              {call,ping,waitready,sql,subscribe} ...
midclt: error: argument name: invalid choice: 'chart.release.get_instance' (choose from 'call', 'ping', 'waitready', 'sql', 'subscribe')_

**Comment by stavros-k** [comment]
Sorry forgot something
`midclt call chart.release.get_instance pihole | jq '.config'`

**Comment by beto868** [comment]
_"appVolumeMounts": {
    "config": {
      "hostPath": "/mnt/my/pihole/data",
      "hostPathEnabled": true,
      "mountPath": "/etc/pihole"
    },
    "dnsmasq": {
      "hostPath": "/mnt/my/pihole/dnsmasq",
      "hostPathEnabled": true,
      "mountPath": "/etc/dnsmasq.d"
    }
  },
  "dhcp": false,
  "dnsConfig": {
    "options": []
  },
  "enableResourceLimits": false,
  "environmentVariables": [],
  "extraAppVolumeMounts": [],
  "global": {
    "ixChartContext": {
      "addNvidiaRuntimeClass": false,
      "hasNFSCSI": true,
      "hasSMBCSI": true,
      "isInstall": false,
      "isStopped": false,
      "isUpdate": false,
      "isUpgrade": true,
      "kubernetes_config": {
        "cluster_cidr": "172.16.0.0/16",
        "cluster_dns_ip": "172.17.0.10",
        "service_cidr": "172.17.0.0/16"
      },
      "nfsProvisioner": "nfs.csi.k8s.io",
      "nvidiaRuntimeClassName": "nvidia",
      "operation": "UPGRADE",
      "smbProvisioner": "smb.csi.k8s.io",
      "storageClassName": "ix-storage-class-pihole",
      "upgradeMetadata": {
        "newChartVersion": "1.0.25",
        "oldChartVersion": "1.0.24",
        "preUpgradeRevision": 1
      }
    }
  },
  "image": {
    "pullPolicy": "IfNotPresent",
    "repository": "pihole/pihole",
    "tag": "2023.11.0"
  },
  "ixCertificateAuthorities": {},
  "ixCertificates": {},
  "ixChartContext": {
    "addNvidiaRuntimeClass": false,
    "hasNFSCSI": true,
    "hasSMBCSI": true,
    "isInstall": false,
    "isStopped": false,
    "isUpdate": false,
    "isUpgrade": true,
    "kubernetes_config": {
      "cluster_cidr": "172.16.0.0/16",
      "cluster_dns_ip": "172.17.0.10",
      "service_cidr": "172.17.0.0/16"
    },
    "nfsProvisioner": "nfs.csi.k8s.io",
    "nvidiaRuntimeClassName": "nvidia",
    "operation": "UPGRADE",
    "smbProvisioner": "smb.csi.k8s.io",
    "storageClassName": "ix-storage-class-pihole",
    "upgradeMetadata": {
      "newChartVersion": "1.0.25",
      "oldChartVersion": "1.0.24",
      "preUpgradeRevision": 1
    }
  },
  "ixExternalInterfacesConfiguration": [],
  "ixExternalInterfacesConfigurationNames": [],
  "ixVolumes": [],
  "ownerGID": 568,
  "ownerUID": 568,
  "password": "XXXXXXXXXXXX",
  "release_name": "pihole",
  "timezone": "UTC",
  "web_port": 20720_

**Comment by beto868** [comment]
_"appVolumeMounts": {
    "config": {
      "hostPath": "/mnt/my/pihole/data",
      "hostPathEnabled": true,
      "mountPath": "/etc/pihole"
    },
    "dnsmasq": {
      "hostPath": "/mnt/my/pihole/dnsmasq",
      "hostPathEnabled": true,
      "mountPath": "/etc/dnsmasq.d"
    }
  },
  "dhcp": false,
  "dnsConfig": {
    "options": []
  },
  "enableResourceLimits": false,
  "environmentVariables": [],
  "extraAppVolumeMounts": [],
  "global": {
    "ixChartContext": {
      "addNvidiaRuntimeClass": false,
      "hasNFSCSI": true,
      "hasSMBCSI": true,
      "isInstall": false,
      "isStopped": false,
      "isUpdate": false,
      "isUpgrade": true,
      "kubernetes_config": {
        "cluster_cidr": "172.16.0.0/16",
        "cluster_dns_ip": "172.17.0.10",
        "service_cidr": "172.17.0.0/16"
      },
      "nfsProvisioner": "nfs.csi.k8s.io",
      "nvidiaRuntimeClassName": "nvidia",
      "operation": "UPGRADE",
      "smbProvisioner": "smb.csi.k8s.io",
      "storageClassName": "ix-storage-class-pihole",
      "upgradeMetadata": {
        "newChartVersion": "1.0.25",
        "oldChartVersion": "1.0.24",
        "preUpgradeRevision": 1
      }
    }
  },
  "image": {
    "pullPolicy": "IfNotPresent",
    "repository": "pihole/pihole",
    "tag": "2023.11.0"
  },
  "ixCertificateAuthorities": {},
  "ixCertificates": {},
  "ixChartContext": {
    "addNvidiaRuntimeClass": false,
    "hasNFSCSI": true,
    "hasSMBCSI": true,
    "isInstall": false,
    "isStopped": false,
    "isUpdate": false,
    "isUpgrade": true,
    "kubernetes_config": {
      "cluster_cidr": "172.16.0.0/16",
      "cluster_dns_ip": "172.17.0.10",
      "service_cidr": "172.17.0.0/16"
    },
    "nfsProvisioner": "nfs.csi.k8s.io",
    "nvidiaRuntimeClassName": "nvidia",
    "operation": "UPGRADE",
    "smbProvisioner": "smb.csi.k8s.io",
    "storageClassName": "ix-storage-class-pihole",
    "upgradeMetadata": {
      "newChartVersion": "1.0.25",
      "oldChartVersion": "1.0.24",
      "preUpgradeRevision": 1
    }
  },
  "ixExternalInterfacesConfiguration": [],
  "ixExternalInterfacesConfigurationNames": [],
  "ixVolumes": [],
  "ownerGID": 568,
  "ownerUID": 568,
  "password": "XXXXXXXXXXXX",
  "release_name": "pihole",
  "timezone": "UTC",
  "web_port": 20720_

**Comment by stavros-k** [comment]
I guess you password has a special character?
I've opened a fix, once its merged refresh your catalog and try with version 2.0.6!

**Comment by beto868** [comment]
Yes, it has special characters.
Would the ideal be to change the password so you don't have it and avoid future mistakes?
I use it to make the password more complex to be cracked

**Comment by stavros-k** [comment]
You can change it for now and once the fix lands, you can set it to more complex again!
