### ISSUE TITLE
Storj - Sticks on Deploying after upgrade

### ISSUE THREAD

**Issue by dajavax** [truenas/charts#2237]
When updating from v1.68.2_1.0.18 to v1.68.2_2.0.0 it gets stuck deploying with the following error in the log for "storj-init-03-setup"

`ERROR	contact:service	ping satellite failed 	{"process": "storagenode", "Satellite ID": "", "attempts": 1, "error": "ping satellite: failed to ping storage node, your node indicated error code: 0, rpc: tcp connector failed: rpc: dial tcp 187.213.149.244:28967: connect: connection timed out", "errorVerbose": "ping satellite: failed to ping storage node, your node indicated error code: 0, rpc: tcp connector failed: rpc: dial tcp xxx.xxx.xxx.xxx:28967: connect: connection timed out\n\tstorj.io/storj/storagenode/contact.(*Service).pingSatelliteOnce:209\n\tstorj.io/storj/storagenode/contact.(*Service).pingSatellite:157\n\tstorj.io/storj/storagenode/contact.(*Chore).updateCycles.func1:87\n\tstorj.io/common/sync2.(*Cycle).Run:99\n\tstorj.io/common/sync2.(*Cycle).Start.func1:77\n\tgolang.org/x/sync/errgroup.(*Group).Go.func1:75"}`

This error repeats with many Satellite IDs.

Rolling back to v1.68.2_1.0.18 makes it work again.

**Comment by SalataZ** [comment]
I can confirm, same problem. I've to revert to 1.0.18.

**Comment by stavros-k** [comment]
Hello, I've pushed a fix to actually skip the setup if the config file is present.

Can you please also verify for me that the config.yaml file contains the correct details in regards to these fields?
- operator.wallet
- operator.email
- contact.external-address (here the it should be `<your-public-ip-or-dns>:<p2pPort-from-webui>`) and also the same port must be open on your firewall, but that should already be inplace since you had it working before.

Thanks

**Comment by dajavax** [comment]
Currently in v1.68.2_1.0.18 those 3 fields show up as "" for me in the config.yaml file.

**Comment by kutyla-philipp** [comment]
Same here. Reverted back to 1.0.18.

**Comment by stavros-k** [comment]
> Currently in v1.68.2_1.0.18 those 3 fields show up as "" for me in the config.yaml file.

This is weird, how does storj knows your information if those are empty?
Did you check from inside the container or on your dataset?

**Comment by dajavax** [comment]
I checked on the dataset. However I was now able to upgrade to 2.0.1 without issues, thanks.
