### ISSUE TITLE
emby Intel GPU hardware transcoding issue

### ISSUE THREAD

**Issue by wongsyrone** [truenas/charts#2247]
Hi,

I fixed emby Intel GPU hardware transcoding issue via "Additional Environments", please refer to https://hub.docker.com/r/emby/embyserver/#vaapi for details.

The official Docker image accepts three important environment variables:

- UID: The UID to run emby as
- GID: The GID to run emby as
- GIDLIST: A comma-separated list of additional GIDs to run emby as

According to official instructions, GIDLIST is also needed to grant access to VAAPI/NVDEC/NVENC render nodes. It is recommended to leave UID and GID as is so that emby runs with the least amount of privileges, and use GIDLIST to obtain the permissions you need.

```
root@truenas[~]# ls -al /dev/dri
total 0
drwxr-xr-x  3 root root        100 Mar  3 12:24 .
drwxr-xr-x 19 root root       4560 Mar  3 12:27 ..
drwxr-xr-x  2 root root         80 Mar  3 12:24 by-path
crw-rw----  1 root video  226,   0 Mar  3 12:24 card0
crw-rw----  1 root render 226, 128 Mar  3 12:24 renderD128
```

In general, emby is run as an ordinary user with gid 2 or 1000, while the required char device is owned by root, `video` and `render` group must be added to GIDLIST.

```
root@truenas[~]# getent group video
video:x:44:
root@truenas[~]# getent group render
render:x:107:
```

To workaround the hw transcoding issue, I must add `GIDLIST=44,107` to emby configuration page. I hope truenas scale add these two groups automatically, without manual intervention.

**Comment by stavros-k** [comment]
Opened a PR to do that automatically!
Make sure you remove the manually added env before upgraded, (it will give you an error saying there is a duplicate otherwise)
