### ISSUE TITLE
n8n app changed to pre-release, breaks usage

### ISSUE THREAD

**Issue by ErroneousBosch** [truenas/charts#2262]
Update to the n8n chart switched to the pre-release 1.32 version, which is not stable but pre-release. Updating the app breaks login to the app via the web portal.

This should be downgraded to the latest stable 1.31.x release: 1.31.2
https://github.com/n8n-io/n8n/releases

**Comment by stavros-k** [comment]
Hello, according to n8n this is a stable release.

See https://github.com/truenas/charts/pull/2178#issuecomment-1956421939

Regarding your issue, please share logs so we can see if the issue lies on our side first.
Thanks

**Comment by ErroneousBosch** [comment]
That likely explains it. I was getting a ton of 401 unauthorized errors in the browser console. I don't have logs as I already deleted the container and switched to the TC one. Maybe I will switch back, I haven't decided. Thanks for getting back to me

**Comment by stavros-k** [comment]
Yea, just tried a fresh install and seems that 1.32.x has this issue. 
Login does work (eg wrong password shows wrong pass, but correct moves to the next screen), but thats pretty much it, beyond that it just loads forever with 401's.
I'd suggest opening a bug report upstream, as it will affect TC version too once they newer image drops there.

**Comment by ErroneousBosch** [comment]
Bug report put in for n8n [8850](https://github.com/n8n-io/n8n/issues/8850) #

**Comment by Joffcom** [comment]
This happens if you access n8n over HTTP instead of HTTPS, The best solution would be to use HTTPS for your instance but you should be able to work around it by setting `N8N_SECURE_COOKIE` to `false` as an env option.
