### ISSUE TITLE
How to change runAs user and group in immich

### ISSUE THREAD

**Issue by maxwassiljew** [truenas/charts#2277]
Hello, I have a question if it is possible to change the runAs user and group somehow before the immich deployment?

Currently, a fresh deployment would result in running postgres database with the user `netdata` and group `docker`.

`netdata` is a built-in user with uid:gid 999:997
`docker` is a built-in group with gid:999

At first glance it looks like a permission chaos or is there more to it?

![Screenshot 2024-03-12 at 11 48 09](https://github.com/truenas/charts/assets/27824730/24f2011e-5bf0-49d4-8090-8f4d553a4f5a)
![Screenshot 2024-03-12 at 11 47 49](https://github.com/truenas/charts/assets/27824730/47a1c8ab-8721-42dd-99e9-407a45cbf00d)
![Screenshot 2024-03-12 at 11 49 14](https://github.com/truenas/charts/assets/27824730/16d98ad2-bca7-41cb-97fe-23ffe26a10f5)
![Screenshot 2024-03-12 at 11 48 46](https://github.com/truenas/charts/assets/27824730/81d97bcf-8e6c-4d78-a4b9-1ae96b9859d8)

**Comment by stavros-k** [comment]
Hello this is the internal UID/GID of the **postgres** container, it just happen to map to different names on the host

The IDs are defined on the upstream container.
https://github.com/docker-library/postgres/blob/44ef8b226a40f86cf9df3f9299067db6779a3aa3/15/bookworm/Dockerfile#L11-L13

**Comment by stavros-k** [comment]
I'll close this for now, let me know if you have more questions. 

Thanks!
