### ISSUE TITLE
Can't edit configuration of linkding

### ISSUE THREAD

**Issue by philer-jambit** [truenas/charts#2282]
I tried installing **linkding** from the community charts. I selected host paths for all storage configuration (data, postgres & postgres backup). The app was installed and available over the network. When I try to edit the app configuration afterwards (in truenas » apps) I can no longer see the selected host paths and when I go to save it shows an error that host paths are required:
```
Error: [EINVAL] values.linkdingStorage.data.hostPathConfig.hostPath: attribute required
[EINVAL] values.linkdingStorage.pgData.hostPathConfig.hostPath: attribute required
[EINVAL] values.linkdingStorage.pgBackup.hostPathConfig.hostPath: attribute required 
```
![Screenshot 2024-03-15 at 11-51-41 TrueNAS - moria](https://github.com/truenas/charts/assets/79307632/1ae2aebd-fdfc-4022-9713-376ca313b954)

I checked [the relevant `questions.yaml`](https://github.com/truenas/charts/blob/master/community/linkding/1.2.10/questions.yaml#L177) and saw that it has a show condition on ACLs – I did *not* enable the ACL option when I installed the app.

Please let me know if there is anything I can do to fix this.

---

Side issue: What I was *trying* to edit is the "Username" option which I had left empty. The help text for this option states: "Leaving this empty will disable authentication." ([line in `questions.yaml`](https://github.com/truenas/charts/blob/master/community/linkding/1.2.10/questions.yaml#L32)) – This is apparently incorrect, as I am still shown a login dialog upon first visiting the app's web view, except that now I don't have any user to log in with.

**Comment by stavros-k** [comment]
Please upgrade to TrueNAS Cobia the issue should be solved there, there was an issue with WebUI in Bluefin.

Thanks
