### ISSUE TITLE
nextcloud shows update available when is already up to date

### ISSUE THREAD

**Issue by sbe-arg** [truenas/charts#2286]
No clue where to log the issue let me know if needs to go into another github space

![image](https://github.com/truenas/charts/assets/23391642/b74da787-3ddc-4c60-bcac-9660f3713cd8)

**Comment by stavros-k** [comment]
Hello, can you post the output of the bellow command? Run it on the TrueNAS Shell.

```sh
midclt call container.image.query
```
Thanks

**Comment by sbe-arg** [comment]
I assume the important bit is ""update_available": true," ?
```
{
    "id": "sha256:ea0d219f8302b3fafca6bf69dacdf294d4e5fb9ef0a7ce517d8c271393da2cca",
    "repo_tags": [
        "docker.io/library/nextcloud:28.0.3"
    ],
    "repo_digests": [
        "docker.io/library/nextcloud@sha256:4aa8fdda6f280d3a3bc7786de33af3f27fdf00f158427672a962d010d4789064"
    ],
    "size": 422669625,
    "dangling": false,
    "update_available": true,
    "system_image": false
},
```

**Comment by sbe-arg** [comment]
I ran the "update" and the available notification went away... waited a few hours and it where there again.

**Comment by stavros-k** [comment]
Okay, I see whats happening.
Nextcloud overwrite's the `28.0.3` tag and the `digest` is changing.
So that's why it shows you that there is an update.

Both container version and chart version is the same, but the digest of the upstream container is newer.

**Comment by sbe-arg** [comment]
Not sure why was marked as completed XD
Not sure why the digest got updated then :thinking: a re-tag?

**Comment by sbe-arg** [comment]
@stavros-k how can I force a pull of the image from the cli so I get the correct digest?

**Comment by sbe-arg** [comment]
That worked

**Comment by sbe-arg** [comment]
hey @stavros-k this keeps happening every 1-2 weeks after I update the images says there is an update and a sh mismatch.

there is something odd. can we reopen?

**Comment by sbe-arg** [comment]
what the? 
![image](https://github.com/truenas/charts/assets/23391642/ffc7d242-044c-4b8d-b374-7e34518cb711)

seems like nextcloud is updating the existing tags?

**Comment by sbe-arg** [comment]
@stavros-k if you see here https://github.com/nextcloud/docker/issues/2197 maybe an option is to change the pull strategy of get some alignment into how to avoid the mismatch

**Comment by stavros-k** [comment]
I don't think changing the strategy would help.
If you set it to `Never` then you would have to manually pull the image before you can even install the App.
If you set it to `Always` you will be downloading 400mb + every time you edit or stop and start the App.

**Comment by sbe-arg** [comment]
But it is a problem as it is now.

**Comment by stavros-k** [comment]
It shouldn't be an issue anymore on TrueNAS 24.10 and later.
If you encounter such issue again, feel free to reopen at truenas/apps repo.

Thanks
