### ISSUE TITLE
Add more verbosity to the CI when running Helm Test

### ISSUE THREAD

**Issue by Ornias1993** [truenas/charts#23]
Currently when the CI `helm test` or `helm install`  fails, it's not always clear why...
This ends up being a guessing game, when local runs of helm test work fine.

It would be nice if we could get a little more verbosity from the CI....

That being said: The default for  `helm test` or `helm install` isn't verbose too and I'm not sure if you could make it more verbose.

To explain the problematic scenario's:
I've had multiple cases where the pods/svc's/etc would deploy fine, but running helm with `wait` resulted in timeouts (both locally and in the CI) without a clear reason. Only by tracing back my steps I was able to find the cause in those cases.

But the goal of a CI is to also nudge you in the right direction, while it currently only says "timeout"

**Comment by sonicaj** [comment]
This commit should fix this https://github.com/truenas/catalog_validation/commit/d5510a1eb30ba1f4062bf607c9a66b6ffb148782

**Comment by Ornias1993** [comment]
It should indeed, thanks! :)
