### ISSUE TITLE
Upgrade to 2.0.3 not possible

### ISSUE THREAD

**Issue by 110errm** [truenas/charts#2310]
Upgrade to 203 not possible with the following message:
 File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 49, in helm_action
    raise CallError(f'Failed to {tn_action} App: {errmsg}')
middlewared.service_exception.CallError: [EFAULT] Failed to upgrade App: Persistence - Expected <mountPath> to start with a forward slash [/]

I want kindly ask what went wrong an what can i do?

thx

**Comment by stavros-k** [comment]
Hello, which application?

It seems that you are missing `/` on one of your paths.

**Comment by 110errm** [comment]
Thank u for the answer. The application is syncthing. Installed version is 1.27.3 (chart version 1.0.42). Want to upgrade to 1.27.4 (chart version 2.0.3). Regards

**Comment by stavros-k** [comment]
Did you check that the mount paths or host paths start with a `/`? 
If not, fix it, save and then upgrade!

Thanks!

**Comment by 110errm** [comment]
> Did you check that the mount paths or host paths start with a `/`? If not, fix it, save and then upgrade!
> 
> Thanks!

Configuration with a beginning / resulted in sync issues. So i set up a new instance. Now everthing is working again. Thx again 4 ur fast reply.

Regards

**Comment by stavros-k** [comment]
Anytime!

Closing this now, thanks!
