### ISSUE TITLE
Minio 2.0.3 Install failed

### ISSUE THREAD

**Issue by sopleb** [truenas/charts#2314]
It seems the chart for 2.0.3 is not configured correctly, missing the export volume:
`Error: [EFAULT] Failed to install App: Persistence - Expected < datasetName > [export] to exist on list, but list contained [pgData, pgBackup] on type`

**Comment by sopleb** [comment]
```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 427, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 465, in __run_body
    rv = await self.method(*([self] + args))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 197, in nf
    rv = await func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 44, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 177, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 487, in do_create
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1399, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 49, in helm_action
    raise CallError(f'Failed to {tn_action} App: {errmsg}')
middlewared.service_exception.CallError: [EFAULT] Failed to install App: Persistence - Expected <datasetName> [export] to exist on <ixVolumes> list, but list contained [pgData, pgBackup] on <ixVolume> type```

**Comment by sopleb** [comment]
seems like this singular line is the issue: https://github.com/truenas/charts/blob/1b4fd73fcddb2f26c8acb27f7c385128dcaa6a70/charts/minio/2.0.3/questions.yaml#L185C1-L185C54

**Comment by scapoor** [comment]
I am facing a different error ```[EFAULT] Failed to upgrade App: Container - Environment Variable [MINIO_ROOT_USER] in [envList] tried to override the Environment Variable that is already defined in [Secret - minio-creds]```.

```

Commenting here instead of creating new issue as it relates to the same problem.

**Comment by stavros-k** [comment]
> I am facing a different error `[EFAULT] Failed to upgrade App: Container - Environment Variable [MINIO_ROOT_USER] in [envList] tried to override the Environment Variable that is already defined in [Secret - minio-creds]`.
> 
> ```
>  Error: Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/middlewared/job.py", line 427, in run
>     await self.future
>   File "/usr/lib/python3/dist-packages/middlewared/job.py", line 465, in __run_body
>     rv = await self.method(*([self] + args))
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 177, in nf
>     return await func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 44, in nf
>     res = await f(*args, **kwargs)
>           ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 115, in upgrade
>     await self.upgrade_chart_release(job, release, options)
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 299, in upgrade_chart_release
>     await self.middleware.call('chart.release.helm_action', release_name, chart_path, config, 'upgrade')
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1399, in call
>     return await self._call(
>            ^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1353, in _call
>     return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1251, in run_in_executor
>     return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/helm.py", line 49, in helm_action
>     raise CallError(f'Failed to {tn_action} App: {errmsg}')
> middlewared.service_exception.CallError: [EFAULT] Failed to upgrade App: Container - Environment Variable [MINIO_ROOT_USER] in [envList] tried to override the Environment Variable that is already defined in [Secret - minio-creds]
> ```
> 
> Commenting here instead of creating new issue as it relates to the same problem.

Hello, please use the provided fields in the UI (Root User and Root Password)
Remove the `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` "additional environment variables"

Thanks
