### ISSUE TITLE
chart.release.rollback fails on TrueNas Scale

### ISSUE THREAD

**Issue by nathanhack** [truenas/charts#2320]
[immich.app](https://immich.app/) failed to update so i tried to roll back but chart.release.rollback it just gets stuck at 45% and does nothing. I've tried multiple times and different versions.

After the update failed it won't run. So i'm  just stuck with something that doesn't work.

Not sure where to find the logs to debug. 

Before blowing everything away I thought I might post something here and see if anyone has ideas or suggestions.

**Comment by stavros-k** [comment]
Hello, please check the kubernetes events card in the Apps UI
![image](https://github.com/truenas/charts/assets/47820033/b4dc94b8-130c-4bab-8545-fefafeac7918)

Can you also share the output of the following commands?

```
k3s kubectl get pods -n ix-immich -o wide
k3s kubectl get jobs -n ix-immich -o wide
```

Thanks

**Comment by nathanhack** [comment]
Sorry for the delay,
from the event card:
```
2024-04-08 19:26:02
Container image "tensorchord/pgvecto-rs:pg15-v0.2.0" already present on machine
2024-03-30 19:41:15
Back-off restarting failed container immich in pod immich-postgres-7644dbb79b-qp72l_ix-immich(90cecfca-c2f8-4dee-a9a5-df6975382c7b)
```

```
 k3s kubectl get pods -n ix-immich -o wide
NAME                                     READY   STATUS             RESTARTS           AGE   IP            NODE         NOMINATED NODE   READINESS GATES
immich-postgresbackup-fjgfm              1/1     Running            0                  9d    172.16.0.68   ix-truenas   <none>           <none>
immich-machinelearning-6b696fc56-lxfs8   0/1     Init:0/1           0                  9d    172.16.0.72   ix-truenas   <none>           <none>
immich-microservices-6cd9496758-lns6f    0/1     Init:0/3           0                  9d    172.16.0.73   ix-truenas   <none>           <none>
immich-6c8f4c4b7c-gkg2t                  0/1     Init:0/2           0                  9d    172.16.0.74   ix-truenas   <none>           <none>
immich-redis-79588f864b-4zx9b            1/1     Running            0                  9d    172.16.0.76   ix-truenas   <none>           <none>
immich-postgres-7644dbb79b-qp72l         0/1     CrashLoopBackOff   2548 (2m47s ago)   9d    172.16.0.75   ix-truenas   <none>           <none>
```

```
k3s kubectl get jobs -n ix-immich -o wide
NAME                    COMPLETIONS   DURATION   AGE   CONTAINERS   IMAGES                               SELECTOR
immich-postgresbackup   0/1           30d        30d   immich       tensorchord/pgvecto-rs:pg15-v0.2.0   controller-uid=9fbd2474-6fc1-4146-aff0-5adfcdc629c8
```

**Comment by stavros-k** [comment]
Can you please the postgres container logs? Click the logs icon in the `Workloads` card.
And select the postgres pod and container.

Looks like this is the one thing that currently blocks the app from starting

Thanks

**Comment by nathanhack** [comment]
I don't seem to have one for postgres
![Screenshot from 2024-04-09 14-17-07](https://github.com/truenas/charts/assets/9204400/7a2b393c-14c2-47d7-8283-9de89de61650)
![Screenshot from 2024-04-09 14-15-40](https://github.com/truenas/charts/assets/9204400/9ae2e96b-60b0-4e5c-a75b-43d4a36ab16b)

**Comment by nathanhack** [comment]
```
k3s kubectl delete job -n ix-immich immich-postgresbackup
job.batch "immich-postgresbackup" deleted
```

**Comment by nathanhack** [comment]
workloads after `delete job`
![Screenshot from 2024-04-09 14-20-54](https://github.com/truenas/charts/assets/9204400/fa4f1ba4-399c-409e-a93d-eb2fbfc9a040)

**Comment by stavros-k** [comment]
> I don't seem to have one for postgres
> 
> ![Screenshot from 2024-04-09 14-17-07](https://github.com/truenas/charts/assets/9204400/7a2b393c-14c2-47d7-8283-9de89de61650)
> 
> ![Screenshot from 2024-04-09 14-15-40](https://github.com/truenas/charts/assets/9204400/9ae2e96b-60b0-4e5c-a75b-43d4a36ab16b)
> 
> 

Sorry, for immich is the one named pgvecto

**Comment by nathanhack** [comment]
```
2024-04-09 14:33:27.574214-04:002024-04-09T14:33:27.574214527-04:00
2024-04-09 14:33:27.574237-04:00PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-04-09 14:33:27.574242-04:002024-04-09T14:33:27.574242790-04:00
2024-04-09 14:33:27.616990-04:002024-04-09 14:33:27.616 EDT [1] LOG:  starting PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-04-09 14:33:27.617083-04:002024-04-09 14:33:27.617 EDT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-04-09 14:33:27.617100-04:002024-04-09 14:33:27.617 EDT [1] LOG:  listening on IPv6 address "::", port 5432
2024-04-09 14:33:27.638243-04:002024-04-09 14:33:27.638 EDT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-04-09 14:33:27.655610-04:002024-04-09 14:33:27.655 EDT [16] LOG:  database system was shut down at 2024-03-08 23:06:42 EST
2024-04-09 14:33:27.655683-04:002024-04-09 14:33:27.655 EDT [16] LOG:  invalid resource manager ID in primary checkpoint record
2024-04-09 14:33:27.655700-04:002024-04-09 14:33:27.655 EDT [16] PANIC:  could not locate a valid checkpoint record
2024-04-09 14:33:27.656470-04:002024-04-09 14:33:27.656 EDT [1] LOG:  startup process (PID 16) was terminated by signal 6: Aborted
2024-04-09 14:33:27.656483-04:002024-04-09 14:33:27.656 EDT [1] LOG:  aborting startup due to startup process failure
2024-04-09 14:33:27.656784-04:002024-04-09 14:33:27.656 EDT [1] LOG:  database system is shut down
```

**Comment by stavros-k** [comment]
Sadly database's "write ahead log" seems to have been malformed.
There **might** be a chance that you can revive it. Because you have to shell into the database container,
which exits as soon as it starts due to this error.

If you manage shell in the pgvecto container, you can try running this command, which should reset it, and hopefully nothing of value is lost.

```shell
pg_resetwal -f /var/lib/postgresql/data
```

Alternatively you could move the data directory on a system that has the pg_resetwal command available, execute it
and then move the data directory back.

**Comment by nathanhack** [comment]
Ok, I'm back on the box and I'm trying to back up the all the files, before running the command.
It seems like the original images and videos are all maintained on disk in uuid directories (presumably a uuid per user?).
If the images are on disk, what is in the database?

**Comment by stavros-k** [comment]
I'm not sure what's there.
But I suppose are mostly metadata generated while scanning the library.
Immich developers might be able to answer that better for you.

**Comment by nathanhack** [comment]
Yeah I'm not having any luck grabbing the pgvecto running.  
Is there a way to just run a docker container that has postgress and point to the directory so I can fix the wal?

**Comment by stavros-k** [comment]
You have to run it on a separate machine/vm.
But I'd suggest running the pgvecto one. (https://hub.docker.com/r/tensorchord/pgvecto-rs)

**Comment by stavros-k** [comment]
Hey, I'll go ahead and close this, as there isn't much we can do on our side in this case.

Thanks!
