### ISSUE TITLE
MINIO Settings and Migration Issue from Version 1.7.24 to 2.0.4

### ISSUE THREAD

**Issue by PrinzJuliano** [truenas/charts#2333]
Due to legacy settings, I use the MINIO_VOLUMES Environment Argument and Extra Host Path Volumes to use a host Path for my data volume (previously the Certs Volume as well).

The newly created 2.0.4 Chart will fail the update, as MINIO_VOLUMES cannot be set by both the config YAML and env.
This creates a unique issue for me:
Right now (Version 1.7.24) has the data volume fixed to `/export`.
This in itself is not an issue.
However, the option to set a host Path for that volume is disabled and required.
Going further with this installation bears some risk, as I do not know whether I can set this option in 2.0.4.

<img width="830" alt="2024-04-02-msedge-173" src="https://github.com/truenas/charts/assets/1338788/a760b895-f9b1-4675-bed7-e306de407ee6">

**Comment by stavros-k** [comment]
Hello, can you share the full config in order to get the full picture of what you are doing?

Also, do you use a single volume for the data?
eg `MINIO_VOLUMES: /data`?

**Comment by PrinzJuliano** [comment]
This is my full (redacted) config:
<img width="1433" alt="image" src="https://github.com/truenas/charts/assets/1338788/68616895-bed5-49d4-97d9-fad065b6636b">

Due to previous requirements, the `/mnt/SSD/minio` Volume (on the Pool named SSD) the `data` and `certs` directory were both mounted in MINIO under `/mnt`.

Thus, I could use `/mnt/data` as MINIO_VOLUMES and `/mnt/certs` as `--certs-dir` argument.
I only use one certificate now, which is managed by truenas.

I would need to mount the data volume as `/mnt/SSD/minio/data` to /export. But I do not have the option to set the hostPath in the predefined data volume:
<img width="1800" alt="image" src="https://github.com/truenas/charts/assets/1338788/34acd920-6b87-4f7c-b1f0-620c346e08cf">

Since the migration also defines MINIO_VOLUMES as `/export`K8S rejects the new config as MINIO_VOLUMES is defined multiple times.

**Comment by stavros-k** [comment]
Hmm yea if this wasn't disabled you could map your host path and remove the extra host path and the env variable.

One way is to stop the current installed Minio app.
Create a new Minio App, fill in root user and password, set the Export storage section to your hostpath `/mnt/SSD/data`, select your certificate and fill in your domain. And it should be back up and running. 
Of course backup your data **first**!

Alternatively I can look if its possible to update previous version to unlock that field.

Let me know what you think

**Comment by PrinzJuliano** [comment]
In my opinion, the field should not be disabled in the first place. There has to be an issue / miss configured field.

I will re-set up the app again in the future.

**Comment by stavros-k** [comment]
> In my opinion, the field should not be disabled in the first place.

Version 2.x.x and later have this field enabled at all times.

I'll close this for the time being, but if you have any trouble, please let me know so we can fix it asap.

Thanks
