### ISSUE TITLE
Missing port unificontroller

### ISSUE THREAD

**Issue by ViktorLindstrm** [truenas/charts#2335]
The unifi-controller app currently are lacking the ability to expose 8080 from the container.
The port 8080 is used by the controller to iadopt new network appliances.

Currently there are no option to do so, and the adoption process is not possible. 

https://github.com/goofball222/unifi?tab=readme-ov-file#usage
The container exposes the following ports, and the bold one is the one that would be very appreciated if forwarded.

3478/udp (port used for STUN connection)
6789/tcp (port used for throughput measurement from Android/iOS app)
**8080/tcp (port for UAP/USW/USG to inform controller)**
8443/tcp (port for controller GUI / API)
8880/tcp (port for HTTP portal redirect)
8843/tcp (port for HTTPS portal redirect)
10001/udp (port used for UBNT discovery broadcasts - Local LAN/L2/same subnet only)

**Comment by stavros-k** [comment]
Hello, you can enable the currently labeled webui http port. Which is the inform port (fixing label now)

Here is the system.properties field that sets that port
https://github.com/goofball222/unifi/blob/9713df62f7e29adac7571278bf4e046adb9028a2/release/root/usr/lib/unifi/system.properties.default#L6

And here we set the port via env based on the convention mentioned here
![image](https://github.com/truenas/charts/assets/47820033/4a5e767d-9872-47a2-a6c1-ef1701105313)

https://github.com/truenas/charts/blob/84588588f336f4a40edb4d9e0026c0ee9dad514e/library/ix-dev/community/unifi-controller/templates/_unifi.tpl#L22

**Comment by ViktorLindstrm** [comment]
That makes sense! 
Thanks for clearing that out!  And thanks for the _very_ swift and clear response!
