### ISSUE TITLE
Update icon for qBitttorent

### ISSUE THREAD

**Issue by tannisroot** [truenas/charts#2348]
The icon used for the qBitttorent app is very outdated (and is frankly ugly, which is why it was replaced).
I would make my own PR but I see that the icon_url points to an image hosted on media.sys.truenas.net, so someone from TrueNAS needs to update it.
Link to the current icon from the official repo: https://github.com/qbittorrent/qBittorrent/blob/master/src/icons/qbittorrent-tray.svg
And the .ico version: https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/src/icons/qbittorrent.ico

**Comment by stavros-k** [comment]
Refresh your page!
It should be updated now :D

Thanks!
