### ISSUE TITLE
Update icon for AdGuard too

### ISSUE THREAD

**Issue by tannisroot** [truenas/charts#2350]
Sorry to open another issue, should have been a part of #2349, but Adguard app has the same issue where the icon is really a banner.
I looked and found an .svg of just the logo on the official website, which is available with this link:
https://st.agrd.eu/adguard-4516/img/main.min.svg#shield

**Comment by stavros-k** [comment]
No worries at all! Thanks for finding those images!
Updated it as well!

**Comment by tannisroot** [comment]
> No worries at all! Thanks for finding those images! Updated it as well!

Thanks!
Btw, idk if you just haven't gotten around to it yet, but while the .png did get updated, which is what gets shown when you search for the chart, .svg was not, which is what gets used when the app is actually installed (I checked through source code inspection).
In fact, the link to it is now dead:
https://media.sys.truenas.net/apps/adguard-home/icons/icon.svg
It is what is referenced in `app_versions.json`.

**Comment by stavros-k** [comment]
That makes sense now :D I was confused when I updating the icon, that there was both png and svg.
Thanks for noticing. Should be good now!
