### ISSUE TITLE
Navidrome

### ISSUE THREAD

**Issue by thickmelon** [truenas/charts#2352]
Simple request, but could you add Korean support for Navidrome? It won't read any of my song titles properly, and I don't think I can just straight up paste the ko.json file from this guy's repo into the configs using the shell... (even if I did, every time there's an update, I'll just have to paste it again)
https://github.com/bonik21/navidrome_korean/tree/master/resources/i18n

**Comment by stavros-k** [comment]
Hello, Doesn't setting the `ND_DEFAULTLANGUAGE` env work? 
https://www.navidrome.org/docs/usage/configuration-options/

**Comment by tannisroot** [comment]
> Simple request, but could you add Korean support for Navidrome? It won't read any of my song titles properly, and I don't think I can just straight up paste the ko.json file from this guy's repo into the configs using the shell... (even if I did, every time there's an update, I'll just have to paste it again) https://github.com/bonik21/navidrome_korean/tree/master/resources/i18n

Could you provide a screenshot of the problem you're seeing?

**Comment by thickmelon** [comment]
> Hello, Doesn't setting the `ND_DEFAULTLANGUAGE` env work? https://www.navidrome.org/docs/usage/configuration-options/

Sorry, this wasn't the issue. From what I've seen from the answers given by the Navidrome folks, some tags (I don't really know what kinds) seem to not be able to be read by Navidrome.

**Comment by stavros-k** [comment]
I see, thanks for getting back. I'll close this now then.

Thanks!

**Comment by thickmelon** [comment]
Yeah and thanks for the magical service you always deliver!
