### ISSUE TITLE
Update Immich icon

### ISSUE THREAD

**Issue by tannisroot** [truenas/charts#2355]
New icon: https://github.com/tannisroot/immich/blob/main/design/immich-logo.png

**Comment by stavros-k** [comment]
Done!

**Comment by tannisroot** [comment]
> Done!

So sorry to bother you again, but I just noticed that the .svg from the repository (https://github.com/tannisroot/immich/blob/main/design/immich-logo.svg), unlike the .png, for some reason has huge empty spaces around it (probably because it's for use in their web ui?), making the icon in TrueChart's UI look noticeably smaller than other icons.
I went ahead and resized it in Inkscape myself, but in case you want to do it yourself for security's sake, you just need to go into Inkscape, File->Document Properties->"Display" tab (first one) - > Click "Resize to content", then "Save" or Ctrl+S.
https://github.com/truenas/charts/assets/10602045/fff4c3b4-9c7b-4bb1-add0-b367043eb6d1
![immich-logo](https://github.com/truenas/charts/assets/10602045/fff4c3b4-9c7b-4bb1-add0-b367043eb6d1)

**Comment by stavros-k** [comment]
Should be good now! Thanks again!
