### ISSUE TITLE
App will not delete nor terminate its pods  - Again - This time nextcloud

### ISSUE THREAD

**Issue by pmjufo** [truenas/charts#2361]
Hi,

similar to https://github.com/truenas/charts/issues/2115

Hi,

I have a similar issue.

I try to stop nextcloud 28.0.4_1.6.59 with the GUI, but can't.

    The following is logged in application events:

2024-04-07 16:45:06
Job completed
2024-04-07 16:45:06
Deleted job nextcloud-cronjob-28541670
2024-04-07 16:45:06
Saw completed job: nextcloud-cronjob-28541685, status: Complete
2024-04-07 16:45:01
Created container nextcloud-cronjob
2024-04-07 16:45:01
Started container nextcloud-cronjob
2024-04-07 16:45:00
Created job nextcloud-cronjob-28541685
2024-04-07 16:45:00
Created pod: nextcloud-cronjob-28541685-5fzkp
2024-04-07 16:45:00
Successfully assigned ix-nextcloud/nextcloud-cronjob-28541685-5fzkp to ix-truenas
2024-04-07 16:45:00
Add eth0 [172.17.19.11/16] from ix-net
2024-04-07 16:45:00
Container image "nextcloud:28.0.4" already present on machine
2024-04-07 16:30:05
Job completed
2024-04-07 16:30:05
Saw completed job: nextcloud-cronjob-28541670, status: Complete
2024-04-07 16:30:05
Deleted job nextcloud-cronjob-28541655
2024-04-07 16:30:01
Created container nextcloud-cronjob
2024-04-07 16:30:01
Started container nextcloud-cronjob
2024-04-07 16:30:00
Created job nextcloud-cronjob-28541670
2024-04-07 16:30:00
Created pod: nextcloud-cronjob-28541670-gxhdl
2024-04-07 16:30:00
Successfully assigned ix-nextcloud/nextcloud-cronjob-28541670-gxhdl to ix-truenas
2024-04-07 16:30:00
Add eth0 [172.17.19.10/16] from ix-net
2024-04-07 16:30:00
Container image "nextcloud:28.0.4" already present on machine
2024-04-07 16:15:06
Job completed
2024-04-07 16:15:06
Deleted job nextcloud-cronjob-28541640
2024-04-07 16:15:06
Saw completed job: nextcloud-cronjob-28541655, status: Complete
2024-04-07 16:15:01
Created container nextcloud-cronjob
2024-04-07 16:15:01
Started container nextcloud-cronjob
2024-04-07 16:15:00
Created job nextcloud-cronjob-28541655
2024-04-07 16:15:00
Created pod: nextcloud-cronjob-28541655-w9xcg
2024-04-07 16:15:00
Successfully assigned ix-nextcloud/nextcloud-cronjob-28541655-w9xcg to ix-truenas
2024-04-07 16:15:00
Add eth0 [172.17.19.9/16] from ix-net
2024-04-07 16:15:00
Container image "nextcloud:28.0.4" already present on machine
2024-04-07 16:00:06
Job completed
2024-04-07 16:00:06
Deleted job nextcloud-cronjob-28541625
2024-04-07 16:00:06
Saw completed job: nextcloud-cronjob-28541640, status: Complete
2024-04-07 16:00:01
Created container nextcloud-cronjob
2024-04-07 16:00:01
Started container nextcloud-cronjob
2024-04-07 16:00:00
Created job nextcloud-cronjob-28541640
2024-04-07 16:00:00
Created pod: nextcloud-cronjob-28541640-jzh7n
2024-04-07 16:00:00
Successfully assigned ix-nextcloud/nextcloud-cronjob-28541640-jzh7n to ix-truenas
2024-04-07 16:00:00
Add eth0 [172.17.19.8/16] from ix-net

    The following is logged in Jobs:
    chart.release.scale
    40.00%
    Waiting for pods to be scaled to 0 replica(s)
    chart.release.scale
    Waiting: 07.04.2024 16:31:33
    chart.release.scale
    Waiting: 07.04.2024 13:43:37
    chart.release.scale
    Waiting: 07.04.2024 13:36:35
    chart.release.scale
    Waiting: 07.04.2024 13:35:03
    chart.release.scale
    Waiting: 07.04.2024 13:24:55
    chart.release.scale
    Waiting: 07.04.2024 12:31:26
    chart.release.scale
    Waiting: 07.04.2024 12:26:48
    chart.release.scale
    Waiting: 07.04.2024 12:24:34
    chart.release.scale
    Waiting: 07.04.2024 12:23:08
    chart.release.scale
    Waiting: 07.04.2024 11:52:52
    chart.release.scale
    Waiting: 07.04.2024 11:39:24

    The following lines repeat in syslog every 15 minutes:

Apr 7 16:30:05 truenas ntpd[3452]: Deleting interface https://github.com/truenas/charts/pull/46 vethc72aa53a, fe80::xxxx:xxxx:xxxx:xxxx%35#123, interface stats: received=0, sent=0, dropped=0, active_time=2 secs
Apr 7 16:35:46 truenas nscd[686952]: 686952 monitoring file /etc/hosts (1)
Apr 7 16:35:46 truenas nscd[686952]: 686952 monitoring directory /etc (2)
Apr 7 16:35:46 truenas nscd[686952]: 686952 monitoring file /etc/resolv.conf (3)
Apr 7 16:35:46 truenas nscd[686952]: 686952 monitoring directory /etc (2)
Apr 7 16:40:03 truenas systemd[1]: Starting sysstat-collect.service - system activity accounting tool...
Apr 7 16:40:03 truenas systemd[1]: sysstat-collect.service: Deactivated successfully.
Apr 7 16:40:03 truenas systemd[1]: Finished sysstat-collect.service - system activity accounting tool.
Apr 7 16:45:00 truenas systemd-udevd[704652]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr 7 16:45:00 truenas systemd-udevd[704652]: Using default interface naming scheme 'v247'.
Apr 7 16:45:00 truenas kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethebxxxxxx : link becomes ready
Apr 7 16:45:00 truenas kernel: kube-bridge: port 5(vethebxxxxxx ) entered blocking state
Apr 7 16:45:00 truenas kernel: kube-bridge: port 5(vethebxxxxxx ) entered disabled state
Apr 7 16:45:00 truenas kernel: device vethebxxxxxx entered promiscuous mode
Apr 7 16:45:00 truenas kernel: kube-bridge: port 5(vethebxxxxxx ) entered blocking state
Apr 7 16:45:00 truenas kernel: kube-bridge: port 5(vethebxxxxxx ) entered forwarding state
Apr 7 16:45:00 truenas systemd-udevd[704652]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr 7 16:45:02 truenas ntpd[3452]: bind(39) AF_INET6 fe80::xxxx:xxxx:xxxx:xxxx%36#123 flags 0x11 failed: Cannot assign requested address
Apr 7 16:45:02 truenas ntpd[3452]: unable to create socket on vethebxxxxxx (47) for fe80::xxxx:xxxx:xxxx:xxxx%36#123
Apr 7 16:45:02 truenas ntpd[3452]: failed to init interface for address fe80::xxxx:xxxx:xxxx:xxxx%36
Apr 7 16:45:04 truenas ntpd[3452]: Listen normally on 48 vethebxxxxxx [fe80::xxxx:xxxx:xxxx:xxxx%36]:123
Apr 7 16:45:04 truenas kernel: kube-bridge: port 5(vethebxxxxxx) entered disabled state
Apr 7 16:45:04 truenas kernel: device vethebxxxxxx left promiscuous mode
Apr 7 16:45:04 truenas kernel: kube-bridge: port 5(vethebxxxxxx) entered disabled state
Apr 7 16:45:06 truenas ntpd[3452]: Deleting interface https://github.com/truenas/charts/pull/48 vethebxxxxxx, fe80::xxxx:xxxx:xxxx:xxxx%36#123, interface stats: received=0, sent=0, dropped=0, active_time=2 secs
Apr 7 16:50:04 truenas systemd[1]: Starting sysstat-collect.service - system activity accounting tool...
Apr 7 16:50:04 truenas systemd[1]: sysstat-collect.service: Deactivated successfully.
Apr 7 16:50:04 truenas systemd[1]: Finished sysstat-collect.service - system activity accounting tool.
Apr 7 17:00:00 truenas systemd[1]: Starting sysstat-collect.service - system activity accounting tool...
Apr 7 17:00:00 truenas systemd[1]: sysstat-collect.service: Deactivated successfully.
Apr 7 17:00:00 truenas systemd[1]: Finished sysstat-collect.service - system activity accounting tool.
Apr 7 17:00:00 truenas systemd-udevd[733961]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr 7 17:00:00 truenas systemd-udevd[733961]: Using default interface naming scheme 'v247'.
Apr 7 17:00:00 truenas kernel: IPv6: ADDRCONF(NETDEV_CHANGE): veth33xxxxxx: link becomes ready
Apr 7 17:00:00 truenas kernel: kube-bridge: port 5(veth33xxxxxx) entered blocking state
Apr 7 17:00:00 truenas kernel: kube-bridge: port 5(veth33xxxxxx) entered disabled state
Apr 7 17:00:00 truenas kernel: device veth33xxxxxx entered promiscuous mode
Apr 7 17:00:00 truenas kernel: kube-bridge: port 5(veth33xxxxxx) entered blocking state
Apr 7 17:00:00 truenas kernel: kube-bridge: port 5(veth33xxxxxx) entered forwarding state
Apr 7 17:00:00 truenas systemd-udevd[733961]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Apr 7 17:00:03 truenas ntpd[3452]: Listen normally on 49 veth33xxxxxx [fe80::xxxx:xxxx:xxxx:xxxx)%37]:123
Apr 7 17:00:03 truenas kernel: kube-bridge: port 5(veth33xxxxxx) entered disabled state
Apr 7 17:00:03 truenas kernel: device veth33xxxxxx left promiscuous mode
Apr 7 17:00:03 truenas kernel: kube-bridge: port 5(veth33xxxxxx) entered disabled state
Apr 7 17:00:05 truenas ntpd[3452]: Deleting interface https://github.com/truenas/charts/pull/49 veth33xxxxxx, fe80::xxxx:xxxx:xxxx:xxxx%37#123, interface stats: received=0, sent=0, dropped=0, active_time=2 secs

Installed heavyscript but couldn't stop nextcloud with it:
![320298894-45f4026e-902d-4655-8c2c-569227a95df7](https://github.com/truenas/charts/assets/45011119/647106e6-79f5-4f83-837d-4b95d7582782)

The script states that it stops nextcloud but nothing happens.
Nothing is written to syslog.

How can I stop the app and solve the issue?

Best regards,
Jufo

**Comment by stavros-k** [comment]
Hello, I'm not familiar with what this script does, and considering on your linked issue you have manually tried to remove things bypassing middleware, I can't guarantee things will work as they should.

That being said, can you please open an issue in Jira where you can safely upload a debug file so we can take a look?
Alternatively you can send the debug to `stavros.kois@ixsystems.com`.

Thanks

**Comment by pmjufo** [comment]
Hello,Thank you. Uploaded the debug file for n jira. Addressed to @Stavros Kois.I hope the report finds you well.Best regardsTorstenVon meinem iPhone gesendetAm 09.04.2024 um 15:09 schrieb Stavros Kois ***@***.***>:﻿
Hello, I'm not familiar with what this script does, and considering on your linked issue you have manually tried to remove things bypassing middleware, I can't guarantee things will work as they should.
That being said, can you please open an issue in Jira where you can safely upload a debug file so we can take a look?
Alternatively you can send the debug to ***@***.***
Thanks

**Comment by stavros-k** [comment]
Sorted the issue by email.

For anyone stumble upon this issue:
Upgrading TN version solved it.
