### ISSUE TITLE
wg-easy app won't work with the default config - wrong default port `30057` instead of `51820`

### ISSUE THREAD

**Issue by kroegerama** [truenas/charts#2374]
The config of the wg-easy TrueNAS App [has a default port of `30057`](https://github.com/truenas/charts/blob/fda55eeaac73561557e36c8edc6c08b6b7950bed/charts/wg-easy/2.0.14/ix_values.yaml#L16). However, the wg-easy application itself [has a hardcoded port `51820`](https://github.com/wg-easy/wg-easy/blob/ed369ff199204fb9f63e50587f558a7b8448b7db/src/lib/WireGuard.js#L98). It seems, the developer of wg-easy has a strong opinion on not making this hardcoded port customizable.

So if you don't know better and just confirm the default options, Wireguard won't work at all.

It was really hard to find the cause, but I was able to fix it by defining the correct port while installing the app, but other users might not find this info and get stuck.

**Comment by stavros-k** [comment]
Hello, thanks for finding this.

The WG_PORT allows the user to change the "endpoint" port, I've just opened a PR to "hardcode" the internal port to match what wg-easy is doing.
