### ISSUE TITLE
Provide a template chart

### ISSUE THREAD

**Issue by fire** [truenas/charts#239]
Like a chart that serves a plain html that returns the string truenas allowing the option to use the truenas cert.

**Comment by sonicaj** [comment]
@fire can you please clarify what you would like us to do ? I am not really sure i follow the html bit. Thanks!

**Comment by fire** [comment]
Make a sample chart that shows how to use the wizard.

**Comment by Ornias1993** [comment]
You have multiple charts here that already show multiple ways of doing questions.yaml.
I do agree iX should make a special example questions.yaml with extreme amounts of commenting to highlight how it works.

But a chart itself is a bit too much for something that is basically a single file.

**Comment by stavros-k** [comment]
Hello, considering the change to a new backend for apps (docker), please follow the truenas/apps repo.
Where will be docs available once the core library is stabilized and ready to accept contributions.

Thanks!
