### ISSUE TITLE
Wireguard app does not respect the port in configuration

### ISSUE THREAD

**Issue by MRodneyMcKay** [truenas/charts#2391]
I have tried to setup wireguard to use the already forwarded port (used by previus version of truenas). It failed, i could not get a connection, I had to forward WG's default port to get a connection.
So I would suggest either delete port setup from the app config dialog, or make it work.

**Comment by stavros-k** [comment]
Can you please share your configuration? (screenshots are fine)
Thanks

**Comment by MRodneyMcKay** [comment]
The latest update changed the configuration page of the app/container.
When i reported the issue, there was an another option here, for setting up the port for the network trafic, which was ignored, because the connection would only work if i set up the wireguard default port.
![Beillesztett kép](https://github.com/truenas/charts/assets/60845221/75125c5c-8254-4f9f-be1a-da6191a89eca)

**Comment by stavros-k** [comment]
Okay, yea I've made the change after I saw your issue, just wanted to verify that you were using hostNetwork.
In which case the port field as you mentioned does not do anything. (it only takes effect on non-hostNet)

I'm closing this one now

Thanks for the report!
