### ISSUE TITLE
Minecraft 2024.4.1

### ISSUE THREAD

**Issue by DosWorld** [truenas/charts#2401]
Hello!

%subj% doest not work. Need add jvm 21. Here is log:

`2024-04-23 19:23:40.714531+03:00java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 63.0`

"class file version 65.0)" it is Java**21**,
but max listed (in app props) - Java**19**.

Imho, may be will not be bad add 21 and 22 - all latest avilable.

**App details:**

Name: minecraft
App Version: 2024.4.1
Chart Version: 1.2.9
Last Updated: N/A
Source:
[minecraft.net/en-us](https://www.minecraft.net/en-us)[github.com/truenas/charts/tree/master/community/minecraft](https://github.com/truenas/charts/tree/master/community/minecraft)[github.com/itzg/docker-minecraft-server](https://github.com/itzg/docker-minecraft-server)
Developer: N/A
Catalog: TrueNAS
Train: community

**Comment by istasi** [comment]
https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#image-tags

tags available, seems to mismatch with options presented in ui.
