### ISSUE TITLE
Nextcloud 2.0.5 not rewriting full URL

### ISSUE THREAD

**Issue by alvaroemtnez** [truenas/charts#2456]
Hello!

I realised this morning that after the update to 2.0.4, I couldn't access the web interface, but all the apps worked fine. I rolled back to 2.0.3 and that completely broke my nextcloud installation (so it looks like I'm gonna have a pretty interesting weekend now).

Now I'm reinstalling everything (this time it's version 2.0.5) and the same thing happened. I saw in the closed issues a similar problem so I wrote "/index.php/apps/files/files" after my FQDN and everything seems to be working fine. It rewrites it as "/login?redirect_url=/index.php/apps/files/files" and prompts me to log in (as it should be).

Running "occ maintenance:update:htaccess" in the container shell didn't solve it for me.

I'm opening this issue in case that problem wasn't solved in 2.0.4 as it's mentioned in the issue I saw.

**Comment by stavros-k** [comment]
Are you using external reverse proxy?
If yes, Can you try adding additional variable `APACHE_DISABLE_REWRITE_IP` with value `1` and then run `occ maintenance:update:htaccess` again?

**Comment by alvaroemtnez** [comment]
No, I'm using the stock NGINX that comes in the chart. I just select my own certificate and deploy.

I've done a clean reinstall three times, the only config I'm adding is the admin account and passw, my fqdn and port in "host" (like FQDN:PORT, nothing else), I change cron jobs to be executed every 5 mins instead of 15 (*/5 * * * *), the web port (the same one I put in "host") and my certificate, and the hosts paths to html, data, pgData and pgBackups datasets, which I newly created with the TrueNAS WebUI with the "Apps" preset. 

Nothing else, it's a fully clean install, I've always removed the previous one using heavyscript and deleting all the html, etc datasets using the UI, and I even check in the terminal that everything has been deleted before installing. And I'm always getting the same problem: the URL is not rewritten, which causes apps to not be able to sign in (I have to as it's a new install), and also in the admin tab there's a warning reading something like "_Some headers are not set correctly on your instance - The `X-Robots......_" (it's really long).

After three clean reinstalls (two as I wrote and one only selecting a host path for data and leaving ix-volumes for html and postgres) I gave up. I'll try again when it's updated or might look for another solution not using charts, as having unstable updates in a system that should be only updated when it's rock-solid is extremely inconvenient for my use case, especially if rolling back breaks everything (and I rolled back from 2.0.4 to 2.0.3, not a major upgrade). I even tried installing a clean instance of 1.6 (the lastest one) and it's not deploying, and the UI is not letting me install 2.0.3, which worked perfectly fine for me after I manually corrected the trusted_proxies thing.

**Comment by stavros-k** [comment]
Can you please remove the `:port` from the host field?

Also if the external port you are accessing nextcloud is different than then webPort, also "tick" the Use different external port, and put the external port there.

**Comment by alvaroemtnez** [comment]
Hi again!
Sorry, I didn't know it would be that obvious. I was using the same configuration that worked for me in the previous versions and the "Use different port for URL rewrites" setting never gave me any issues (as the web port I'm using is the same as the external access one). My ISP blocks port 443 (and I prefer using non-standard ports in general). It's weird that it worked perfectly for me in 2.0.3 without that setting checked.
Now everything seems to be working flawlessly! Thanks a lot :)

**Comment by stavros-k** [comment]
Awesome!
