### ISSUE TITLE
Nextcloud 2.0.5 not able to access the database

### ISSUE THREAD

**Issue by Rami-Pastrami** [truenas/charts#2457]
I updated truenas / nextcloud for the first time in a while, I also moved the directory of the database (to an SSD). Am currently on the latest stable Truenas and Nextcloud 29.0.0_2.0.5

Currently, nextcloud gets stuck at deploying 2/3.

The overview logs show this
![image](https://github.com/truenas/charts/assets/25966197/6064d6ed-1502-49f3-8f13-b88a932067b1)

The redis and postgres container logs show that they started fine and are awaiting connections
Of note is the nextcloud container itself, which shows this:
![image](https://github.com/truenas/charts/assets/25966197/c921be71-8993-415e-b8ca-b95c1d6f9d25)

In addition, the nextcloud log would spam this line
```
{"reqId":"ARGbaYSUYiSFsiJVjr0W","level":3,"time":"2024-05-10T19:53:00+00:00","remoteAddr":"172.16.0.1","user":"--","app":"remote","method":"GET","url":"/status.php","message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name \"nextcloud-postgres\" to address: Name or service not known","userAgent":"kube-probe/1.25","version":"28.0.4.1","exception":{"Exception":"Doctrine\\DBAL\\Exception","Message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name \"nextcloud-postgres\" to address: Name or service not known","Code":7,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":453,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":411,"function":"getDatabasePlatformVersion","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":318,"function":"detectDatabasePlatform","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/ConnectionAdapter.php","line":200,"function":"getDatabasePlatform","class":"Doctrine\\DBAL\\Connection","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":121,"function":"getDatabasePlatform","class":"OC\\DB\\ConnectionAdapter","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":1237,"function":"expr","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppConfig.php","line":262,"function":"loadConfig","class":"OC\\AppConfig","type":"->","args":[false]},{"file":"/var/www/html/lib/private/AppConfig.php","line":1378,"function":"searchValues","class":"OC\\AppConfig","type":"->","args":["enabled"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":131,"function":"getValues","class":"OC\\AppConfig","type":"->","args":[false,"enabled"]},{"file":"/var/www/html/lib/private/App/AppManager.php","line":152,"function":"getInstalledAppsValues","class":"OC\\App\\AppManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":234,"function":"getInstalledApps","class":"OC\\App\\AppManager","type":"->","args":[]},{"file":"/var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"getEnabledApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/lib/base.php","line":706,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->","args":[]},{"file":"/var/www/html/lib/base.php","line":1181,"function":"init","class":"OC","type":"::","args":[]},{"file":"/var/www/html/status.php","line":39,"args":["/var/www/html/lib/base.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/DB/Connection.php","Line":155,"message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name \"nextcloud-postgres\" to address: Name or service not known","exception":{},"CustomMessage":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name \"nextcloud-postgres\" to address: Name or service not known"}}
```

Sounds like it is failing to connect to the database container? but it spins up correctly

Let me know if further detail is needed

Thanks!

**Comment by stavros-k** [comment]
Please share the output of
(replace `nextcloud` with the name you have to your app)

```
k3s kubectl get pods -n ix-nextcloud
```

Also share the `config.php` contents (redact any private info)

And finally, do you have any DNS Options defined the TrueNAS -> Nextcloud -> Edit screen?

**Comment by Rami-Pastrami** [comment]
> k3s kubectl get pods -n ix-nextcloud

![image](https://github.com/truenas/charts/assets/25966197/56582ef1-1551-48f9-9c8c-1e71584827f5)

Nothing set for the DNS config (under advanced pod configuration)

as for the config.php:
`
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'passwordsalt' => '[retracted]',
  'secret' => '[retracted]',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '[retracted-domain1]',
    2 => '[retracted-domain2]',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '28.0.4.1',
  'overwrite.cli.url' => 'http://localhost',
  'overwriteprotocol' => 'https',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-postgres:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_rimadmin',
  'dbpassword' => '[retracted]',
  'installed' => true,
  'instanceid' => 'oc5j1j95k1ne',
  'mail_from_address' => 'server',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '[retracted]',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '[retracted]',
  'mail_smtpport' => '1025',
  'mail_smtpname' => '[retracted]',
  'mail_smtppassword' => '[retracted]',
  'maintenance' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'loglevel' => 0,
  'app_install_overwrite' => 
  array (
    0 => 'sharingpath',
  ),
);
`

**Comment by stavros-k** [comment]
Thanks for the info and sorry for the delay.

Can you also share this output?

```sh
k3s kubectl get svc -n ix-nextcloud
```

**Comment by Rami-Pastrami** [comment]
![image](https://github.com/truenas/charts/assets/25966197/39843923-92dd-4400-9420-e73e3efe53c0)

**Comment by stavros-k** [comment]
Update the config.php file to show this:

```php
  'dbname' => 'nextcloud',
  'dbhost' => 'ramicloud-nextcloud-postgres:5432',
  'dbport' => '',
```

(only the `dbhost` changes)
If you upgraded from v1.6.1 -> 2.x.x, please also make sure the `Pre v2 storage structure` is selected in the Nextcloud storage section 
(TrueNAS -> Apps -> Nextcloud -> edit)

**Comment by Rami-Pastrami** [comment]
That seems to have worked, upgraded to nextcloud 29 and things are running.

Thanks!
