### ISSUE TITLE
Transmission - settings are resetting

### ISSUE THREAD

**Issue by dangreen** [truenas/charts#2459]
Hi. Every time when i'm restarting container with transmission,  transmission settings are resetting to defaults. Why?

Also link to env variables in docs is not working:

https://github.com/truenas/charts/blob/master/library/ix-dev/community/transmission/README.md

https://github.com/onedr0p/containers/tree/main/apps/transmission - 404

**Comment by stavros-k** [comment]
Hello, settings from webui do not persist, it should be configured with env variables.
I just noticed that this container is deprecated, so I'll have to look for an alternative.

For now, please see this page https://github.com/onedr0p/containers/blob/b4601dc9bccb261a8518d503b15f802149f947f3/apps/transmission/README.md

Thanks

**Comment by dangreen** [comment]
@stavros-k Thanks for response

> settings from webui do not persist

It is very strange and not obvious, don't you think? When I'm using other apps (Jellyfin, File manager, ...) their settings from web ui are persist.

> I just noticed that this container is deprecated, so I'll have to look for an alternative.

I hope that you will find new image that doesn't have issue like that.
