### ISSUE TITLE
New install of Nextcloud 2.0.5 not able to access the database

### ISSUE THREAD

**Issue by Danit2** [truenas/charts#2460]
I try to install a fresh installation of nextcloud. But it doesn't work.
Nextcloud can not acces to the database.
Also not when i enter everything manually.

![image](https://github.com/truenas/charts/assets/71522810/0dbd8e81-5f52-4e63-aef9-818756bbc51d)
![image](https://github.com/truenas/charts/assets/71522810/8cc47ef3-2e90-409a-bdff-911f3c27cb6b)
![image](https://github.com/truenas/charts/assets/71522810/b12c3983-eb05-465e-8f0f-66f33b7a653b)
![image](https://github.com/truenas/charts/assets/71522810/65061793-1067-40dc-ae93-5c548bc6c561)

**Comment by Danit2** [comment]
OK.....
After i have deleted everything again.
Including the storage folder everything is working now.

So only delete the app is not enough

**Comment by stavros-k** [comment]
Yes, deleting the app does not delete HostPaths (only ixVolumes)

The database details are not the ones that Nextcloud uses, (below there should be a note that Nextcloud generates its own user/password for database, and uses those).

I'll close this for now, let me know if you need anything else!
Thanks!
