### ISSUE TITLE
Jellyfin app doesn't take into account "Additional Environment Variables"

### ISSUE THREAD

**Issue by dgeng** [truenas/charts#2485]
### Testing conditions:

- TrueNAS Scale 24.04
- Chart Version: 1.2.8, 1.2.9, 1.2.10

### Steps to reproduce:

1. Install app Jellyfin.
2. In the section "Additional Environment Variables", click "Add", use "foo" as Name, and "bar" as value.
3. Open "Shell" to the container, type "echo $foo".

**Expected result:**
bar

**Actual result:**
Emtpy

**Comment by dgeng** [comment]
This patch should fix it.

`git diff
diff --git a/community/jellyfin/1.2.10/templates/_jellyfin.tpl b/community/jellyfin/1.2.10/templates/_jellyfin.tpl
index 9501af997..48bad9bbc 100644
--- a/community/jellyfin/1.2.10/templates/_jellyfin.tpl
+++ b/community/jellyfin/1.2.10/templates/_jellyfin.tpl
@@ -22,7 +22,7 @@ workload:
           envList:
             {{ range $env := . }}
             - name: {{ $env.name }}
-              values: {{ $env.value }}
+              value: {{ $env.value }}
             {{ end }}
           {{ end }}
           probes:
`

**Comment by dgeng** [comment]
These *.tpl files seem to have the same issue:
```
community/jenkins/1.2.9/templates/_jenkins.tpl
28:              values: {{ $env.value }}

library/ix-dev/community/jenkins/templates/_jenkins.tpl
28:              values: {{ $env.value }}

library/ix-dev/community/jellyfin/templates/_jellyfin.tpl
25:              values: {{ $env.value }}

test/jellyfin/1.0.16/templates/_jellyfin.tpl
25:              values: {{ $env.value }}
```

**Comment by stavros-k** [comment]
Nice catch.
Thanks!

**Comment by dgeng** [comment]
Thanks a lot for the quick response.
