### ISSUE TITLE
[Plex] Button "Webportal" does not open the correct path of the Plex web interface

### ISSUE THREAD

**Issue by Fishezzz** [truenas/charts#2493]
When helping a friend of mine today with an issue with his Plex install on Truenas Scale, I found a simple but quite user-unfriendly issue.

If you install Plex as an App on Truenas Scale, without following any official installation guides but just following the App installation steps, Plex installs just fine. But when you click on the butten to open the webportal, it opens [http://\<ip-address>:32400](http://<ip-address>:32400) and displays a page containing some XML.
After some searching I found [this forum post from 2014](https://forums.unraid.net/topic/30196-when-accessing-plex-server-it-shows-quotthis-xml-file-does-not-appear-to-have-any/) with the exact same issue. The solution provided there is to append "/manage", so the webportal URL would/should be [http://\<ip-address>:32400/manage](http://<ip-address>:32400/manage).

If a non-technical user encounters this situation, they might think something is broken (like my friend did), while their installation is just fine and they are just browsing the wrong URL/path.

After looking around in the code/chart a bit, I think I found where this behaviour can be corrected. In [`charts/plex/2.0.6/templates/_portal.tpl`](/truenas/charts/blob/master/charts/plex/2.0.6/templates/_portal.tpl) and [`library/ix-dev/charts/plex/templates/_portal.tpl`](/truenas/charts/blob/master/library/ix-dev/charts/plex/templates/_portal.tpl), the `path` variable in the configmap should be changed to `/manage`

I don't have a Truenas installation and also no Plex installation, so this is solely based on the troubleshooting with my friend. So I'm also not able to test this. He also had Truenas Core before and had no trouble accessing the webportal on that.

**Comment by Fishezzz** [comment]
Apparently when he clicks on the button now, it takes him to the correct location. Without having changed anything. (maybe an automatic update did something?)

But what he saw in the browser initially is almost exactly the same as what jang430 pasted in his forum post that I linked to.

**Comment by Charlie67j** [comment]
I know that this is a closed issue, but I get the same results. When I hit the "Web Portal" button in the Application Info section for Plex, it opens the XML view. When I add the "/web" after the port the Plex app loads fine. I've tested this in Brave, Friefox, and Edge and all behave the same. This has remained the case through every app update.

**Comment by stavros-k** [comment]
> I know that this is a closed issue, but I get the same results. When I hit the "Web Portal" button in the Application Info section for Plex, it opens the XML view. When I add the "/web" after the port the Plex app loads fine. I've tested this in Brave, Friefox, and Edge and all behave the same. This has remained the case through every app update.

It is fixed on the new implementation for TN 24.10
(https://github.com/truenas/apps/blob/637f0a172beef5c9bcc6c110ca8cde4528ce1565/ix-dev/stable/plex/templates/docker-compose.yaml#L80)
