### ISSUE TITLE
Immich not visible through tailscale. No host networking?

### ISSUE THREAD

**Issue by david7a68** [truenas/charts#2494]
Hi!

I just tried to set up immich alongside Tailscale but found that I am not able to access the app through the tailnet. Taking a look at prior issues suggests that it might be the same as #2201? However, my background is insufficient for me to identify the issue beyond that.

**Comment by stavros-k** [comment]
Hello, please test again once you upgrade to TrueNAS Electric Eel (24.10.x).
If you can reproduce, feel free to open a new issue on https://github.com/truenas/apps 

Thanks
