### ISSUE TITLE
hide library charts

### ISSUE THREAD

**Issue by Ornias1993** [truenas/charts#25]
It would be nice to be able to use the CI on library charts, but ignore them from actually being shown in the "Apps" screen.

Current hack I did to hide a library chart from the CI (because the CI is incompatible with Library charts at the moment)::
Put it in the root folder with a dot `.` in front of a folder name in the root of the repository.

However, it would be nice if we would be able to use Library charts from Helm like normal and use the included IX-CI on those, without them being shown as Apps, because it would significantly simplify the workflow.
(for example: Now I had to hack a folder exclusion for the IX-CI, see above, and had to add another CI just for the library charts)

Suggested solution:
Add a special train/folder "libraries", exclude it from the default CI-process and process everything in there differently.

**Comment by Ornias1993** [comment]
Current trick I did to hide a library chart:
Put it in the root folder with a dot `.` in front of the name

**Comment by sonicaj** [comment]
@Ornias1993 can you please clarify `library chart` ? The terminology we have had in mind so far was that the directories in the root folder are `trains` like stable ( which is `chart` ). Can you please confirm if perhaps you are referring to a `library` train ?

**Comment by Ornias1993** [comment]
If you don't know what a library chart is, I think you need a readup on Helm.
No offense intended, but I don't think i'm the best person to explain what a "library chart" is and why you don't want to show those as Apps nor want to run your CI on them.

**Comment by sonicaj** [comment]
Thank you for clarifying @Ornias1993, your original comment did not elaborate it which left me confused as library charts don't have to be at the top level or any specific level for that. Anyways, it's a good suggestion and I think we can certainly make space for this.
