### ISSUE TITLE
Error: [EFAULT] Your TrueNAS system version (24.04.2) is greater than the maximum version (24.04.1) required by this application.

### ISSUE THREAD

**Issue by Diogo-Caires** [truenas/charts#2502]
Can't update my TrueCharts Apps or install new ones -> Everytime I get this error: Error: [EFAULT] Your TrueNAS system version (24.04.2) is greater than the maximum version (24.04.1) required by this application.

**Comment by stavros-k** [comment]
Hello, this is a restriction put by TrueCharts.
You can follow their support channels.

Thanks
