### ISSUE TITLE
gitea stuck on "Back-off restarting failed container gitea"

### ISSUE THREAD

**Issue by ccfoo242** [truenas/charts#2525]
Dragonfish-24.04.1.1
New install. Configured hostpaths for  config/data/pgdata/pgbackup. What might I be doing wrong?

 2024-06-01 15:23:16
Back-off restarting failed container gitea in pod gitea-6469db755f-xmzdj_ix-gitea(ca905dea-59e9-414a-95dd-ecb57de2abf8)
2024-06-01 15:23:06
Created container gitea
2024-06-01 15:23:06
Started container gitea
2024-06-01 15:23:05
Container image "gitea/gitea:1.22.0-rootless" already present on machine
2024-06-01 15:22:45
Created container gitea
2024-06-01 15:22:45
Started container gitea
2024-06-01 15:22:44
Created pod: gitea-6469db755f-xmzdj
2024-06-01 15:22:44
Scaled up replica set gitea-6469db755f to 1
2024-06-01 15:22:44
Successfully assigned ix-gitea/gitea-6469db755f-xmzdj to ix-truenas
2024-06-01 15:22:44
Scaled up replica set gitea-postgres-89c9b5568 to 1
2024-06-01 15:22:44
Created pod: gitea-postgres-89c9b5568-825vs
2024-06-01 15:22:44
Successfully assigned ix-gitea/gitea-postgres-89c9b5568-825vs to ix-truenas
2024-06-01 15:22:44
Add eth0 [172.16.0.48/16] from ix-net
2024-06-01 15:22:44
Add eth0 [172.16.0.49/16] from ix-net
2024-06-01 15:22:44
Container image "postgres:15.2" already present on machine
2024-06-01 15:22:44
Container image "postgres:15.2" already present on machine
2024-06-01 15:22:44
Created container gitea-init-postgres-wait
2024-06-01 15:22:44
Started container gitea-init-postgres-wait
2024-06-01 15:18:16
Scaled down replica set gitea-postgres-7d7bb49455 to 0 from 1
2024-06-01 15:18:16
Scaled down replica set gitea-7746855c4b to 0 from 1
2024-06-01 15:18:16
Deleted pod: gitea-postgres-7d7bb49455-dvqxc
2024-06-01 15:18:16
Stopping container gitea
2024-06-01 15:18:16
Deleted pod: gitea-7746855c4b-c57dm
2024-06-01 14:28:54
Back-off restarting failed container gitea in pod gitea-7746855c4b-c57dm_ix-gitea(e1728b25-6e60-426d-82c6-f89b58356f9e)
2024-06-01 14:28:45
Created container gitea
2024-06-01 14:28:45
Started container gitea
2024-06-01 14:28:44
Container image "gitea/gitea:1.22.0-rootless" already present on machine
2024-06-01 14:28:20
Created container gitea-init-postgres-wait
2024-06-01 14:28:20
Started container gitea-init-postgres-wait
2024-06-01 14:28:20
Created container gitea
2024-06-01 14:28:20
Started container gitea
2024-06-01 14:28:19
Add eth0 [172.16.0.42/16] from ix-net
2024-06-01 14:28:19
Add eth0 [172.16.0.43/16] from ix-net
2024-06-01 14:28:19
Container image "bash:4.4.23" already present on machine
2024-06-01 14:28:19
Container image "bash:4.4.23" already present on machine
2024-06-01 14:28:19
Created container gitea-install-01-permissions
2024-06-01 14:28:19
Started container gitea-install-01-permissions
2024-06-01 14:28:19
Created container gitea-install-permissions
2024-06-01 14:28:19
Started container gitea-install-permissions
2024-06-01 14:28:19
Container image "postgres:15.2" already present on machine
2024-06-01 14:28:19
Container image "postgres:15.2" already present on machine
2024-06-01 14:28:18
Scaled up replica set gitea-postgres-7d7bb49455 to 1
2024-06-01 14:28:18
Scaled up replica set gitea-7746855c4b to 1
2024-06-01 14:28:18
Created pod: gitea-postgres-7d7bb49455-dvqxc
2024-06-01 14:28:18
Created pod: gitea-7746855c4b-c57dm
2024-06-01 14:28:18
Successfully assigned ix-gitea/gitea-postgres-7d7bb49455-dvqxc to ix-truenas
2024-06-01 14:28:18
Successfully assigned ix-gitea/gitea-7746855c4b-c57dm to ix-truenas

**Comment by stavros-k** [comment]
Please check the logs all the gitea containers.
If you set up hostPaths yourself, it might be an issue with permissions. 
Logs should indicate that.

Thanks

**Comment by ccfoo242** [comment]
Yeah it was permissions, mkdir: can't create directory '/var/lib/gitea/git': Permission denied
Any idea what the permissions should be? When I created the dataset I just used the "Apps" preset.
```
    targetSelector:
      gitea:
        gitea:
          mountPath: /var/lib/gitea
        {{- if and (eq .Values.giteaStorage.data.type "ixVolume")
                  (not (.Values.giteaStorage.data.ixVolumeConfig | default dict).aclEnable) }}
        01-permissions:
          mountPath: /mnt/directories/data
        {{- end }}
```

**Comment by ccfoo242** [comment]
Ok I got it installed. Not sure if this was correct: created git user and group on truenas with uid and gid of 1000 and gave the user full control over the datasets. Ended up using ix volume for postgres data and backup. When I got to the initial setup page it complained about the gitea user for postgres, so I went back and switched it to the ix volume.

**Comment by stavros-k** [comment]
You don't "need" to create a `git` user on the host. (It doesn't hurt either)
Giving access to `1000:1000` is enough.

The plan was to expose fields for choosing the user when you installing but due to a bug that gitea had/has (`https://github.com/go-gitea/gitea/issues/23632`) fields remained hidden.

But it should have been probably locked instead
https://github.com/truenas/charts/blob/3858f5f2f3a11cd43d8f9c1d4b5b2571d6565b25/library/ix-dev/community/gitea/questions.yaml#L54-L83

As for the postgres, you need `999:999` permissions. 

Glad it's working for you now.
Will close this one.

Thanks!

**Comment by ViniAman01** [comment]
how i can give access to 1000:1000?
