### ISSUE TITLE
Tailscale App Stuck Deploying After Update On 2 Separate Scale Systems

### ISSUE THREAD

**Issue by swiney89** [truenas/charts#2539]
I have two separate Truenas Scale systems I replicate on using Tailscale.  Today I updated both of the tailscale apps and now neither of them will launch.  they are stuck at deploying.

I see another user has reported this already, but I figured I'd report mine individually to bring awareness to this.

On both machines, this is the log that repeats.

 2024-06-05 14:16:21
Back-off restarting failed container tailscale in pod tailscale-5ff797b5b-72qtx_ix-tailscale(cc28f141-d00b-4cfe-8964-9e6351cda2de)
2024-06-05 14:16:06
Created container tailscale
2024-06-05 14:16:06
Started container tailscale
2024-06-05 14:16:05
Container image "tailscale/tailscale:v1.66.4" already present on machine
2024-06-05 14:16:04
Scaled up replica set tailscale-5ff797b5b to 1
2024-06-05 14:16:04
Created pod: tailscale-5ff797b5b-72qtx
2024-06-05 14:16:04
Successfully assigned ix-tailscale/tailscale-5ff797b5b-72qtx to ix-truenas
2024-06-05 14:15:23
Scaled down replica set tailscale-6c856df87d to 0 from 1
2024-06-05 14:15:23
Deleted pod: tailscale-6c856df87d-wtdls

**Comment by swiney89** [comment]
I have grabbed debug files.  I'm just not sure where to upload them.

**Comment by swiney89** [comment]
[NAS1log.txt](https://github.com/user-attachments/files/15595810/NAS1log.txt)
[NAS2log.txt](https://github.com/user-attachments/files/15595811/NAS2log.txt)

**Comment by swiney89** [comment]
[NAS1log.txt](https://github.com/user-attachments/files/15595938/NAS1log.txt)
[NAS2log.txt](https://github.com/user-attachments/files/15595940/NAS2log.txt)

**Comment by stavros-k** [comment]
Hello, it **seems** there is an issue from the tailscale side, but the "workaround" is here
https://github.com/truenas/charts/issues/2534#issuecomment-2149526483

You need to add the `--reset` arg and it should be ok

**Comment by swiney89** [comment]
Hi,
I added --reset to both systems, restarted the app, and they both connected.  I then went back in and removed the --reset and they still work normally.  

this seems to have resolved the problem on both machines.  

thanks!

**Comment by stavros-k** [comment]
It might get stuck on the next stop/start/reboot.
A more permanent solution is to check the "Auth Once" (it should be available on version 1.0.41)
