### ISSUE TITLE
1.0.41 Tailscale default value mismatch

### ISSUE THREAD

**Issue by leebickmtu** [truenas/charts#2548]
As I took a look at the changes from 1.0.40 --> 1.0.41 I saw the new authOnce param has a mismatched boolean value between what the default is as specified in questions.yaml (`false`) and what's specified in ix_values.yaml (`true`).

Maybe that's normal and ok, I'm not knowledgeable on how those 2 files interact. But it just stood out to me as odd since all the other params appear to have matching values in those 2 files. Seems unclear what the value will end up being. So just raising the issue here in case it's a mistake.

**Comment by stavros-k** [comment]
Hey, yea I was going to set it true by default. As this would be the most used way for that option.
But I ended up keeping the tailscale default.

That being said, questions.yaml will override any options in ix_values.yaml.
So whatever is picked from the UI will be the one that's used.

**Comment by leebickmtu** [comment]
Ok, sounds good then. Just wanted to make sure.
