### ISSUE TITLE
Update QBittorrent

### ISSUE THREAD

**Issue by Kapppa** [truenas/charts#2552]
The version that is listed is 4.5.2 but 4.6.5 which has had a major improvement to the webui which is very relevant to a server app. If it could be updated that would be great. 

See https://hub.docker.com/r/linuxserver/qbittorrent/tags?page=1&page_size=&ordering=&name=4.6.5

**Comment by stavros-k** [comment]
Hello, can you clarify where you see 4.5.2 version?

I just checked the catalog and installed it
![image](https://github.com/truenas/charts/assets/47820033/aaf5b6e2-a8b0-40b2-bfee-c95d2eb4bad3)
![image](https://github.com/truenas/charts/assets/47820033/b1d276ec-28af-4ce4-b899-586555ebac06)


Thanks

**Comment by stavros-k** [comment]
I'll close this one now, but if you still have issue, feel free to reply.
Thanks

**Comment by Kapppa** [comment]
It seems like I am on the old train of charts not community. Is there a guide to update to the new train?

**Comment by stavros-k** [comment]
Please share a screenshot, I don't remember qbit being in another train ever

**Comment by Kapppa** [comment]
> Please share a screenshot, I don't remember qbit being in another train ever

![brave_4T87pADrmh](https://github.com/truenas/charts/assets/17926797/40ba717e-3e49-44e2-83cd-f4ba34fa2131)

**Comment by Kapppa** [comment]
I also asked you to update last year, when the 4.5.2 dropped. https://github.com/truenas/charts/issues/1008

**Comment by stavros-k** [comment]
I see, I didn't even remember that qbit was ever at charts train.
There isn't a way to upgrade an app cross-train. You will have to re-install it.
