### ISSUE TITLE
Issue with jellyfin

### ISSUE THREAD

**Issue by LeDiamantRouge** [truenas/charts#2553]
I have install jellyfin and I have setup it, after I have delete it because I didn't need it...

Today I have install jellyfin again and all start normally I can access the web page but when I try to access on the server I got an error. I don't have any error I the console or in the app log. I have try to delete "ixApp" but that not work...

Every time I reinstall I get back the old jellyfin server which doesn't work, so if anyone knows how to reinstall jellyfin from scratch?

Thanks !

**Comment by stavros-k** [comment]
Can you please share what "error" did you got?

Also please share your configuration and the app logs.

Thanks

**Comment by LeDiamantRouge** [comment]
I don't have any error just the server don't start and when i'm on the jellyfin page and i try to logon the server I have an error because the server is not started...

**Comment by stavros-k** [comment]
Sounds like a browser cache issue.
But I can't say for sure without app logs and your configuration.
