### ISSUE TITLE
syncthing update: path contains data

### ISSUE THREAD

**Issue by bchevreau** [truenas/charts#2557]
I am attempting to update the Syncthing app (Truenas official version) but I am met with the error below. I am worried it might be related to how I set up my sync folder, and would like to be sure I am not deleting anything in the process. Is that a possible outcome?

If not, where should I add the “force” argument that the error is suggesting?

Thanks in advance.

`Error: [EINVAL] chart_release_create.syncthingStorage.additionalStorages.0.hostPathConfig.acl: /mnt/HomeTank/MainTank/sync: path contains existing data and force was not specified`

**Comment by stavros-k** [comment]
Hello, what version of TrueNAS SCALE are you running?

Thanks
