### ISSUE TITLE
Truenas Scale Charts should be able to use unmodified helm3 charts

### ISSUE THREAD

**Issue by fire** [truenas/charts#258]
## Context and Problem Statement

It would help development if one can import helm3 charts for kubernetes directly into truenas scale's charts as is.

## Describe the proposed option and how it helps to overcome the problem or limitation

We should be able to run helm3 charts in a degraded state.

## Describe how your proposal will work, with code, pseudo-code, mock-ups, or diagrams

Auto import the Truenas Scale standard library?

Give defaults to the wizard?

## Positive Consequences 

- Accessible to the universe of helm3 charts.

## Negative Consequences 

- Engineering effort
- Lack of product lock-in

## Option graveyard: 

- Option: Include the https://github.com/truenas/charts/tree/master/library/common library manually 
- Rejection Reason: This is a modified upstream helm chart and causes drift in configuration.

## If this enhancement will not be used often, can it be worked around with a few lines of script?

Not merely a few lines of logic.

## Is there a reason why this should be core and done by us?

Truenas Scale is a k3s kubernetes system and yet it is not.

## References 

- https://github.com/truenas/charts

**Comment by sonicaj** [comment]
@fire to clarify, are you saying that you want the ability to consume any helm chart via UI ?

**Comment by fire** [comment]
Yes consuming any helm chart would be ideal. I thought about how to provide a UI config for external helm charts but don’t have a design.

**Comment by sonicaj** [comment]
We don't support that as we expect a certain format to be defined which we can use to dynamically generate the UI and validate schema. However please feel free to create a suggestion ticket at https://jira.ixsystems.com outlining how you think it should work and we can then move from there. Thanks!

**Comment by fire** [comment]
I am not sure how creating a ticket in jira will help. I prefer to work in the open, but thanks for the request.
