### ISSUE TITLE
Community Chart Suggestion: flaresolverr

### ISSUE THREAD

**Issue by vendeesign** [truenas/charts#2619]
Hello, Can you add flaresolverr
https://github.com/FlareSolverr/FlareSolverr

**Comment by stavros-k** [comment]
Duplicate of #2591

**Comment by vendeesign** [comment]
Ok duplicate, but when will it be available? With the MAJ of truecharts, we can no longer install the latest version. Thanks a lot

**Comment by stavros-k** [comment]
You can subscribe to the linked issue if you’d like to get notified for any progress when it’s made. Thanks
