### ISSUE TITLE
Paperless-ngx - Only admin user can log in.

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/charts#2623]
Since updating the chart to version 1.2.43 a normal user cannot log in anymore, only the admin user can log in.

Attempting to log in with a regular user will get stuck on "paperless-ngx is loading" and eventually a message that says "Still here?! Hmm, something might be wrong. Here's a link to the docs."

The pod log shows an error 

`2024-06-28 21:14:01.634903+02:00[2024-06-28 21:14:01,634] [WARNING] [django.request] Forbidden: /api/ui_settings/`

It seems to be a known issue Paperless-ngx: https://github.com/paperless-ngx/paperless-ngx/issues/7036#issue-2362585714

**Comment by stavros-k** [comment]
Hello, from the linked issue you posted, I understand that you have to add the `ui_settings` permission to the other users in order to be able to use the UI.

Is there something that we have to fix on our side?

**Comment by TimvanDijkNL** [comment]
Not sure 🤔 Adding `ui_settings` perms fixes the problem, as mentioned in the linked issue. My worry was that it suddenly happened after updating to 1.2.43 hence this issue. In hindsight, does seem to be related to a change within paperless-ngx itself, and not the chart.
