### ISSUE TITLE
Tdarr internal worker crashing with no errors in log

### ISSUE THREAD

**Issue by Casuallynoted** [truenas/charts#2627]
At the moment while using a flow, I'm noticing that the internal Tdarr worker is crashing while GPU transcoding and leaving the media file it's processing in "Processing" status forever, moving on to the next repeatedly while having those workers crash too. Health checks are working properly. I'm using Intel QSV with an Arc GPU encoding to AV1 using a flow. I've tried these same settings using the TrueCharts equivalent of Tdarr previously and it worked correctly.

**Comment by stavros-k** [comment]
Can you please share the logs in order to see if there is any details as to why that might be happening?

Thanks
