### ISSUE TITLE
Paperless-ngx  - add optional tika / gotenberg support

### ISSUE THREAD

**Issue by mEDI-S** [truenas/charts#2635]
Hello,

Is there the possibility to optionally integrate Tika/Gotenberg into the chart so that you can also easily include DOC and DOCX support when needed?

https://docs.paperless-ngx.com/configuration/#tika

I haven't tried it myself yet, but the docker compose seems to want to access the other dockers only through the URL.

https://github.com/paperless-ngx/paperless-ngx/blob/dev/docker/compose/docker-compose.postgres-tika.yml

     PAPERLESS_TIKA_ENABLED: 1
     PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
     PAPERLESS_TIKA_ENDPOINT: http://tika:9998

and therefore it could be possible with little structural changes "untested by me and only an assumption"
but it would be cool if you could simply activate it via a checkbox during the installation or configuration of the app

Best regards

**Comment by stavros-k** [comment]
Please follow https://github.com/truenas/apps/issues/837
Thanks
