### ISSUE TITLE
Vaultwarden, Immich, maybe others as well: Setting postgres backup storage seems to have no effect

### ISSUE THREAD

**Issue by iSOcH** [truenas/charts#2639]
I am new to Truenas, so maybe I am just missing some obvious steps.

I installed vaultwarden and immich from the truenas catalog (not truecharts). When configuring the chart, there is "Vaultwarden Postgres Backup Storage" with hint "The path to store Vaultwarden Postgres Backup.", which I set to a hostpath.

I would have expected to sooner or later find some backups in those directories, but nothing seems to happen. When I checked the underlying `Deployment`s, I was not able to find any mention of my configured hostpaths.

```
$ sudo k3s kubectl -n ix-vaultwarden get all -o yaml | grep "vaultwarden-backup" # my backup path contains "vaultwarden backup"
$
```

In the postgres container there's only a `data` directory mounted for postgres, no backup

```
$ sudo k3s kubectl -n ix-vaultwarden exec deployment.apps/vaultwarden-postgres -- ls -l /var/lib/postgresql/
total 12
drwx------ 19 postgres postgres 26 Jul  7 12:02 data

$ sudo k3s kubectl -n ix-vaultwarden exec deployment.apps/vaultwarden-postgres -- mount | grep postgre
usb/ix-applications/releases/vaultwarden/volumes/ix_volumes/pgData on /var/lib/postgresql/data type zfs **(rw,noatime,xattr,posixacl,casesensitive)**
```

Am I doing something wrong or is there an issue?

**Comment by stavros-k** [comment]
Hello, backups are performed during chart updates only.
The reason you dont see the path in the deployment is because it only appears on the `Job` that is spawned during upgrade.
