### ISSUE TITLE
Suggest adding Jellyfin Service

### ISSUE THREAD

**Issue by chxbw** [truenas/charts#264]
This server is easy and free,it can be accelerated using NVIDIA graphics card,an it is open source
Please adding
Thank ~~

**Comment by chxbw** [comment]
i hope SC and Core both adding 
A good man has a big penis！！！！！！！！once at 18H！！！！！

**Comment by sonicaj** [comment]
@chxbw please create a suggestion ticket at https://jira.ixsystems.com. Thanks!
