### ISSUE TITLE
Home Assistant interface language is messed up

### ISSUE THREAD

**Issue by rewgs** [truenas/charts#2659]
I've tried installing Home Assistant on TrueNas Bluefin, Cobia, and now Dragonfish (v24.04.2), and the result is always the same: the language is either set to something I don't recognize at all, or is just garbled, random letters. Not sure which. The Inspector shows `lang=en`, so I assume it's the latter.

This issue only occurs in Chrome -- both Safari and Firefox are fine.

App settings are 100% stock, and my timezone is set correctly (in my case, `America/Los_Angeles`).

This is what it looks like when entering the web portal:
<img width="661" alt="1" src="https://github.com/user-attachments/assets/2a76ece6-60a7-445d-baec-750feb07f49a">

And this is what it looks like when I click the "Create my smart home" button:
<img width="707" alt="2" src="https://github.com/user-attachments/assets/fb4e094b-d806-42a4-97f2-0cf6adf0fb33">

I proceeded with creating my account in Firefox; I then tried logging in via Chrome, and while my username and password are accepted, they display as garbled (non-English) letters. Once into the main Home Assistant interface, the issue persists in Chrome.

Any ideas?

**Comment by stavros-k** [comment]
Hello, this sounds like an issue of Home Assistant, have you tried reaching their support channels?

Thanks
