### ISSUE TITLE
Nextcloud Memories app requires Postgres 14 minimum

### ISSUE THREAD

**Issue by Emplopi** [truenas/charts#2664]
### Issue:
The popular Nextcloud app "Memories" requires Postgres 14 minimum for filecache triggers. 
The Nextcloud chart is currently bundled with Postgres 13.1.

### Potential fix:
Update Postgres to 14+

### Chart version:
```
Chart version: 2.0.10
Nextcloud version: 29.0.3
```

**Comment by stavros-k** [comment]
Please follow https://github.com/truenas/apps/issues/342.
Closing this one!

Thanks!
