### ISSUE TITLE
minio data directory empty

### ISSUE THREAD

**Issue by martinr92** [truenas/charts#2668]
The `/data` mount is always empty. For any reason everything is stored within the `/export` folder (in my case at `/mnt/sheldon/ix-applications/releases/minio/volumes/ix_volumes/export/`. I configured two mounts:

1. `/export` --> ixVolume (Enable ACL unchecked; Enable Log Search API unchecked)
2. `/data` --> Host Path (Enable ACL unchecked)

Just did the steps mentioned [here](https://www.truenas.com/docs/scale/24.04/scaletutorials/apps/communityapps/minioapp/)

Some details:
- chart version 2.0.9
- Enable Distributed Mode: unchecked

**Comment by stavros-k** [comment]
I think docs needs to be updated.
The default is `/export` and you can change it to `/data` (or something else) during the installation.
Which I just saw that it wasn't working. https://github.com/truenas/charts/pull/2671

**Comment by micjohnson777** [comment]
I've check the docs, do say to set it to /data in the Storage section but it can be more clear in the Configuring MinIO (S3) Community App section of the article. I'll link this PR to a docs ticket. We are going to revamp the apps articles in the next couple of weeks.

**Comment by stavros-k** [comment]
I'll close this one now, docs team have their own ticket tracking the docs update.
Thanks!
