### ISSUE TITLE
Increase Syncthing inotify limit

### ISSUE THREAD

**Issue by jimboolio** [truenas/charts#2685]
Hello!

The inotify setting on Syncthing chart probably could be user configurable, since the sync kind of fails if set too low. The default seems to be 128 and according to the docs it should probably be something like 204800, or on bigger setups even higher: https://docs.syncthing.net/users/faq.html#inotify-limits

The official docs assume that the user is on systemd based distro/container, but since Syncthing container is Alpine -based, probably some kind of an container startup script/addition could be implemented. I'll update this if/when I figure out an workaround.

**Comment by stavros-k** [comment]
Hello, this is something to configure on the host.
You can do so in the `System Settings` -> **Advanced** -> `Sysctl`.
