### ISSUE TITLE
Stuck on Job Waiting for pods to be scaled to 0 replica(s) in TrueNAS

### ISSUE THREAD

**Issue by bial654321** [truenas/charts#2690]
After updating my nextcloud to newest version (App Version: 29.0.4 / Chart Version 2.0.11] it's stuck on job "Waiting for pods to be scaled to 0 replica(s)". I tried reverting the update to the version I had before but it did not work. II have no idea what to change at this point. It won't deploy and I don't have access to my files anymore. Is there a way to bring it all back? Thanks!

![image](https://github.com/user-attachments/assets/13cf4658-29ca-4b0b-bc0c-26f6d8ff57bc)
![image](https://github.com/user-attachments/assets/2a96af29-9cd3-4ffe-84d4-a2a622bc3528)

**Comment by bial654321** [comment]
Or if possible I would like to know if it's possible to retrieve all my data back to my PC

**Comment by bial654321** [comment]
Hey thanks for the reply. I'm sorry to be a burden but I have no idea where to put this command. Do you mean that I connect with ssh for example through linux to the Nextcloud's IP address? If so - connection is refused. I am not able to connect through ssh. Unless there is an option to do it from the TrueNAS itself where I can do that

**Comment by stavros-k** [comment]
Hello, you can run those on the TrueNAS itself!
Either using ssh or the web shell on the menu.

**Comment by bial654321** [comment]
Ok I managed and this is what I got:

**k3s kubectl get pods -n ix-nextcloud**

![image](https://github.com/user-attachments/assets/0a910cf7-fa37-4df1-b3cf-ec69c59aabe0)

**k3s kubectl get jobs -n ix-nextcloud**


![image](https://github.com/user-attachments/assets/8fab0b51-4ba4-4592-ab2b-3c8c63d0f8c3)

**Comment by stavros-k** [comment]
Can you please share output of this
```sh
k3s kubectl logs -n ix-nextcloud --selector pod.name=postgres
```
Thanks

**Comment by bial654321** [comment]
![IMG_20240731_141656](https://github.com/user-attachments/assets/5c1074b8-c63d-4945-a186-f9676ea59873)

**Comment by stavros-k** [comment]
Looks like the permissions on the postgres data directory are not right.

Do you use host path for postgres data?
If yes, you have to make sure the permissions for that directory are `999:999`

**Comment by bial654321** [comment]
I switched postgres backup and data from host path to ixvolume (since I have no idea to which user/group I should give permissions to) and it still doesnt work

![IMG_20240731_145047](https://github.com/user-attachments/assets/6d366240-a525-4419-9a60-e535005f9ff3)

![IMG_20240731_145317](https://github.com/user-attachments/assets/c0d5ce5b-2616-4445-87f1-1acc52bbc2a4)

**Comment by stavros-k** [comment]
... you can't just switch postgres data to another type.
the ixvolume is empty, without postgres data.

Changing type wont move data.

Please switch back to host paths and update permissions
eg on the host you can run something like this. (update with the correct paths)
```
# chown 999:999 /path/to/postgres/data
```

**Comment by bial654321** [comment]
Ok now it says "running" instead of "deploying". Ill let this run for few hours and let you know since i have a lot of data. For now when I go to the NextCloud website it says the site cant be reached

**Comment by stavros-k** [comment]
You can check logs of nextcloud, maybe there are hints on whats wrong.

Either from the UI click the "logs" icon
or 
```
k3s kubectl logs -n ix-nextcloud --selector pod.name=nextcloud
```

**Comment by bial654321** [comment]
![IMG_20240731_151616](https://github.com/user-attachments/assets/946eefb6-e20a-47d4-b490-4171e8d63444)

**Comment by bial654321** [comment]
2024-07-31 15:22:25
Readiness probe failed: HTTP probe failed with statuscode: 502
2024-07-31 15:22:25
Liveness probe failed: HTTP probe failed with statuscode: 502

**Comment by bial654321** [comment]
Ok so i can access the website but I get the same thing like I did last time. Non stop maintenance mode

![IMG_20240731_154409](https://github.com/user-attachments/assets/75e656d6-7760-418c-b2d4-19c342d9b29d)

**Comment by stavros-k** [comment]
Shell in the nextcloud pod/container (there is a button on the UI once you select nextcloud app)

And run
```
occ maintenance:mode --off
```

**Comment by bial654321** [comment]
I think I'm blind because i cant see that

![Screenshot_20240731-161915](https://github.com/user-attachments/assets/9c7d9ac6-8f9b-401a-a1a2-6860add3245b)

**Comment by stavros-k** [comment]
![image](https://github.com/user-attachments/assets/08143189-1d03-41c1-9745-921b5f426c71)

The icon with the `>_` symbol 

Make sure on the popup the nextcloud _pod_ and nextcloud _container_ are selected

**Comment by stavros-k** [comment]
![image](https://github.com/user-attachments/assets/08143189-1d03-41c1-9745-921b5f426c71)

The icon with the `>_` symbol 

Make sure on the popup the nextcloud _pod_ and nextcloud _container_ are selected

**Comment by bial654321** [comment]
This is what I selected

![IMG_20240731_162557](https://github.com/user-attachments/assets/0a608f9e-8302-4b35-82c2-62f9d697bbdd)

And this is what i get

![IMG_20240731_162627](https://github.com/user-attachments/assets/ad99bd31-c65c-466a-9041-5ae0dafcc173)

These are my pod options before selecting: 

![IMG_20240731_162455](https://github.com/user-attachments/assets/a458e486-eac6-440c-bdc2-0a065adc0f44)

**Comment by bial654321** [comment]
When selecting this

![IMG_20240731_163055](https://github.com/user-attachments/assets/3639ec93-dd03-4ead-aa80-a4468735faca)

I get

![IMG_20240731_163117](https://github.com/user-attachments/assets/e422c4a4-6cd0-4a8d-b08f-6ed451e842fd)

**Comment by bial654321** [comment]
> When selecting this
> 
> ![IMG_20240731_163055](https://private-user-images.githubusercontent.com/56353909/353871385-3639ec93-dd03-4ead-aa80-a4468735faca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzY3MjMsIm5iZiI6MTcyMjQzNjQyMywicGF0aCI6Ii81NjM1MzkwOS8zNTM4NzEzODUtMzYzOWVjOTMtZGQwMy00ZWFkLWFhODAtYTQ0Njg3MzVmYWNhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE0MzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMWViZmY0ZDJiMjljMTJiZWI3NDQ5MDhkNmZkNTE1MDkzNzcxMDg5ODc2M2ZlMmE5MzZlZjM5Y2Q2MWMxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wf8ZI1cy2bTAPPCKghQ-48iFMBcUb5NsCNLIqWvC26Q)
> 
> I get
> 
> ![IMG_20240731_163117](https://private-user-images.githubusercontent.com/56353909/353871412-e422c4a4-6cd0-4a8d-b08f-6ed451e842fd.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzY3MjMsIm5iZiI6MTcyMjQzNjQyMywicGF0aCI6Ii81NjM1MzkwOS8zNTM4NzE0MTItZTQyMmM0YTQtNmNkMC00YThkLWIwOGYtNmVkNDUxZTg0MmZkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE0MzM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkMWE1NjQyYzkyNzEyM2VlOTQwODFlNzNjMjhmYTI4NWU1ZjRjMzJkZjc2OGZhZDY3MjY5YWEwMzM0ZDhhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xD31M313B-kRUXVkw_gsySjDOlPKSIW-ttKSE6d7LLs)

Yeah I did here

**Comment by stavros-k** [comment]
Can you try please
```sh
su -p "www-data" -s /bin/bash -c 'php /var/www/html/occ maintenance:mode --off'
```
