### ISSUE TITLE
Add HTTPS Port option to SABnzbd

### ISSUE THREAD

**Issue by bitrage** [truenas/charts#2693]
It seems currently impossible to make use of the "HTTPS Port" inside the SABnzbd advanced config. Could you please expose this option to the app questions?

The option sets the following sabnzbd.ini attributes:

[misc]
https_port = 30060

You could couple it with a enable_https = 1 checkbox.

Thank you!

**Comment by stavros-k** [comment]
Closing for now, feel free to re-open when upstream has added some option.
Thanks!
