### ISSUE TITLE
add pgagent to pgadmin chart

### ISSUE THREAD

**Issue by schmitzkr** [truenas/charts#2695]
It would be useful for automating database backups if pgagent was installed in the pgadmin chart.

**Comment by stavros-k** [comment]
Hello, if the pgAgent is not present on the container, you will have to create a request on the upstream pgAdmin project to include it.

We consume this container https://hub.docker.com/r/dpage/pgadmin4/

**Comment by schmitzkr** [comment]
Thanks for pointing that out!
