### ISSUE TITLE
Pi-hole – Can’t Connect to Network

### ISSUE THREAD

**Issue by epe71** [truenas/charts#2712]
The default installation of Pi-hole is configured to use the eth0 interface, which may not be present on all systems. As a result, the DNS service fails to operate correctly since it cannot connect to the network.

**Environment**
    • TrueNAS Scale: Dragonfish-24.04.2
    • Pi-hole: 2024.07.0

**Steps to Reproduce**
    1. Navigate to Apps > Discover Apps > Search for pihole.
    2. Install Pi-hole. Set the web password and leave the other settings at their default values. Deploy the app.
    3. Once running, log in to the web portal using the previously set password.
    4. Go to Tools > Pi-hole Diagnosis. The following error is displayed: interface eth0 does not currently exist.

**Temporary fix**
    1. Go to Tools > Network to check available interfaces. On my setup, the interface is eno1.
    2. Navigate to the settings page for the Pi-hole app in TrueNAS.
    3. Add an additional environment variable:
        ◦ Name: INTERFACE
        ◦ Value: eno1
    4. Click Update and wait for the app to reload.
    5. Verify that the error in Tools > Pi-hole Diagnosis is resolved.

**Suggestion**
If eno1 is the standard interface on all TrueNAS servers, consider adding this environment variable automatically during installation. It would enhance user experience by ensuring the default installation works out of the box.

**Comment by stavros-k** [comment]
Remember to remove the `INTERFACE` from additional envs before upgrading, and using the new field now to set the value you want.
Thanks

**Comment by epe71** [comment]
Are the problem fixed or is it just moved to a new location? I still can't make a standard installation of PI-hole with getting the error. If you set the default value for the new field to "eno1" it will work.

**Comment by stavros-k** [comment]
The new field defaults to empty, for backwards compatibility.
So you still need to set the value, but under the designated field, instead of using "additional variables"
