### ISSUE TITLE
WireGuard Update NEED

### ISSUE THREAD

**Issue by Freebase394** [truenas/charts#2718]
Hi there! 

There is a simple fix. 
The official repo  of this for Tre NAS CHARTS is in Read Only now! --> https://github.com/WeeJeWel/wg-easy

But there are more updates on the official repo : https://github.com/wg-easy/wg-easy
![image](https://github.com/user-attachments/assets/b9481325-3ab4-4ad1-b00b-302b17d9916b)

**Comment by stavros-k** [comment]
I'm not sure what `Read Only` means here, but updates are still rolling out for charts.
Specifically wg is being updated here. https://github.com/truenas/charts/pull/2723
