### ISSUE TITLE
DDNS-Updater deployment missing Route53 in dropdown

### ISSUE THREAD

**Issue by polarbe4r1** [truenas/charts#2720]
As title suggests, when installing/deploying ddns-updater on truenas scale (apps) there is no drop down (Provider) for route-53.

![image](https://github.com/user-attachments/assets/76560a44-8506-4b4b-b07d-3742450fca3b)

Go to Apps 
find ddns-updater and click on install.
Next to DNS Provider Configuration click Add
Click the Drop down for providers.

Not sure if this was ever available. I am new to truenas scale.

Thank you for your hard work!!

**Comment by stavros-k** [comment]
I see that ddns-updater only recently added R53 on the supported list.

**Comment by polarbe4r1** [comment]
Thank you good sir!

**Comment by joshu111** [comment]
Was AWS route53 provider removed?
