### ISSUE TITLE
"Install Applications" should query currently assigned ports

### ISSUE THREAD

**Issue by SamPlaysKeys** [truenas/charts#2732]
When a custom port is entered for a prebuilt application install, or for a custom application, TrueNAS should query ports currently assigned to other applications, as well as ports in use by the host, and put an error notice below the textbox. The result would visually be similar to the notice when assigning a port outside of the port range, but would help when setting up several applications, or when accidentally setting up conflicting applications.

If this is in the realm of what would be wanted for the page, I would be happy to contribute some time to the project to make this a reality.

**Comment by stavros-k** [comment]
Hello, this is already done in the new apps implementation available currently on BETA channels of 24.10!
