### ISSUE TITLE
Immich - set additional environment variables

### ISSUE THREAD

**Issue by tjhorner** [truenas/charts#2739]
Unlike other TrueNAS charts, the Immich chart does not allow the user to set additional environment variables for any of the containers. It would be nice to be able to set arbitrary env vars.

**Comment by stavros-k** [comment]
This should be working on the new apps on Electric Eel. I'll close this for now.
Thanks!

**Comment by tjhorner** [comment]
I'm a bit confused - what do you mean? Electric Eel is not stable yet, so it would make sense to patch this chart in the meantime.

**Comment by stavros-k** [comment]
Currently all efforts are towards migrating the backends.
This change would require changes in both sides and on the migrations.
PRs are welcome, but its not currently the priority.

Thanks

**Comment by tjhorner** [comment]
Ok, got it! Thanks for the clarification. As an aside, where is all the work for the migration being done? I'm interested to see what the approach is there.

**Comment by stavros-k** [comment]
https://github.com/truenas/apps
