### ISSUE TITLE
Home assistant app (official catalog) not deploying (postgres initdb stuck)

### ISSUE THREAD

**Issue by Divaaaaaan** [truenas/charts#2744]
Hi, getting the following when trying to deploy HA through the offical chart catalog. I've tried searching for the directories mentioned but no luck. 

I've also opened up the permissions on the dataset for testing but still no resolution. I doubt it's a permission issue but just pasting for more information

![image](https://github.com/user-attachments/assets/f59ed719-b14a-4d08-a349-61f803cd8909)

```2024-08-19 06:31:05.359545-07:00The files belonging to this database system will be owned by user "postgres".
2024-08-19 06:31:05.359628-07:00This user must also own the server process.
2024-08-19 06:31:05.359652-07:002024-08-19T06:31:05.359652850-07:00
2024-08-19 06:31:05.359691-07:00The database cluster will be initialized with locale "en_US.utf8".
2024-08-19 06:31:05.359713-07:00The default database encoding has accordingly been set to "UTF8".
2024-08-19 06:31:05.359732-07:00The default text search configuration will be set to "english".
2024-08-19 06:31:05.359767-07:002024-08-19T06:31:05.359767306-07:00
2024-08-19 06:31:05.359790-07:00Data page checksums are disabled.
2024-08-19 06:31:05.359814-07:002024-08-19T06:31:05.359814014-07:00
2024-08-19 06:31:05.359743-07:00initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
2024-08-19 06:31:05.359853-07:00If you want to create a new database system, either remove or empty
2024-08-19 06:31:05.359873-07:00the directory "/var/lib/postgresql/data" or run initdb
2024-08-19 06:31:05.359904-07:00with an argument other than "/var/lib/postgresql/data".```

**Comment by Divaaaaaan** [comment]
Installed truenas about 2 weeks ago, played around with the other apps then decided to try install home assistant, got this issue and left it for a few days then tried again. Removed the app, dataset, created both again, removed the containers but still no luck. Not sure what is using the postgres db from the other apps

**Comment by stavros-k** [comment]
Can you open truenas shell and run

```
sudo k3s kubectl get pods -A
```
Thanks

**Comment by Divaaaaaan** [comment]
@stavros-k I'll have a quick look for any other logs but here is the output from the command.

```
NAMESPACE                NAME                                          READY   STATUS      RESTARTS        AGE
kube-system              csi-nfs-controller-7b74694749-ms2h4           0/4     Error       0               5d12h
kube-system              csi-smb-controller-7fbbb8fb6f-4x86h           0/3     Error       0               5d12h
kube-system              csi-smb-node-x55wg                            3/3     Running     3 (4d22h ago)   5d12h
kube-system              csi-nfs-node-2qmfh                            3/3     Running     6 (4d22h ago)   5d20h
kube-system              amdgpu-device-plugin-daemonset-fqchb          1/1     Running     0               4d22h
kube-system              snapshot-controller-546868dfb4-fw2gr          0/1     Error       0               5d12h
kube-system              coredns-59b4f5bbd5-8tf2g                      0/1     Completed   0               5d12h
kube-system              csi-smb-controller-7fbbb8fb6f-fzndd           3/3     Running     0               4d22h
kube-system              snapshot-controller-546868dfb4-7gktc          1/1     Running     0               4d22h
kube-system              csi-nfs-controller-7b74694749-kgwgg           4/4     Running     0               4d22h
kube-system              snapshot-controller-546868dfb4-vh62d          0/1     Error       0               5d12h
kube-system              coredns-59b4f5bbd5-jkz7h                      1/1     Running     0               4d22h
kube-system              snapshot-controller-546868dfb4-kvn5p          1/1     Running     0               4d22h
ix-ad-guard-home         ad-guard-home-adguard-home-5d95f68cb4-4bdj8   1/1     Running     0               4d22h
ix-nginx-proxy-manager   nginx-proxy-manager-7bd798df4-g4mn6           1/1     Running     0               4d22h
ix-qbittorrent           qbittorrent-5b6567d696-l5tjc                  1/1     Running     0               4d12h
ix-file-browser          file-browser-filebrowser-66c64d5bd8-97mb7     1/1     Running     0               3d20h
ix-prowlarr              prowlarr-67cb488c64-j58cr                     1/1     Running     0               2d22h
ix-flare-solverr         flare-solverr-ix-chart-749bccbdcd-p2s6m       1/1     Running     0               2d21h
ix-sabnzbd               sabnzbd-6fd667cdf4-5lpjj                      1/1     Running     1 (44h ago)     44h
ix-radarr                radarr-56c9d6fd7c-7cwmc                       1/1     Running     0               28h
ix-sonarr                sonarr-6bf4c7b9cf-6rllg                       1/1     Running     0               28h
ix-plex                  plex-59d9fbdd64-cmj75                         1/1     Running     0               24h
```

**Comment by stavros-k** [comment]
> @stavros-k I'll have a quick look for any other logs but here is the output from the command.
> 
> ```
> NAMESPACE                NAME                                          READY   STATUS      RESTARTS        AGE
> kube-system              csi-nfs-controller-7b74694749-ms2h4           0/4     Error       0               5d12h
> kube-system              csi-smb-controller-7fbbb8fb6f-4x86h           0/3     Error       0               5d12h
> kube-system              csi-smb-node-x55wg                            3/3     Running     3 (4d22h ago)   5d12h
> kube-system              csi-nfs-node-2qmfh                            3/3     Running     6 (4d22h ago)   5d20h
> kube-system              amdgpu-device-plugin-daemonset-fqchb          1/1     Running     0               4d22h
> kube-system              snapshot-controller-546868dfb4-fw2gr          0/1     Error       0               5d12h
> kube-system              coredns-59b4f5bbd5-8tf2g                      0/1     Completed   0               5d12h
> kube-system              csi-smb-controller-7fbbb8fb6f-fzndd           3/3     Running     0               4d22h
> kube-system              snapshot-controller-546868dfb4-7gktc          1/1     Running     0               4d22h
> kube-system              csi-nfs-controller-7b74694749-kgwgg           4/4     Running     0               4d22h
> kube-system              snapshot-controller-546868dfb4-vh62d          0/1     Error       0               5d12h
> kube-system              coredns-59b4f5bbd5-jkz7h                      1/1     Running     0               4d22h
> kube-system              snapshot-controller-546868dfb4-kvn5p          1/1     Running     0               4d22h
> ix-ad-guard-home         ad-guard-home-adguard-home-5d95f68cb4-4bdj8   1/1     Running     0               4d22h
> ix-nginx-proxy-manager   nginx-proxy-manager-7bd798df4-g4mn6           1/1     Running     0               4d22h
> ix-qbittorrent           qbittorrent-5b6567d696-l5tjc                  1/1     Running     0               4d12h
> ix-file-browser          file-browser-filebrowser-66c64d5bd8-97mb7     1/1     Running     0               3d20h
> ix-prowlarr              prowlarr-67cb488c64-j58cr                     1/1     Running     0               2d22h
> ix-flare-solverr         flare-solverr-ix-chart-749bccbdcd-p2s6m       1/1     Running     0               2d21h
> ix-sabnzbd               sabnzbd-6fd667cdf4-5lpjj                      1/1     Running     1 (44h ago)     44h
> ix-radarr                radarr-56c9d6fd7c-7cwmc                       1/1     Running     0               28h
> ix-sonarr                sonarr-6bf4c7b9cf-6rllg                       1/1     Running     0               28h
> ix-plex                  plex-59d9fbdd64-cmj75                         1/1     Running     0               24h
> ```

Did you had home-assistant started/deploying, when you got this output?
Considering its a fresh install, can you try deleting the app. and install with a different name?

**Comment by stavros-k** [comment]
> Considering its a fresh install, can you try deleting the app. and install with a different name?

Can you also try this and let me know if it works?

**Comment by Divaaaaaan** [comment]
Let me try that quickly.

**Comment by Divaaaaaan** [comment]
@stavros-k Same issue. Renamed it to `ha`

```
2024-08-20 15:36:33
Back-off restarting failed container ha-home-assistant in pod ha-home-assistant-postgres-7888d659cb-445kt_ix-ha(8ab7b343-b1c5-495d-a4eb-8da836cb6cdd)
2024-08-20 15:36:28
Container image "postgres:13.1" already present on machine
2024-08-20 15:36:23
Created container ha-home-assistant
2024-08-20 15:36:23
Started container ha-home-assistant
2024-08-20 15:36:22
Successfully pulled image "postgres:13.1" in 1m15.758784085s (1m15.758967971s including waiting)
2024-08-20 15:35:12
Container image "postgres:15.2" already present on machine
2024-08-20 15:35:12
Created container ha-home-assistant-init-postgres-wait
2024-08-20 15:35:12
Started container ha-home-assistant-init-postgres-wait
2024-08-20 15:35:07
Pulling image "postgres:13.1"
2024-08-20 15:35:06
Started container ha-home-assistant-init-01-init-config
2024-08-20 15:35:05
Created container ha-home-assistant-install-permissions
2024-08-20 15:35:05
Started container ha-home-assistant-install-permissions
2024-08-20 15:35:05
Created container ha-home-assistant-init-01-init-config
2024-08-20 15:35:04
Scaled up replica set ha-home-assistant-postgres-7888d659cb to 1
2024-08-20 15:35:04
Scaled up replica set ha-home-assistant-7486fddcbd to 1
2024-08-20 15:35:04
Created pod: ha-home-assistant-postgres-7888d659cb-445kt
2024-08-20 15:35:04
Created pod: ha-home-assistant-7486fddcbd-shtjt
2024-08-20 15:35:04
Successfully assigned ix-ha/ha-home-assistant-postgres-7888d659cb-445kt to ix-truenas
2024-08-20 15:35:04
Successfully assigned ix-ha/ha-home-assistant-7486fddcbd-shtjt to ix-truenas
2024-08-20 15:35:04
Add eth0 [172.16.0.119/16] from ix-net
2024-08-20 15:35:04
Add eth0 [172.16.0.118/16] from ix-net
2024-08-20 15:35:04
Container image "mikefarah/yq:4.40.5" already present on machine
2024-08-20 15:35:04
Container image "bash:4.4.23" already present on machine
```

```
2024-08-20 06:42:06.116399-07:00The files belonging to this database system will be owned by user "postgres".
2024-08-20 06:42:06.116457-07:00This user must also own the server process.
2024-08-20 06:42:06.116470-07:002024-08-20T06:42:06.116470571-07:00
2024-08-20 06:42:06.116522-07:00The database cluster will be initialized with locale "en_US.utf8".
2024-08-20 06:42:06.116566-07:00The default database encoding has accordingly been set to "UTF8".
2024-08-20 06:42:06.116589-07:00The default text search configuration will be set to "english".
2024-08-20 06:42:06.116631-07:002024-08-20T06:42:06.116631785-07:00
2024-08-20 06:42:06.116620-07:00initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
2024-08-20 06:42:06.116712-07:00If you want to create a new database system, either remove or empty
2024-08-20 06:42:06.116738-07:00the directory "/var/lib/postgresql/data" or run initdb
2024-08-20 06:42:06.116653-07:00Data page checksums are disabled.
2024-08-20 06:42:06.116827-07:002024-08-20T06:42:06.116827073-07:00
2024-08-20 06:42:06.116758-07:00with an argument other than "/var/lib/postgresql/data".
```

**Comment by stavros-k** [comment]
Do you use ix-volumes or host-paths?
If it is host-paths, please try on a new directory or try ix-volumes.

I've just tried a fresh install and works fine for me.

**Comment by Divaaaaaan** [comment]
@stavros-k I used host volumes that I created. I did create a new directory for `ha` but failed so I'll try use the `ix-volume` but I'd prefer to have each app separate from the ix-volume but I'll give it a shot

**Comment by Divaaaaaan** [comment]
@stavros-k Using the `ix-volume` seems to work. It's strange that it would work but not with the creation of a custom data set.

**Comment by stavros-k** [comment]
Okay, at least we have pinpointed that is isolated to the host paths used.

Can you share the config you use for the storage section please?

**Comment by Divaaaaaan** [comment]
@stavros-k Here you go.
![image](https://github.com/user-attachments/assets/97161760-7ff4-4091-a09a-dc0955e13e01)

**Comment by stavros-k** [comment]
You have to use different directories for each storage....
eg

**Comment by Divaaaaaan** [comment]
@stavros-k Ah okay I didn't know but I assume that's the standard. Let me give that a go and see if that works.

**Comment by Divaaaaaan** [comment]
Is it best practice to always have separate folders for each storage regardless of app because I've only been using one main dataset per app for storage and they seem to work fine. Only HA which has given issues with this approach but will confirm now if the separate folders work.

**Comment by stavros-k** [comment]
Its pretty much a requirement, for smooth operations
In most cases it might work, but long term might cause issues. 
if you use a single directory for all storages it can cause conflicts with files with same name, or conflicts on permissions.

**Comment by Divaaaaaan** [comment]
Ah okay cool thank you very much for the info, I think I'll redo my app configurations then to go with the best practice. Also I've always used the `Apps` data preset when creating the datasets, is this fine or is there a preferred dataset to use when creating it for chart apps?

**Comment by stavros-k** [comment]
Yes this preset should be good, at least for the majority of apps.

I'll close this now, let me know if you still have issues after you split the directories!

Thanks!
