### ISSUE TITLE
Nextcloud installation impossible to create admin user

### ISSUE THREAD

**Issue by twisterrm** [truenas/charts#2753]
After the deploy i got this error
![1](https://github.com/user-attachments/assets/fd4c7e4c-6c30-4290-b669-70426f68a9a6)
I have try every suggestion found online without luck, i also try to login inside the db with pgadmin, but even if I put the correct credential (reported in config.php and on the "Notes" of application i receive this error
![2](https://github.com/user-attachments/assets/6ee104b1-61cd-4d17-a4fe-ff8afc6bd1ad)
It seems that the database/user creation is broken, i didn't see (as per Notes suggested) the admin user in config.php
This is my config.php

```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'nextcloud-redis',
    'password' => '[redacted]',
    'port' => 6379,
   ),
  'upgrade.disable-web' => true,
  'passwordsalt' => '[redacted]',
  'secret' => '[redacted]',
  'trusted_domains' => 
  array (
    0 => '192.168.[redacted]:9001',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '29.0.4.1',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'nextcloud-postgres:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '[redacted]',
  'instanceid' => '[redacted]',
 );
```

**Comment by stavros-k** [comment]
Is this a fresh install or are you trying to restore with a previews config.php?

**Comment by twisterrm** [comment]
It's a fresh installation

**Comment by stavros-k** [comment]
That's weird, is the data hostpath/ix-volume  used empty?
If it contains a config file, it will try to use previously defined dbuser/dbpass.
Because nextcloud uses that config file to manage its configuration, we cannot dynamically update it.

If the hostpath/ix-volume is empty, can you also try to install it under a different name?

eg `nextcloud-1` or something else.

> I've also tried installing nextcloud couple of times, and didn't have any issues.

**Comment by twisterrm** [comment]
Hi, sorry for the delay, after another fresh install (changed the dataset, name etc...) the app works fine now
