### ISSUE TITLE
Transmission - Unable to move file: Read Only Filesystem

### ISSUE THREAD

**Issue by Pixie35** [truenas/charts#2771]
Configured the app with a host path to a downloads folder within a dataset, and can confirm the apps group has permissions for this folder, however on completing a download, Transmission (and qBittorrent) gives the following error:

`Error: Couldn't get '/mnt/media/Downloads/filenames': Read-only file system (30)`

I have tried fresh installs but no matter what, it ends up with this error. This seems to be similar to #1762.
I'm still 60% unsure if this is a permissions issue but no other app is having these issues access and moving files.

**Comment by stavros-k** [comment]
> Configured the app with a host path to a downloads folder within a dataset, and can confirm the apps group has permissions for this folder, however on completing a download, Transmission (and qBittorrent) gives the following error:
> 
> `Error: Couldn't get '/mnt/media/Downloads/filenames': Read-only file system (30)`
> 
> I have tried fresh installs but no matter what, it ends up with this error. This seems to be similar to #1762. I'm still 60% unsure if this is a permissions issue but no other app is having these issues access and moving files.

Can you try using an ixVolume to test?
If ixVolume works, then its permissions issue.

Thanks!

**Comment by Pixie35** [comment]
I would, however I woke up the following morning, it worked without issue. I've now been unable to recreate the fault!
I'll keep the above in mind, if it does reappear and I'll reopen an issue. 
Thanks though!
