### ISSUE TITLE
Immic password

### ISSUE THREAD

**Issue by sheiy** [truenas/charts#2778]
Hi @sonicaj I want to know the default postgres password of immich community version.  I have already upgraded my truenas to 24.10.beta1. When I install immich app through TrueNAS UI and it let me input the postgres password but  I do not fill it when I used the prev version

**Comment by stavros-k** [comment]
If you used Immich on 24.04 and upgraded/migrated to 24.10. The password should be visible on the edit screen.
Previously it was autogenerated.

**Comment by sheiy** [comment]
@stavros-k my apps  not auto install when I upgraded to 24.10 the apps page is empty.
where can I find my immich pg password?

**Comment by stavros-k** [comment]
Is the apps service running? Can you give more details please?
What is the current state of the system?

Password is in the backups directory in the ix-applications dataset, but its not in plain text, but in base64.

**Comment by sheiy** [comment]
@stavros-k  Thanks for your reply. I found my password from ix-applications dataset and install new app of immich with the password which I found from backups ix-applications dataset. It's works fine.
By the way is there a way to add a internal ip to docker container? I want run a nginx proxy manager and set a internal ip to it(192.168.100.11)

**Comment by stavros-k** [comment]
Happy to hear that is working!

Currently there is no way.
But networking options are planned after all migrations are done.
