### ISSUE TITLE
Can't add additional storage to Immich

### ISSUE THREAD

**Issue by KeeganCarter11** [truenas/charts#2788]
Request to set 'immutable: false' for Immich additional storage. Another option that I would need help know if it would be posible would be refactoring the questions hierarchy so that adding storage is permitted but editing existing is not. 

https://github.com/truenas/charts/blob/master/community/immich/4.0.12/questions.yaml#L693 

![image](https://github.com/user-attachments/assets/0725ee8d-009f-476b-8a02-5e053ccd7039)

![image](https://github.com/user-attachments/assets/62291fe0-7c7f-4575-bec0-c0a22f06bfe1)

**Comment by stavros-k** [comment]
Adding should be permitted at any time. What is your scale version?

**Comment by KeeganCarter11** [comment]
> Adding should be permitted at any time. What is your scale version?

I can click the add button but even the newly created input-container for adding storage can't be edited. I'm assuming the 'immutable' configuration at the top level is taking precedence but I'll be honestly I don't 100% know how this page gets generated.

TrueNAS-SCALE
24.04.2
Immich App Version:
1.112.1
Immich Chart Version:
4.0.12

example of the inspect element for my existing Immich install, you can see I get an 'input container disabled' for fresh input-containers when clicking the add button:
![image](https://github.com/user-attachments/assets/9de2279e-0598-4421-89b5-346bb3c095d8)

vs the inspect element for a fresh install:
![image](https://github.com/user-attachments/assets/b375f87e-3ba6-4751-b3f3-60658b9baa92)

**Comment by stavros-k** [comment]
Hmm I remember this being an issue on 23.xx, but it has been fixed since.
I just tried on a system that is on 24.04, and the newly added items are editable.
only existing remain disabled.

Can you try clearing your browser cache or try another browser please?

**Comment by KeeganCarter11** [comment]
Cleared cache and bingo! PEBKAC error solved!

Thanks!
