### ISSUE TITLE
Immich doesn't show used storage capacity correctly

### ISSUE THREAD

**Issue by saukkico** [truenas/charts#2799]
I have about 160 GB of photos in Immich, but it shows I've used only 128 KiB of storage. 

![image](https://github.com/user-attachments/assets/1e85887f-b62a-4534-a189-5c9326aed37d)

Truenas version: Dragonfish-24.04.2

**Comment by stavros-k** [comment]
This depends on how Immich checks for used storage.
And the type of storage you used on for your photos.

Given that containers can have multiple different storage devices and types mounted, I'm not sure how someone could reliable provide a single "status" of used storage for all of those.

I'm closing this as there is nothing we can do here.

Thanks

**Comment by itsPenzi** [comment]
Immich checks the usage of the library folder. Afaik it's supposed to move the contents of the upload folder to library.
I found a band-aid fix by enabling storage templates and running the respective job for it.
