### ISSUE TITLE
Plex Configuration Storage directory misleading for migration

### ISSUE THREAD

**Issue by lambada** [truenas/charts#2800]
I was following [Plex's instructions](https://support.plex.tv/articles/201370363-move-an-install-to-another-system/) for migrating a Plex server to a new host to migrate from an old self-managed Jail install to the Truenes SCALE App.

I created on my server a pre-existing directory `/mnt/OnePower/saidar/plex-config/Plex Media Server` which I selected as the `Plex Configuration Storage` host path location. i.e. `/config` in the container was pointed to `/mnt/OnePower/saidar/plex-config/Plex Media Server`

I copied my existing `Plex Media Server` folder to that location meaning that I had for example the following paths
`/mnt/OnePower/saidar/plex-config/Plex Media Server/Preferences.xml`
`/mnt/OnePower/saidar/plex-config/Plex Media Server/Metadata`
`/mnt/OnePower/saidar/plex-config/Plex Media Server/Plug-ins`
etc. All the files and folders that compose the Plex Server Data Directory.

Upon starting the container plexpass version of the app it was obvious that it hadn't used the existing data and it was considered a blank server. Upon looking in /config it became clear that it had created its own data structure underneath to make a _new_ Plex data directory in the app at `/config/Library/Application\ Support/Plex\ Media\ Server` in the container or `/mnt/OnePower/saidar/plex-config/Plex Media Server/Library/Application\ Support/Plex\ Media\ Server` on the host.

I stopped the container, reset the `/mnt/OnePower/saidar/plex-config` folder and this time moved my Plex Server Data Directory to `mnt/OnePower/saidar/plex-config/Plex Media Server/Library/Application\ Support/Plex\ Media\ Server`
meaning that I now had
`/mnt/OnePower/saidar/plex-config/Plex Media Server/Library/Application\ Support/Plex\ Media\ Server/Preferences.xml` etc

Upon restarting the app it then detected and used my existing Server configuration without issue, once I'd added the new Plex Data Storage path to the existing libraries as expected.

This long path feels unintentional and under documented in the UI for migrating existing Plex Servers.

Here's a screenshot of the relevant configuration and also the full Pod YAML that's running
<img width="367" alt="Screenshot 2024-09-08 at 11 48 31" src="https://github.com/user-attachments/assets/88a92651-63d4-421b-bb3d-d562216d2e2c">

```yaml
# k3s kubectl get pods -n ix-plex -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      rollme: gZfPD
    creationTimestamp: "2024-09-07T22:20:36Z"
    generateName: plex-fbb7d58fb-
    labels:
      app: plex-2.0.12
      app.kubernetes.io/instance: plex
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: plex
      app.kubernetes.io/version: 1.40.5.8921
      helm-revision: "20"
      helm.sh/chart: plex-2.0.12
      pod-template-hash: fbb7d58fb
      pod.name: plex
      release: plex
    name: plex-fbb7d58fb-4v9k6
    namespace: ix-plex
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: plex-fbb7d58fb
      uid: b39fb35e-c753-4002-81de-b9bac1bb53f8
    resourceVersion: "9853"
    uid: f484bf43-3a17-4c3a-921d-67418bbf5ac3
  spec:
    automountServiceAccountToken: false
    containers:
    - env:
      - name: TZ
        value: Europe/London
      - name: UMASK
        value: "002"
      - name: UMASK_SET
        value: "002"
      - name: NVIDIA_DRIVER_CAPABILITIES
        value: all
      - name: PUID
        value: "568"
      - name: USER_ID
        value: "568"
      - name: UID
        value: "568"
      - name: PGID
        value: "568"
      - name: GROUP_ID
        value: "568"
      - name: GID
        value: "568"
      - name: PLEX_CLAIM
      - name: PLEX_GID
        value: "568"
      - name: PLEX_UID
        value: "568"
      image: plexinc/pms-docker:plexpass
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 32400
        timeoutSeconds: 5
      name: plex
      ports:
      - containerPort: 32469
        hostPort: 32469
        name: dlna-tcp
        protocol: TCP
      - containerPort: 1900
        hostPort: 1900
        name: dlna-udp
        protocol: UDP
      - containerPort: 32410
        hostPort: 32410
        name: gdm1
        protocol: UDP
      - containerPort: 32412
        hostPort: 32412
        name: gdm2
        protocol: UDP
      - containerPort: 32413
        hostPort: 32413
        name: gdm3
        protocol: UDP
      - containerPort: 32414
        hostPort: 32414
        name: gdm4
        protocol: UDP
      - containerPort: 32400
        hostPort: 32400
        name: webui
        protocol: TCP
      readinessProbe:
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 2
        tcpSocket:
          port: 32400
        timeoutSeconds: 5
      resources:
        limits:
          cpu: "4"
          memory: 8Gi
        requests:
          cpu: 10m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
          - KILL
          drop:
          - ALL
        privileged: false
        readOnlyRootFilesystem: false
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      startupProbe:
        failureThreshold: 180
        initialDelaySeconds: 30
        periodSeconds: 5
        successThreshold: 1
        tcpSocket:
          port: 32400
        timeoutSeconds: 2
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /config
        name: config
      - mountPath: /data
        name: data
      - mountPath: /config/Library/Application Support/Plex Media Server/Logs
        name: logs
      - mountPath: /shared
        name: shared
      - mountPath: /tmp
        name: tmp
      - mountPath: /transcode
        name: transcode
    dnsPolicy: ClusterFirstWithHostNet
    enableServiceLinks: false
    hostNetwork: true
    nodeName: ix-truenas
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups:
      - 44
      - 107
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - hostPath:
        path: /mnt/OnePower/saidar/plex-config/Plex Media Server
        type: ""
      name: config
    - hostPath:
        path: /mnt/OnePower/saidar
        type: ""
      name: data
    - emptyDir:
        sizeLimit: 2Gi
      name: logs
    - emptyDir: {}
      name: shared
    - emptyDir: {}
      name: tmp
    - hostPath:
        path: /mnt/OnePower/ix-applications/releases/plex/volumes/ix_volumes/transcode
        type: ""
      name: transcode
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2024-09-07T22:20:36Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2024-09-07T22:21:17Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2024-09-07T22:21:17Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2024-09-07T22:20:36Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://047246af9c578b8c46728462bdd989c0fc6ef0a43af74e3b7d7300f4c25b6888
      image: docker.io/plexinc/pms-docker:plexpass
      imageID: docker.io/plexinc/pms-docker@sha256:8aeb4a982ea564ad309861dd251cd9e218aac3f4e4d3da21375568341be1b16f
      lastState: {}
      name: plex
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2024-09-07T22:20:38Z"
    hostIP: 10.188.1.201
    phase: Running
    podIP: 10.188.1.201
    podIPs:
    - ip: 10.188.1.201
    qosClass: Burstable
    startTime: "2024-09-07T22:20:36Z"
kind: List
metadata:
  resourceVersion: ""
```

**Comment by stavros-k** [comment]
The `/config` is what upstream container has as a mount point to use.
The structure underneath is also created from the upstream container.
This is not something we can change. 

While we could mount your host path into `/config/Library/Application\ Support/Plex\ Media\ Server`, this breaks the assumption the container has for how data is structured. And can lead to unknown issues.

Maybe the Plex's instruction should include specific steps when it comes to containers.

> Personal opinion, avoid using spaces in your paths when possible :D
> eg Update your data structure to something like this `/mnt/OnePower/saidar/plex-config/<contents of the /config from the container>`
> ie, mount `/mnt/OnePower/saidar/plex-config` instead of `/mnt/OnePower/saidar/plex-config/Plex Media Server`

**Comment by lambada** [comment]
I'm not really suggesting or asking for a change in container behaviour, which isn't this repositories job; nor am I suggesting a change in behaviour, which would be a painful migration for users....

But I think a minor update to some of the embedded tooltips, for example the one in the screenshot below would go miles in usefulness for helping folks diagnose why their migration hasn't worked. The wording could be something like
> If you are importing an existing Plex library, the Preferences.xml and related folders need to be placed in a subfolder of this mount point at ./Library/Application Support/Plex Media Server`

Or some words like that. That's all I'm really suggesting :)
![image](https://github.com/user-attachments/assets/e98e0ee0-0985-4420-80be-d1a2e036ec51)

**Comment by stavros-k** [comment]
While I'm always up to making things more clear in the UI, I don't think adding migration tips there is a good idea.
I don't think it belongs there. This would be useful for a lot more people if it was added on Plex's docs.

What about the other X number of containers that work the same way?
