### ISSUE TITLE
Frigate Configuration Authenticated Port Not Used

### ISSUE THREAD

**Issue by derp90** [truenas/charts#2803]
By default this app is using the internal port 5000, which is the unauthenticated port.

Please add another option port to use the authenticated port (internal 8971)
Reference documentation: https://docs.frigate.video/frigate/installation/#ports

**Comment by adyanth** [comment]
This was not really solved

https://github.com/truenas/charts/blob/master/library/ix-dev/community/frigate/templates/_service.tpl#L14
