### ISSUE TITLE
Error upgrading nextcloud

### ISSUE THREAD

**Issue by strich3** [truenas/charts#2805]
2024-09-11 19:45:04
Error: ImagePullBackOff
2024-09-11 19:45:04
Back-off pulling image "nextcloud:29.0.6"
2024-09-11 19:45:03
Failed to pull image "nextcloud:29.0.6": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/nextcloud:29.0.6": failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/nextcloud/manifests/sha256:c437d628c117e0508e45c6d1d89f5fba236c092ade7d0cc28d629d581bea161c: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
2024-09-11 19:45:03
Error: ErrImagePull

I don't really know how to fix this, or increase the ratelimit

**Comment by stavros-k** [comment]
This is a rate limit from dockerhub. You'll have to wait for it to reset.
If I remember correclty it resets every 6hours or so

**Comment by strich3** [comment]
Alright, trying again now then
