### ISSUE TITLE
Cannot set INTERFACE on PiHole 2.0.14

### ISSUE THREAD

**Issue by AlexWhitehouse** [truenas/charts#2815]
When trying to upgrade to the latest version of this chart (PiHole 2.0.14) I get the following error:
[EFAULT] Failed to upgrade App: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml Error: UPGRADE FAILED: execution error at (pihole/templates/common.yaml:13:4): Container - Environment Variable [INTERFACE] in [envList] tried to override the Environment Variable that is already defined in [env]

I cannot set my INTERFACE variable in the chart options to enp3s0 which is the adapter I use as eth0 does not exist.
When removing this environment variable from the setup I am able to upgrade and launch PiHole 2.0.14 - if I try and set this variable after updating I get the same error.

Currently on TrueNas Scale: Dragonfish-24.04.2.2
<img width="696" alt="image" src="https://github.com/user-attachments/assets/599ea339-2594-4333-8bc2-5a1ef0953b24">

<img width="443" alt="image" src="https://github.com/user-attachments/assets/45f178ac-7965-4e63-aa8b-ec71129972f4">

**Comment by stavros-k** [comment]
Hello, remove the INTERFACE variable you have manually added, update and then use the ui field to set the desired value.

**Comment by AlexWhitehouse** [comment]
Sorry, UI where? On PiHole itself or the TrueNas UI for setting up the pihole config?

**Comment by stavros-k** [comment]
> Sorry, UI where? In the PiHole app itself or the TrueNas UI for setting up the pihole config?

In the pihole app!

<img width="1136" alt="image" src="https://github.com/user-attachments/assets/e6a40d1c-d5c8-44ee-9723-ac7b7f28e9e6">

**Comment by AlexWhitehouse** [comment]
Great, thanks!
