### ISSUE TITLE
Jellyfin - Making system panic

### ISSUE THREAD

**Issue by santicleon1** [truenas/charts#2817]
I installed jellyfin yesterday and it made my system reboot every 10 minutes.
First i thought that my disks were bad because of what i saw in shell but they arent, I stopped all apps before system rebooted and that stopped it from rebooting.

So I started apps one by one and waited around 10-20 minutes between starting each one. System rebooted after jellyfin.
I did the thing with rest of them and I couldnt get it to reboot.

Reinstallation of jellyfin didnt work.

System behaves normally as it did without jellyfin installed.

Im making issue because i saw that jellyfin was updated 16. 09. so maybe it was the update.

Picture of shell before reboot
![20240917_113318](https://github.com/user-attachments/assets/026a0526-9008-417b-bcfb-af330f662dce)

**Comment by stavros-k** [comment]
Hey, can you please open a Jira ticket (https://ixsystems.atlassian.net/)
And attach a debug there privately so someone can take a look?

Thanks
