### ISSUE TITLE
Nginx-proxy-manager template not working

### ISSUE THREAD

**Issue by Lavamancer** [truenas/charts#2820]
This issue occurs in TrueNAS SCALE 24.x:

When installing nginx-proxy-server from the Discover section, the default settings assign user ID 568 and group ID 568. However, this app requires user/group ID 0 (root) for installation. I recommend setting these values to 0 by default.

Additionally, the app exposes ports 30020, 30021, and 30022, which require specific port forwarding from the router to map them to ports 80, 81, and 443 in order to use this reverse proxy as the main entry point. A better solution would be to allow assigning a separate IP address, making the default ports available for use.

![image](https://github.com/user-attachments/assets/0d58d227-b6b6-4c04-9876-f04295071257)
![image](https://github.com/user-attachments/assets/0e39a203-ef4e-41ff-a500-0e0279293693)

**Comment by stavros-k** [comment]
The template works as designed.
But besides that, ports below 9000 are now available on TrueNAS Electric Eel (24.10) which users docker instead of kubernetes.
And such big changes are not going to happen on kubernetes considering it is going away.

Thanks
