### ISSUE TITLE
DDNS-Updater wrong Config.json entries.

### ISSUE THREAD

**Issue by RebelliousX** [truenas/charts#2827]
Please see this issue here for more details https://github.com/qdm12/ddns-updater/issues/818

It seems with v2.8.0 - 1.0.30, TrueNAS adds other keys to the Config.json file

![368977077-5dbb3438-e397-44f6-adff-f097fcebbe42](https://github.com/user-attachments/assets/76be3556-ced7-4ea7-8992-b0d9f4b743cb)

`Results` and `Warnings` keys should not and are not part of the real configurations that DDNS-Updater expects, per the author of DDNS-Updater himself.

DDNS-Updater expects the `settings` key to be at the top entry.

Now since I updated to latest version provided by TrueNAS, this broke the functionality of DDNS-Updater
and the log shows that the app can't find the `settings` to parse its values. Again, please look at the original issue at the top.

The author of DDNS-Updater says he doesn't know where the `results` and `warnings` keys are coming from and politely pointed me to create an issue here, since he believes TrueNAS is creating erroneous configuration file, not DDNS updater app itself.

**Comment by stavros-k** [comment]
I think you mean v1.0.16 version? You are on Electric Eel right?
(Fix is here https://github.com/truenas/apps/pull/469)

**Comment by RebelliousX** [comment]
@stavros-k correct, it is v1.0.16, I just got confused about the version here. And yes, I am using 24.10 Electric Eel.

**Comment by stavros-k** [comment]
Awesome thanks for confirming!

**Comment by RebelliousX** [comment]
When do we expect for it to show up in TrueNAS?

**Comment by stavros-k** [comment]
Few minutes after the linked PR is merged and you manually sync catalog after that!

**Comment by RebelliousX** [comment]
Great, thanks again for the fast response and fix 👍🏻
