### ISSUE TITLE
TrueNAS Immich used other port than in documentation

### ISSUE THREAD

**Issue by Yemtex** [truenas/charts#2842]
The TrueNAS Immich container uses the port 30041. The documentation and the other installation guides use port 2283, so that is very misleading. See https://immich.app/docs/install/post-install/

**Comment by stavros-k** [comment]
The port selection is on the form you submit. You can choose ports > 9000 on TrueNAS 24.04.x and any port not used on TrueNAS 24.10.x. 

Here is docs for SCALE specifically on Immich website https://immich.app/docs/install/truenas#networking-settings
