### ISSUE TITLE
[EFAULT] Failed to install App: WARNING: Kubernetes configuration file is group-readable. This is insecure.

### ISSUE THREAD

**Issue by kabatp** [truenas/charts#2845]
The following error is thrown when installing pgAdmin in TrueNAS Scale with default (or any other) values.

[pgAdmin_install_log.log](https://github.com/user-attachments/files/17231823/pgAdmin_install_log.log)

**Comment by stavros-k** [comment]
Please share the values you have entered in the UI for that app.

**Comment by kabatp** [comment]
I tried several setups:

These 2 cofiged as below all the time

![app](https://github.com/user-attachments/assets/834db4c9-f3a7-4b11-8189-a4ff4c7c52ba)
![config](https://github.com/user-attachments/assets/9d7f23ab-df0a-4037-b4de-0eb01b6f29cc)


The network part tried both the None certificate and default:
![network](https://github.com/user-attachments/assets/ee2a1084-58a4-421c-83d3-22cf9b5e3bda)


Regarding storage, I tried several:
I tried the host path without ACL to the dataset created for pgAdmin:
I tried to change permissions on the dataset so only the pgAdmin user has access to it without success.

![storage](https://github.com/user-attachments/assets/f3f473ff-a5ed-4436-b844-2be0389e9fd4)

I tried the same with ACL to 5050 user and force flag (This one I tried also with a new user 30XX created just for pgAdmin)
![storage](https://github.com/user-attachments/assets/1a014757-5939-480a-b0c1-c183189e3618)


And I also tried the default config with iX app storage
![storage](https://github.com/user-attachments/assets/f66d7af8-d1b6-4db8-a83c-1c38dead7af5)

**Comment by stavros-k** [comment]
It's not really a "permissions" or hostpath vs ixvolume issue here.
Something causing the rendering to go off.

Can you try something really simple for email/pass?

eg

`test@example.com`
`testpass`

thanks

**Comment by kabatp** [comment]
With the credentials you suggested it worked. So I did a little bit of testing
the email was not the issue

The password contained several symbols and the one causing the issue was [ at the start. While having [ in the middle was not causing any issues. At the beginning, it threw the same error as at the start.

**Comment by kabatp** [comment]
The following symbols at the start are causing the issue
[ ! @ % & * ] { } | ' " , `
