### ISSUE TITLE
NextCloud failing migration on App Upgrade

### ISSUE THREAD

**Issue by RBalcazar** [truenas/charts#2851]
I've been experiencing the issue described here: https://github.com/nextcloud/server/issues/48372

Nextcloud Developers on that issue state that the issue has been fixed in 30.0.1 3 days ago (10/3/24), which was recent. Charts reports that the app is on 30.0.0, so it appears that it doesnt have this fix yet.

**Comment by stavros-k** [comment]
As of this message upstream have not released an image for that version
You can check here https://hub.docker.com/_/nextcloud/tags?name=30.0.1

Once that is released the version will be updated on our catalog as well.
