### ISSUE TITLE
Unifi docker image is deprecated

### ISSUE THREAD

**Issue by csutcliff** [truenas/charts#2864]
Hi,

The unifi image https://hub.docker.com/r/linuxserver/unifi-controller is currently deprecated and unmaintained, last update was 9 months ago.

It has been replaced by https://hub.docker.com/r/linuxserver/unifi-network-application

Could the chart be updated to reflect the upstream change?

**Comment by stavros-k** [comment]
We do not use that container at all. 
And there is also an update coming in here https://github.com/truenas/charts/pull/2867
