### ISSUE TITLE
[SCALE] Official Nextcloud 23 won't update

### ISSUE THREAD

**Issue by peterge1998** [truenas/charts#287]
![image](https://user-images.githubusercontent.com/47355238/148218173-80009000-e838-4306-8384-ef28c7cfc85d.png)

![image](https://user-images.githubusercontent.com/47355238/148218189-9093f34d-9e3b-41e5-b0fc-8fd0ffbcc931.png)

Hey, I have Nextcloud V23_1.3.11 installed. It shows Update available under Applications > Installed Applications. When I try to update the app, it is showing the upgrading... until 50% is reached. Then the windows closes and disappears, without showing any warning. What am I doing wrong? How can I fix that? Is there maybe any option to do this via CLI? It's the official Nextcloud App...

Don't know if this is the right place/ if my Jira issue is correct,
but here are Jira and my forum post:
https://jira.ixsystems.com/browse/NAS-114148
https://www.truenas.com/community/threads/scale-official-nextcloud-23-wont-update.97952/

**Comment by sonicaj** [comment]
@peterge1998 this has been resolved in latest nightlies https://jira.ixsystems.com/browse/NAS-114031.

**Comment by sonicaj** [comment]
If you would like to manually resolve this, you can do so by stopping nextcloud app and deleting the nextcloud:23 docker image and then starting the app again :)
