### ISSUE TITLE
Stuck on "Update needed" screen after the update on TrueNAS

### ISSUE THREAD

**Issue by ByteBolt556** [truenas/charts#2875]
![{B468A15E-743B-4220-A13C-C95B9E46DDA0}](https://github.com/user-attachments/assets/df44afdc-25f6-4dc1-b9be-c0b340050601)

In the beginning I had the same issue as **[here](https://github.com/truenas/charts/issues/2690)** when I downloaded the update. I performed the steps to get rid of Maintenance Mode Screen but later on I got the error that you see on the screenshot. I have no idea how to navigate to that file and apply updates or how to fix it. On truenas I have applied the newest update and it's still saying the same thing. I have ran out of ideas. Can you help out? Thanks! 

PS. I do have to mention that this happens **very often on _every other_ update on TrueNAS**. I'd recommend looking into it unless this is something on my end that I don't know that could be causing issues

**Comment by ByteBolt556** [comment]
Solution from https://github.com/nextcloud/all-in-one/discussions/2726 did not help

**Comment by stavros-k** [comment]
You should be able to use `occ` commands again to manually run the update.

You can see subcommands of occ with:

```sh
su -p "www-data" -s /bin/bash -c 'php /var/www/html/occ'
```

Do not try to use web updater ever even if you enable it in the config file

**Comment by ByteBolt556** [comment]
![{F4E0FAD9-9459-4B6A-BDDB-78C8D3F98EB7}](https://github.com/user-attachments/assets/66207e97-9538-48d8-aafa-80d4a12c4839)

It's stuck

**Comment by ByteBolt556** [comment]
I'm definitely doing something wrong. This is very complicated. Can you help out? It's stuck on maintenance mode again

**Comment by stavros-k** [comment]
> ![{F4E0FAD9-9459-4B6A-BDDB-78C8D3F98EB7}](https://private-user-images.githubusercontent.com/56353909/378464954-66207e97-9538-48d8-aafa-80d4a12c4839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjE5NTUsIm5iZiI6MTcyOTUyMTY1NSwicGF0aCI6Ii81NjM1MzkwOS8zNzg0NjQ5NTQtNjYyMDdlOTctOTUzOC00OGQ4LWFhZmEtODBkNGExMmM0ODM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE0NDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MGU4NDg0OWZkY2RjMTBkMmEwZWUxNTRlNzcyNjM5OTlkOGU2OWYxYjFjNmUxN2ZiZGVkOTliM2ZlZWUzNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Qd-j7TOzDltCGmkFa_5af2tE3EhmJSf1Frh2-c5I0Sk)
> 
> It's stuck

Did it finish? Any errors?



> I'm definitely doing something wrong. This is very complicated. Can you help out? It's stuck on maintenance mode again

Not really. I can only offer suggestions based on logs. But we dont build nextcloud, we only package it, so I can't really tell you exactly whats wrong, unless its something obvious from the logs

**Comment by ByteBolt556** [comment]
> Did it finish? Any errors?

Nope it's been sitting there for about 15 minutes with no progress. I could try to give you log files but I'm not sure how or where to access them. Documentation from nextcloud has commands that I can't even use like "sudo" so it's making this situation even harder

![image](https://github.com/user-attachments/assets/b0989e4b-f280-4781-b126-0d0b82b1dca1)

**Comment by ByteBolt556** [comment]
![{D5FB73E9-BEB3-49B0-B1ED-27085C50D174}](https://github.com/user-attachments/assets/1377c9eb-4f35-413b-b2f9-b100053879d7)

**Comment by stavros-k** [comment]
You can't just execute nextcloud specific commands in truenas shell.
You have to shell into the nextcloud container.

Any OCC command you see on the nextcloud docs, can be executed with this format
https://github.com/truenas/charts/issues/2875#issuecomment-2426419847

**Comment by stavros-k** [comment]
> ![{D5FB73E9-BEB3-49B0-B1ED-27085C50D174}](https://private-user-images.githubusercontent.com/56353909/378490065-1377c9eb-4f35-413b-b2f9-b100053879d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjQzODAsIm5iZiI6MTcyOTUyNDA4MCwicGF0aCI6Ii81NjM1MzkwOS8zNzg0OTAwNjUtMTM3N2M5ZWItNGYzNS00MTNiLWIyZjktYjEwMDA1Mzg3OWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE1MjEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3OTI3OTNlODcwNGI2Nzg5MWQ2NGJhODVlY2QxNzQ3YzU1MzdkYzg0NTEzNjVkZjhkM2I2NDgwMDY0ZWJhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.d_3oNdCqqcUZ87yEddzWwokCf3OE9XZg8LthmcJ0ebs)

https://github.com/nextcloud/server/issues/48372

**Comment by ByteBolt556** [comment]
> > ![image](https://private-user-images.githubusercontent.com/56353909/378476833-b0989e4b-f280-4781-b126-0d0b82b1dca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MjQzNTIsIm5iZiI6MTcyOTUyNDA1MiwicGF0aCI6Ii81NjM1MzkwOS8zNzg0NzY4MzMtYjA5ODllNGItZjI4MC00NzgxLWIxMjYtMGQwYjgyYjFkY2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE1MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNGZjMzU4Y2Y5YmNkM2YwYjUzNTA2MTM5YjlmYTE1NDkyMjBmZDczZjdkZWNlY2I4MWY2YmMwYTA4NTMxMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xipGOj-nklg1Calal46M2tbmVpOD_u-IZ-npiGc3R40)
> 
> You can't just execute nextcloud specific commands in truenas shell. You have to shell into the nextcloud container.
> 
> Any OCC command you see on the nextcloud docs, can be executed with this format [#2875 (comment)](https://github.com/truenas/charts/issues/2875#issuecomment-2426419847)

So I'm guessing it would look like this?

`su -p "www-data" -s /bin/bash -c 'php /var/www/html/occ upgrade'`

**Comment by stavros-k** [comment]
Yes

**Comment by stavros-k** [comment]
> Ok I managed to make it work somehow. Alright I want to make one thing clear. You told me to not a web updater. Do you mean the one built-in Nextcloud or the one in TrueNAS?
> 
> ![{018171EA-C8FE-44D3-9366-758860C79492}](https://private-user-images.githubusercontent.com/56353909/378530987-a9e339e0-ad09-40d4-abc1-6012cf80d5af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzEwMDcsIm5iZiI6MTcyOTUzMDcwNywicGF0aCI6Ii81NjM1MzkwOS8zNzg1MzA5ODctYTllMzM5ZTAtYWQwOS00MGQ0LWFiYzEtNjAxMmNmODBkNWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE3MTE0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODA5ODY3OWI2YWZhMTc5ZWQ4OGQwOGZlZjIzMjI5MDU2ZjU1NmM4NzE3OTE3ZTMxZmI4ZDlhZDJjMmU5OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8u8cu4SqknGflyimucsam6KSZUz-It8Evz4xnGjKFyE)

You should avoid using nextcloud's built in updater. 
It can fail due to lot of reasons. 

Only update via truenas webui.

**Comment by ByteBolt556** [comment]
Okay. I'm asking because that's how I updated Nextcloud before and it broke each time I did it so I'm not sure whether something is wrong on my end.
