### ISSUE TITLE
Lidarr outdated

### ISSUE THREAD

**Issue by kabatp** [truenas/charts#2881]
Is there any technical/particular reason why TrueNas Scale Charts roll with Lidarr 2.5.2.4316 when Lidarr is already on 2.6.4.4402?

**Comment by ChaosBlades** [comment]
2.7.0.4413 actually. Was released 2 days ago.

**Comment by kabatp** [comment]
That is only a pre-release so it is understandable. But 2.5.2.4316 was released Aug 25 2024 - 2 months ago

**Comment by stavros-k** [comment]
We had to switch upstream source to keep updates coming. This is done already for 24.10 apps system.
There are no plans for charts at the moment.
