### ISSUE TITLE
Question: ML inactive for Immich Cuda machine learning image running on Truenas

### ISSUE THREAD

**Issue by Fireflaker** [truenas/charts#2891]
Hi!

I have upgraded to the latest truenas as well as immich as of today, and I wonder if anybody is having the same issues:

When searching using any keyword:

> No results
> Try a synonym or more general keyword
> 
> Error
> Failed to search smart
> (Immich Server Error)

When launching app with GPU enabled:

> 2024-10-25 01:14:08
> Container image "altran1502/immich-machine-learning:v1.118.2-cuda" already present on machine
> ......
> 2024-10-25 01:12:26
> 0/1 nodes are available: 1 Insufficient nvidia.com/gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..

When launching without GPU enabled:

> Same hebavior

In all cases,

> In the jobs section, files seems to be processed with 10k+ remaining and slowly decreasing
> In the people section, it always shows no people
> When searching, the error message Failed to search smart (Immich Server Error) always shows up

Hardware: intel gen 8 CPU, 16gb ram, nvidia k620 GPU(which is quite old, but shows up in truenas terminal fine)

Much thanks!

**Comment by stavros-k** [comment]
Considering apps system in 24.04 is replaced with docker in 24.10.
There won't be any bugtracing/bugfixing on that apps system.

Feel free to test once you upgrade on 24.10 rc2 or stable when it is available.
If you still having issues feel free to open a new issue at https://github.com/truenas/apps

Thanks

**Comment by Karmalakas** [comment]
I have same issue on ElectricEel-24.10.0.2
Reported [here](https://github.com/truenas/apps/issues/942)
