### ISSUE TITLE
Update postgres version for nextcloud

### ISSUE THREAD

**Issue by Renari** [truenas/charts#2895]
I've been working on migrating everything off of TrueCharts and when manually updating Nextcloud to version 30 so that I can dump the database and restore with the TrueNAS chart it seems my database was updated to Postgres 1.15, thus preventing me from restoring my database dump on the TrueNAS official chart.

I dug around a bit but I'm not entirely sure how the charts are laid out to figure out where I'd find this to make a PR, I'll continue digging and if I find it I'll make a PR.

**Comment by stavros-k** [comment]
https://github.com/truenas/charts/pull/2896#issuecomment-2444081121
