### ISSUE TITLE
Pi-Hole can no longer resolve DNS for other apps, after upgrading to Electric Eel.

### ISSUE THREAD

**Issue by TimvanDijkNL** [truenas/charts#2907]
As the title suggests, on "Dragonfish" 24.04, other apps & custom apps could use Pi-Hole as DNS server via the host IP. After upgrading to "Electric Eel" 24.10 this is no longer the case, most likely due to the switch to docker.

Is there any way to fix this ?

**Comment by stavros-k** [comment]
I'm not sure, did you try anything to troubleshoot this?
Did you check if other apps can reach pihole's dns port?

Any logs?

**Comment by TimvanDijkNL** [comment]
Attempting to resolve from the shell of a random container (jlesage/firefox in this case) works on cloudflare dns and my ISP's router.. but not on the PiHole via the TrueNAS ip. Pinging the IP however works fine.

```
/tmp # nslookup www.google.com 1.1.1.1
Server:         1.1.1.1
Address:        1.1.1.1:53

Non-authoritative answer:
Name:   www.google.com
Address: 142.251.36.4

Non-authoritative answer:
Name:   www.google.com
Address: 2a00:1450:400e:803::2004

/tmp # nslookup www.google.com 192.168.2.254
Server:         192.168.2.254
Address:        192.168.2.254:53

Non-authoritative answer:
Name:   www.google.com
Address: 142.251.36.36

Non-authoritative answer:
Name:   www.google.com
Address: 2a00:1450:400e:801::2004

/tmp # nslookup www.google.com 192.168.2.1
;; connection timed out; no servers could be reached

/tmp # ping 192.168.2.1
PING 192.168.2.1 (192.168.2.1): 56 data bytes
64 bytes from 192.168.2.1: seq=0 ttl=64 time=0.075 ms
64 bytes from 192.168.2.1: seq=1 ttl=64 time=0.107 ms
^C
--- 192.168.2.1 ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.091/0.107 ms
/tmp # 
```

Resolving the same domain on my windows laptop via the PiHole DNS works fine, however:

```
Microsoft Windows [Version 10.0.22631.4391]
(c) Microsoft Corporation. All rights reserved.

C:\Users\conta>nslookup
Default Server:  truenas.home
Address:  192.168.2.1

> www.google.com
Server:  truenas.home
Address:  192.168.2.1

Non-authoritative answer:
Name:    www.google.com
Addresses:  2a00:1450:400e:80f::2004
          216.58.214.4

>
```

I did find this: https://discourse.pi-hole.net/t/solve-dns-resolution-in-other-containers-when-using-docker-pihole/31413 where they suggest changing the listening address to the actual address of the host OS (TrueNAS) but i have not been able to experiment with that as my docker knowledge is too limited.

**Comment by stavros-k** [comment]
Do you have static ip on truenas? If not can you set one?

Seems weird that binding it to specific ip instead of all would fix it. Tho this will be possible probably in 25.04.

**Comment by TimvanDijkNL** [comment]
You mean give the PiHole a unique IP ? Or the TrueNAS server ? The TrueNAS server has a static IP. PiHole is using the default setting which is host network

**Comment by stavros-k** [comment]
I meant truenas yes.

But if you are using host network. You can't use the solution mentioned in the forum you shared. 
Maybe check that the interface selected in the pihole settings is the correct one

**Comment by TimvanDijkNL** [comment]
Sadly that's not it either. 

I think it's a Docker specific thing, because with 24.03 it worked like a charm, but it stopped working when migrating to 24.10

![Untitled](https://github.com/user-attachments/assets/41e3b588-6d5e-4ddf-a153-f9c347f89192)

**Comment by stavros-k** [comment]
I meant this
![Uploading image.png…]()

**Comment by TimvanDijkNL** [comment]
Ah. I was mistaken.. the default is not to use the host network it seems.

**Comment by TimvanDijkNL** [comment]
Unfortunately, no... enabling Host Network and setting the server's network card ( `eno1` in this case) seems to have no impact what so ever.

**Comment by NikoKS** [comment]
Is there no elegant fix for this? I'm facing the same problem but with adguard DNS

**Comment by krzysiek2788** [comment]
I have found solution to this issue (it is also present in AdGuard Home app) here is link with solution I have tested it in AdGuard custom app and it is working my other docker apps finally started using local DNS :D
https://discourse.pi-hole.net/t/solve-dns-resolution-in-other-containers-when-using-docker-pihole/31413

**Comment by TimvanDijkNL** [comment]
But how would you do this for the app from the iXsystems catalog ? Assume i have no knowledge of docker yaml stuff

**Comment by krzysiek2788** [comment]
I think now what you can do is only install pihole via Custom app with yaml code where you can put - ip:53:53/udp in port.

**Comment by stavros-k** [comment]
In this case it will be addressed here https://github.com/truenas/apps/issues/787
Closing this now, please subscribe to the linked issue.
Thanks
