### ISSUE TITLE
Unable to install Vaultwarden with custom dataset

### ISSUE THREAD

**Issue by alosarjos** [truenas/charts#2918]
Vaultwarden is unable to get installed if I decide to use a previously create dataset instead of letting truenas create automatically the ix dataset for apps

**Comment by patsytau** [comment]
Does the pre-existing dataset contain anything?

Note that you may need to set the postgresql dataset/folder's permissions to '999:999' if you use a host path.

**Comment by alosarjos** [comment]
I got it working setting the owner and group of the dataser dir to 999:999 (netdata:docker)

Is this the correct way to handle this?

**Comment by patsytau** [comment]
I think technically the correct way is to do it through the UI via an Access Control List, but I think the end result is the same.

**Comment by alosarjos** [comment]
I'm trying to to the ACL but I'm not capable

![imagen](https://github.com/user-attachments/assets/86099d81-1870-43de-8adc-93520bf69f8e)

**Comment by stavros-k** [comment]
Postgres does not like ACLs, as it has very strict checks that the owner is `999` even if it has read/write access.

**Comment by alosarjos** [comment]
So then the only way is to set 999 as owner of the dataset? Can that make any issue? From the UI I can set that owner because there is a user netdata and the docker group with id 999 but seems a bit like some workaround that can be done by pure coincidence

**Comment by stavros-k** [comment]
We don't always control the ids inside the containers. In this case postgres is 999.
Whether you set it via UI using matched names, or via terminal is the same.
As long as it results on a directory owned by 999:999, its fine.
