### ISSUE TITLE
Nextcloud - can't connect after changing host address

### ISSUE THREAD

**Issue by merito** [truenas/charts#2922]
Hi, I've changed my TrueNAS host address, then Host setting in Nextcloud configuration, but I can't access my Nextcloud instance. I've got "Access through untrusted domain" error, see https://docs.nextcloud.com/server/30/admin_manual/installation/installation_wizard.html#trusted-domains I've tried to set NEXTCLOUD_TRUSTED_DOMAINS env variable, but I get an error, because the variable is already set. It looks like this setting is taken into consideration only during the installation and then you can't change it.

┆Attachments: <a href="https://api.atlassian.com/ex/jira/94e022be-3595-4f54-979f-780bfeff904d/rest/api/2/attachment/content/73542">image-20241106-214243.png</a>

**Comment by merito** [comment]
Leaving Host empty does not help

**Comment by stavros-k** [comment]
I'll close this one, as there isnt something we can do on our side.
