### ISSUE TITLE
Homepage Not Updated / Immich Widget

### ISSUE THREAD

**Issue by jason-e-gross** [truenas/charts#2925]
The immich widget in the `homepage` underwent some [breaking changes](https://github.com/gethomepage/homepage/releases/tag/v0.9.11) and was updated three weeks ago.

Seems like the truenas charts for homepage hasn't been updated - because it's still showing errors.

![image](https://github.com/user-attachments/assets/00ec7f46-1258-4ead-aa28-fac55522d9fd)

I suspect the truenas chart for [homepage](https://github.com/gethomepage/homepage) just needs updating to point at the latest version of homepage, so it can use the new REST endpoints (the screenshot is showing its still using the old endpoint).

**Comment by stavros-k** [comment]
It looks like we are up to date.

Charts repo
https://github.com/truenas/charts/blob/c22054138a82c17706642681c5edcbc9ba9d9f2f/library/ix-dev/community/homepage/values.yaml#L4

Apps repo
https://github.com/truenas/apps/blob/78aaf89c9859a241ebf65be525d44d30f7a5a51f/ix-dev/community/homepage/ix_values.yaml#L4

**Comment by jason-e-gross** [comment]
Thanks folks.  Appreciate the check and response.

________________________________
