### ISSUE TITLE
pgBackup folder on Truenas SCALE (24.04)

### ISSUE THREAD

**Issue by the-real-naxgo** [truenas/charts#2929]
Hello,

During the app install I have set this folder, and now after some time there are 3 files with the .sql extension in it.
To me this means there is an automatic backup solution of the database.
How would one configure this? (mainly the frequency)
and most importantly, how would one restore the db using one of these files?

Thanks

**Comment by stavros-k** [comment]
Hello, this folder will not be used on 24.10 as there isn't an easy way in docker to do what we were doing in kubernetes.
An alternative solution would be to use snapshots on the dataset you have the database data.

And later on when docker networks are available, you could use something like pgAdmin to export/import backups.

**Comment by the-real-naxgo** [comment]
I am not going to update to 24.10 any time soon... Waiting for all the kinks to be sorted. How can I use these .sql files in 24.04?
Thanks

**Comment by stavros-k** [comment]
Either pgAdmin app or psql cli within each postgres container.
