### ISSUE TITLE
Unable to access nextcloud after enabling Certificate ID (Nginx)

### ISSUE THREAD

**Issue by immanuelsmith** [truenas/charts#2933]
After enabling "Certificate ID" (Nginx) in the settings for a Nextcloud App, it sets the container port for the app to the same as the host ID. The correct config should be <hostip>:30027 -> port 80, instead it shows <hostip>:30027 -> port 30027. Issue is reproducible on both old and fresh app instances

**Comment by stavros-k** [comment]
It works fine for me
<img width="1239" alt="image" src="https://github.com/user-attachments/assets/08e6006e-f33b-4822-b3b8-add7d289ae01">


Nginx does not listen to `80`, but on the configured port on the UI. So the port mapping is correcgt

**Comment by stavros-k** [comment]
The mapping is correct.
What URL are you trying to access?

**Comment by immanuelsmith** [comment]
Within the container, the web server listens on port 80. This is what it should look like. I was able to get it back to correct config by disabling certificate ID in the nextcloud app settings. 
![image](https://github.com/user-attachments/assets/e71a7258-38ab-4dd8-88ff-831876aabe1b)

**Comment by stavros-k** [comment]
> Within the container, the web server listens on port 80. This is what it should look like. I was able to get it back to correct config by disabling certificate ID in the nextcloud app settings. ![image](https://private-user-images.githubusercontent.com/25368201/384990524-e71a7258-38ab-4dd8-88ff-831876aabe1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDE5MTcsIm5iZiI6MTczMTM0MTYxNywicGF0aCI6Ii8yNTM2ODIwMS8zODQ5OTA1MjQtZTcxYTcyNTgtMzhhYi00ZGQ4LTg4ZmYtODMxODc2YWFiZTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE2MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MzI4ZjY1MDIzNzY3OTk5MzU2ZGY4ZDcwNDQzZDdiYWZlMDhkZTAzNmJmYzM2ODEyYjQxZjE4YmFiNTdmMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DjlPWv63-9pJZIf1meBfGP5VWy78X2C80L7I5kVr1kA)

You are mixing things.

Nextclouds does run as 80, yes.
But when certificate ID is enabled, the nginx container is running in front. 
Nginx runs on the configured port.
So Host (configured port) -> Nginx (configured port) -> nextcloud(80)
in this case, the nextcloud's 80 port is not exposed, so you wont see in the port listing there.

---

Can you please answer on what URL are you using? 
Maybe a video of what's happening?

**Comment by stavros-k** [comment]
You can try comparing the config.php files. Nextcloud is weird at times, in the sense that some settings are install time and some are on every start.
So there might be something out of sync. 
Not many things we can do on our side.

**Comment by immanuelsmith** [comment]
so I was able to recreate the issue today unfortunately. I decided to run with my second server to set it up, for the record I am trying to run nextcloud on the same IP as truenas, just on a different port. There is a bug in the install/config script for nextcloud where it doesn't automatically add that IP as a trusted domain in nextcloud, I am able to bypass this by manually adding that IP to nextcloud's config.php, but as soon as I do that combined with the certificate option in the nextcloud app settings, the bug happens again.

**Comment by stavros-k** [comment]
trusted domains are only updated on initial install, this is something that nextcloud it self handles.
But beyond that, given the information, I cannot reproduce it.
Nextcloud runs fine in the same IP as truenas on different port just fine for me.

**Comment by immanuelsmith** [comment]
It appears that this bug was fixed by something that was done in a Nextcloud app update.
