### ISSUE TITLE
Nextcloud stuck at login page due to issue with Redis password

### ISSUE THREAD

**Issue by rrd1** [truenas/charts#2937]
I did the following steps at TrueNAS 24.10 with various recent versions of the Nextcloud app:

1. No NC datasets available (deleted old ones, made sure nothing left over on CLI)
2. Created new datasets, set permission as per the new documentation at https://www.truenas.com/docs/truenasapps/stableapps/installnextcloudmedia/
3. Followed also the other installation steps from that manual
4. Set 'Admin Password', 'Redis Password' and 'Database Password' to custom values
5. deployed the app successfully
6. verified that config.php took over the correct Redis password, that is the case
7. browsed to the NC login page
8. entered credentials that were used during setup, login page appears again.
9. reloaded page, same result
10. cleared browser cache, tried again, same result
11. Set REDIS_HOST_PASSWORD in the APP wizard, same result
12. changed Redis password in App wizard to 'nextcloud' and manually took this over in config.php
13. login works fine
14. changed Redis password back to custom value -> broken again

I feel the Redis password from app wizard is considered properly by Nextcloud but another part of the app/container just uses a hardcoded default password.

Plesse let me know if any further details to be added.

**Comment by stavros-k** [comment]
Hello, reading this, made me realize that this part of the form was doing nothing.
ie no additional envs was being used at all. 

```
Set REDIS_HOST_PASSWORD in the APP wizard, same result
```

But the `REDIS_HOST_PASSWORD` is set correctly using the Redis Password field.
Is it possible to share the password you used and you had the issue?

If you try a fresh install with a password like `my-redis-pass123` it should work just fine.
I suspect some character is causing the problem.

**Comment by rrd1** [comment]
I just delete the instance multiple times, dropped the content of all related datasets manually and setup the app v1.4.9 again with below settings:

1.  Same password as before, 30 characters
     - stuck at login again
2. Used "my-redis-pass123" as password
     - works fine indeed
3. Another password with just 20 characters
     - works also fine

So my conclusion is that Redis does not support a password of 30 characters. Database and Nextcloud are fine with that.

Do you know what's the maximum length for Redis in this environment? In general Redis should support even longer passwords as far as I quickly investigated.

**Comment by stavros-k** [comment]
It seems that is nextctloud's issue, but not globally.
I get the same login issue with a 30char pass. But it seems that nextcloud have inserted some keys in the redis.

```sh
$ bash
I have no name!@c79f0ef62d41:/$ redis-cli
127.0.0.1:6379> AUTH 6tZY7as6oW5F8vkTw6wVJDwwSasJME
OK
127.0.0.1:6379> KEYS *
  1) "PHPREDIS_SESSION:9dacf4498be4b04a2b0e8edd488c0853"
  2) "PHPREDIS_SESSION:20b2b919e5a03d11af2fdf17e9d6d142"
  3) "PHPREDIS_SESSION:3cd004a19c7bf0429c7de5671f9b4bc1"
  4) "PHPREDIS_SESSION:d29679c0fe13efc11109b9e0ffb45dbc"
  5) "PHPREDIS_SESSION:fc57162b3e48dce2d7c6dff9f21a275f"
  ...
```

Interesting enough is that nextcloud genrates a 35MB log file right after install.
I cannot even try to do some advanced searching. But I can see it have logged some certificates (?!)
My best guess is that it somewhere overflows.

**Comment by stavros-k** [comment]
HUH. Okay. I've reinstalled using the same 30char password.
But now access via incognito.
First login: "Temporary error".
Second login -> Success

First time on the dashboard, "Problem occured"
Then every refresh worked.
Logout/Login works.

So I think it works, but nextcloud seems to cache something WAY too hard.

**Comment by sukarn-m** [comment]
Here's a redis password that was randomly generated, and has caused probably the same issue:
```
Y&FtYK25G%Bfr!UsX@5mu2Dnd5%#L5W@
```
This password was set through the app wizard at the time of the initial install.

the nextcloud.log file is filled with these messages:
```
{"reqId":"cyzwI6wVlWaRmXq9Nasf","level":3,"time":"2024-11-16T06:50:40+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"GET","url":"/status.php","message":"session_start(): Failed to read session data: redis (path: tcp://xxx:xxx@) at /var/www/html/lib/private/Session/Internal.php#198","userAgent":"curl/7.88.1","version":"30.0.2.2","data":{"app":"PHP"}
```

**Comment by stavros-k** [comment]
Yea, looks like the redis client library nextcloud uses, does not url encode the password.
I tried to do it on my side, but it is also used on another place which breaks when I encode it.
I suppose I'll have to disallow some special characters
