### ISSUE TITLE
Dashboard does not display saved automations, scripts, or scenes in Home Assistant

### ISSUE THREAD

**Issue by DenisTimofijuk** [truenas/charts#2939]
**Description**:
I'm experiencing an issue where automations, scripts, and scenes saved in Home Assistant are not appearing on their respective dashboards. After creating and saving these items, the dashboard resets to its initial "Start automating" view, as if nothing was saved. However, I can access each created item directly using URLs, confirming that the items are saved but not displayed in the dashboard.

**Steps to Reproduce**:
1. Open the Home Assistant dashboards for automation, script, or scene:
   - `/config/automation/dashboard`
   - `/config/scene/dashboard`
   - `/config/script/dashboard`
2. Create and save a new automation, script, or scene.
3. Return to the dashboard view for the created item.
4. Observe that the dashboard resets to the initial view, instead of displaying the saved items.

**Expected Behavior**:
Saved automations, scripts, and scenes should appear on their respective dashboards after saving, without the dashboard resetting to the initial view.

**Observed Behavior**:
After saving, the dashboard displays the following initial view text:
> "Start automating  
> Automations make Home Assistant automatically respond to things happening in and around your home.
> 
> Automations connect triggers to actions in a 'when trigger then action' fashion with optional conditions. For example: 'When the sun sets and if Denis is home, then turn on the lights'."

However, I can still access the saved items directly via URL, e.g., `/config/automation/edit/1731534753959`.

**System Information**:
- **Home Assistant Version**: 2024.11.1
- **Frontend Version**: 20241106.2
- **Chart Version**: 2.0.51
- **Installation Source**: TrueNAS Charts
- **Catalog**: TrueNAS
- **Train**: Charts

**Additional Notes**:
- Issue appears specific to dashboard display, as the items are saved and accessible via direct links.
- No error messages or logs appear related to this issue on the frontend.

Any insights or guidance would be appreciated, as the issue impacts the usability of automation and scene management.

**Comment by DenisTimofijuk** [comment]
I’m not sure I fully understand your suggested solutions. Let me clarify a few points:

I am already using the web UI to create automations, scripts, and scenes.
When you mention the 'expected path,' what exactly do you mean? From what I can observe, the automations.yaml file is being updated correctly with my new automation rules when I save them.
I haven't encountered any errors during the creation process, neither in the Pod Shell console nor in the web UI console.

This issue has been present from the very beginning since I started using Home Assistant on TrueNAS Scale. Until now, I wasn’t actively using automations, but I would like to resolve this so I can use the feature as intended.

What could be causing this behavior? Are there any specific steps I can take to debug further?

I’m attaching some screenshots to better illustrate the issue. Please let me know if additional information is needed or if there’s anything else I should check.
![2](https://github.com/user-attachments/assets/0ad04130-c462-47d5-aee9-aba7b7af4cc7)
![3](https://github.com/user-attachments/assets/a1b23841-8b12-4d1b-9b8c-55cd12dfbfe6)

**Comment by stavros-k** [comment]
Check the difference in the configuration.yaml between working and not working setup.
It will probably have a some extra includes there
