### ISSUE TITLE
Is it possible to top apps migration tutorials?

### ISSUE THREAD

**Issue by toseeu** [truenas/charts#2951]
After I upgraded my trueNAS from 24.04 to version 24.10.2, I found that all the applications are not working. I don't know what to do to get all the apps back. I couldn't find any tutorials on how to do it. In the end, I had to give up on the update and choose to boot from 24.04.
***
Request a tutorial on migrating to a new version.

**Comment by stavros-k** [comment]
Hello, without exact details and logs, we cannot help identify the issue.
There isn't something to make a tutorial about. Its all automated.
