### ISSUE TITLE
How to check if the Minio domain is properly set up - issue resolving host-style bucket names

### ISSUE THREAD

**Issue by vtosevski** [truenas/charts#2952]
Hi everyone,

For learning purposes I have deployed the Minio application (App Version: 2024-11-07T00-52-20Z, Chart Version: 2.0.25 ) on my Truenas SCALE (Dragonfish-24.04.2.5). At configuration step I have defined the domain, as I understood this is the requirement if one wishes to use host-style bucket names.

![image](https://github.com/user-attachments/assets/14ea3423-40aa-46bd-86de-7d4f0ad5a2de)

The application deploys successfully but applications that require host-style bucket address don't work. For instance Synology HyperBackup. Path-style name is recognized, host-style isn't.  The host-style URL is ping-able from that machine, so DNS appears OK. I am not good with kubernetes to meaningfully troubleshoot the deployment on Truenas. When I start a shell in the container and use `env`, I don't see domain among the listed environment variables. How do I check if the host-style bucket naming works well on my server?

Thanks!
Vinko

**Comment by vtosevski** [comment]
Hi everyone,

Providing an update, for posterity, perhaps. I have removed the domain from the above field and manually added the environment variable MINIO_DOMAIN

![image](https://github.com/user-attachments/assets/321d0ee2-6921-4631-b602-159105bfd761)

This solved the issue for me. Also, now, listing environment variable from the container's shell with `env` clearly shows the domain name.

Thanks,
Vinko

**Comment by stavros-k** [comment]
Hello, we only use `domain` field to set `MINIO_SERVER_URL` and `MINIO_BROWSER_REDIRECT_URL` variables.
Glad you got it working.
