### ISSUE TITLE
Nextcloud not working after TrueNAS Upgrade (URL Rewrite)

### ISSUE THREAD

**Issue by wabassis** [truenas/charts#2954]
I had Nextcloud  working fine on TrueNAS Dragonfish.
After upgrade to Eletric Eel the Nextcloud App is not working correctly.

Nextcloud running on port 9001
![image](https://github.com/user-attachments/assets/3acf58e1-8d32-496f-94f1-2fe479353140)

Nginx running on port 30022 (External access)

![image](https://github.com/user-attachments/assets/6e730bc6-9235-41db-8635-37d0a716d4e8)

I didnt change any config so far, before the upgrade everything was running fine.
Now, every time i tried to acess my nexcloud over internet the URL rewrites dont work.
 
Name:
[nextcloud]
App Version:
30.0.2
Version:
1.4.11

Can you guys would help me?

**Comment by stavros-k** [comment]
Please share more details.
Logs, errors, screenshots of what's happening etc.

Also you can check nextcloud's config.php file to make sure everything is correct.
Nextclolud also have its own log file in the html directory (nextcloud.log). Check this too.

Thanks

**Comment by wabassis** [comment]
@stavros-k I solve the problem.
The fix was just putting de port to the host field.

![image](https://github.com/user-attachments/assets/922fff5a-c23a-43db-9e67-17f9cf719b40)

Thanks!
