### ISSUE TITLE
Update the postgreSQL version of Nextcloud

### ISSUE THREAD

**Issue by JimmyLiang-lzm** [truenas/charts#2962]
Hello there,
Are there any plans to update  **postgreSQL** version of **Nextcloud**?
Currently, Nextcloud's official HELM already supports postgresql up to **version 15.5.0**.
[https://github.com/nextcloud/helm/blob/main/charts/nextcloud/Chart.yaml](https://github.com/nextcloud/helm/blob/main/charts/nextcloud/Chart.yaml)
But I now find that our Nextcloud's postgreSQL **only supports** version 13.1.

At present, I have found that the problem of low postgreSQL version will affect the response rate of Nextcloud Memories plug-in, and an error will be reported when running the optimization solution of Memories plug-in....
[https://github.com/pulsejet/memories/issues/1179](https://github.com/pulsejet/memories/issues/1179)

**Comment by stavros-k** [comment]
See https://github.com/truenas/apps/issues/342

Thanks
