### ISSUE TITLE
Unable to add environment variables to home-assistant chart

### ISSUE THREAD

**Issue by suredesigntshirts** [truenas/charts#2971]
VERSION: TrueNas SCALE 24.04
HomeAssistant Version: 2024.11.3
Chart Version: 2.0.53

I'm having this issue when attempting to add environment variables to the home assistant chart.

``
[EFAULT] Failed to update App: WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml Error: UPGRADE FAILED: template: home-assistant/templates/common.yaml:6:38: executing "home-assistant/templates/common.yaml" at : error calling include: template: home-assistant/templates/_home-assistant.tpl:35:27: executing "home-assistant.workload" at <$env.name>: can't evaluate field name in type interface {}
``

This user on reddit is also having the issue:
https://www.reddit.com/r/homeassistant/comments/1er5dok/need_some_help_with_making_configurationyaml/

How to re-create?
Attempt to add an environment variable in the Apps UI. Save and it should fail.

**Comment by stavros-k** [comment]
Please share a screenshot of the config entered.
