### ISSUE TITLE
autobrr installation from app selection does not work.

### ISSUE THREAD

**Issue by Tontze** [truenas/charts#2986]
2024-12-09 06:22:40.043168+00:00{"level":"error","module":"http","error":"securecookie: the value is not valid","time":"2024-12-09T08:22:40+02:00","message":"Auth: Failed to create cookies with attempt username:

![2d7b33e41470e6b966a20948ed73c5ba28291f5b](https://github.com/user-attachments/assets/a81d8b04-9700-4aca-8334-318ef2c88d78)

**Comment by stavros-k** [comment]
Please provide more details.
What you do to get that? Are those the ONLY logs?

**Comment by Tontze** [comment]
It is a permission issue i believe. I managed to get it working by installing it through docker compose yaml with uid/gid 0:0, and then chowning dir to 568:568 and changing yaml accordingly. But, i dont know if its related, then i got every  kind off "rss protocol not supported" etc when trying to configure something to download..

**Comment by stavros-k** [comment]
I just tried to install it and worked fine.

Remember that if you use host path you have to manage permissions yourself.
If you can still reproduce it with ixVolumes feel free to ping me and I'll re-open to investigate more.

Thanks
