### ISSUE TITLE
Can't specify NIC or VLAN or host network for charts/charts /home-assistant

### ISSUE THREAD

**Issue by moebis** [truenas/charts#3003]
Because the main NIC on TrueNAS Scale uses mDNS, we are unable to use the HomeKit Bridge feature in Home Assistant unless you turn off mDNS. If you use TrusNAS Scale for Time Machine backups, you cannot turn off mDNS. So the only option left would be to bind the docker container to a different 2nd NIC or VLAN. 

With HomeBridge docker you are able to do this and it works perfectly, the bridge to HomeKit gets setup. So it must be possible, it just a missing configuration option in this custom/community version of Home Assistant. Would it be possible to support this? Thanks.

**Comment by stavros-k** [comment]
Hello, for binding to specific IP per port, you can follow https://github.com/truenas/apps/issues/787
or for custom networks https://github.com/truenas/apps/issues/743

Home assistant (or other apps that use some dependency like database, redis or a worker) cannot currently use host network as it will break the database connection.
