### ISSUE TITLE
Machinaris does have permission issues.

### ISSUE THREAD

**Issue by Supermagnum** [truenas/charts#332]
Hello, my machinaris does not want to plot.
I am running the latest Truenas scale.

machinaris
v0.6.9_1.1.3

Ecc ram available: 58 Gib CPU: 2 X intel E5-2650 0 @ 2.00GHz

One 2TB sata spinning disk with the following paths mentioned below ( host path for config and plots)
The pod/docker is set up as follows per this guide: https://github.com/guydavis/machinaris/wiki/TrueNAS

Host Path for Machinaris Configuration Volume * /mnt/Shia/config

Host Path for Machinaris Plots Volume * /mnt/Shia/plots

http://192.168.132.10:9003/index shows plotting idle and farming active .

http://192.168.132.10:9003/plotting/jobs shows plotting running but no jobs. The workers tab on the same page shows: No plotting disk stats recorded recently for 0.0.0.0. Please check that valid plotting paths (aka "tmp") are set in the worker's Plotman config on the Settings | Plotting page.

http://192.168.132.10:9003/workers shows: truenas chia fullnode

plotter config https://pastebin.com/CxJzBstL

Also, my wallet appears to not be synced even if the nodes are synced.

plotman log says: cat 2022-02-11T04_05_21.184112+00_00.plot.log
Failed to write to finaldir directory: '/plots1/'

plotman.log: Starting plot job: chia_plot -n 1 -k 32 -r 4 -u 128 -x 8444 -t /plotting/ -d /plots1/ -v 128 -K 1 -f b9aec8206ad1a4493ddae6abbcbdd10e37b42566d5dc2e2295fbbe3d69a712040ba87bf6d70a09b9722b8f7bbda422a5 -p a62f4c1cae774f9f6122c0d7747969020f6a3b7d6350429595dc56f00ae77f72c4e28fcb643557c05ae04217f3f95ebf ; logging to /root/.chia/plotman/logs/2022-02-11T09_56_03.781093+00_00.plot.log

Blockchain Status: Full Node Synced

It seems that the directories are not created or mapped correctly, or there most likely is permission related.

I propose that  the Machinaris app get the option to set the correct acl/permissions automatically, like this Sonarr example has.

![permissio](https://user-images.githubusercontent.com/4554462/153734755-174c0070-fe8e-44ad-a663-1954652038f9.png)

**Comment by Supermagnum** [comment]
I have tried to set the permissions manually, like this.. But still the same issue with Failed to write to finaldir directory: '/plots1/'
![Skjermbilde fra 2022-02-13 00-41-20](https://user-images.githubusercontent.com/4554462/153750138-17a0b765-bdf8-40c5-a9ba-24f10bcac646.png)

**Comment by stavros-k** [comment]
I'm closing this issue as `Machinaris` will no longer be maintained officially.
Thanks
