### ISSUE TITLE
Nextcloud missing smbclient debian package on ngix container

### ISSUE THREAD

**Issue by frell** [truenas/charts#373]
In order for nextcloud to make use of the common external storage feature, it requires the smbclient debian package to be installed.

Manually installing it via apt to the ngix container resolves the issue. 

Thanks.

**Comment by sonicaj** [comment]
@frell please open up an issue with upstream nextcloud team so that they can add it in the docker image. We can't unfortunately do it as it would mean maintaining our own version of nextcloud based on upstream with just this package addition. Thanks!
