### ISSUE TITLE
HTTPS: Securing Nextcloud with SSL?

### ISSUE THREAD

**Issue by docwhite** [truenas/charts#43]
Hello, thanks for taking the time to compile the various apps.

I wanted to know how can you manage the Nextcloud application to be run under HTTPS instead of HTTP.

I can think of the solution of using Cloudflare's Free SSL, but I was wondering it it would be possible to configure TrueNas SCALE or contributing to the chart to add some sort of reverse proxy in front that simply enables SSL.

I can think of Caddy's [Automatic](https://caddyserver.com/docs/automatic-https) HTTPS feature, maybe bringing it into the chart would be an option? Or maybe there's no need and we can benefit somehow from the TrueNAS SCALE certificate management system...

Can you configure reverse proxying from TrueNAS SCALE outside Kubernetes, or should I consider working within Kubernetes when it comes to reverse proxying the requests?

What are your views on that?

**Comment by sonicaj** [comment]
@docwhite can you please create a suggestion ticket at https://jira.ixsystems.com ? We track open items there

**Comment by docwhite** [comment]
I have been reading more about it and it seems what I am interested with in k8s terminology is an **Ingress**.

I am happy to help and investigate how to add for instance the nginx ingress into the nextcloud catalog app.

But I wanted to make sure the Helm chart is the place where should be done. I am not familizared with the whole architecture of TrueNAS, so maybe you guys already have something on levels higher up...

It would be awesome to customize reverse proxying for your apps maybe outside of the app itself.

Thanks and apologies for my writings which it's me thinking aloud.

**Comment by docwhite** [comment]
> @docwhite can you please create a suggestion ticket at https://jira.ixsystems.com ? We track open items there

Great! Doing that!

**Comment by sonicaj** [comment]
Yes that is accurate, although i see 2 solutions for this. You can perhaps use Ingress or maybe consume a certificate which is present in TN Scale Certificate's section for nextcloud and it should/can use https in that case. So both can be done, the latter is perhaps more easily achievable as we have not officially configured ingress in our k8s cluster yet. Btw we can do the same with ingress as well when we have added official support for it. Anyways, both suggestions are welcome :)

**Comment by docwhite** [comment]
> or maybe consume a certificate which is present in TN Scale Certificate's section for nextcloud and it should/can use https in that case

That makes much more sense!

I will investigate how to achieve passing the TN certificates to the SSL configuration of Nextcloud.

**Comment by sonicaj** [comment]
Cool, please have a peek at https://github.com/truenas/charts/tree/master/test/minio/1.2.1 - minio consumes TN's certificate subsystem to secure traffic over HTTPS. Good luck with it ;)

**Comment by docwhite** [comment]
Created the ticket: https://jira.ixsystems.com/browse/NAS-109886

**Comment by docwhite** [comment]
Here's some interesting links:

* https://docs.nextcloud.com/server/21/admin_manual/installation/harden_server.html?#use-https 
* https://docs.nextcloud.com/server/21/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=ssl#proxy-configurations 
* https://docs.nextcloud.com/server/21/admin_manual/installation/source_installation.html#enabling-ssl 
* https://docs.nextcloud.com/server/21/admin_manual/configuration_server/occ_command.html?highlight=ssl#security

**Comment by docwhite** [comment]
Could you please point me to where the `defeinitions` are?

In `features_capability.json` it shows:

```
"definitions/certificate": {
    "stable": {"min": "21.04-ALPHA"},
    "nightlies": {"min": "21.02-MASTER"}
  },
```

I was wondering where could I inspect those.

**Comment by sonicaj** [comment]
@docwhite you can consider these attributes as special invocations where the system modifies the schema of the attribute in question and adds some more interesting data. In the specific case you have pointed out, if that is specified, TrueNAS will show certificates configured/found in the TrueNAS database for the field/attribute in question ( please refer to minio tests train questions.yaml to see it in action ).
`feature_capability.json` is just a matrix to keep track of which feature was added when and is supported till when.

**Comment by docwhite** [comment]
Thanks for your answer. Yes, that was my intuition, it augments the object. That's why I was curious about where in the code base does the logic for this augmentation live. You mentioned TrueNAS database, but I believe there must be some business logic too. I ask for this because I'd like to see how it expands the certificate path into the various attributes. But if this code is difficult to get or understand don't worry, I can just take the ones used by minio 1.2.1 as reference.

By the way, what is a train? Is it k8s terminology? I guess now there's two trains, the official and the test, but I was curious about the name.

Thank you!

**Comment by sonicaj** [comment]
@docwhite the logic for conversion is done by TrueNAS, it's done here https://github.com/truenas/middleware/blob/82557c0046fcb9f67ea3215534046535b733d5f4/src/middlewared/middlewared/plugins/catalogs_linux/items.py#L233. I am not sure of what you are trying to achieve, this is just supposed to be specified simply and the system can make the changes itself, if you can let me know a bit about that, that would be good.

About trains, the idea is to have like a stable version of the catalog and a development version of the catalog items. There can be others as well and can be created/updated at will. It's not related to kubernetes at all.

**Comment by docwhite** [comment]
OK, I am not sure I understand, but I believe I wouldn't need to get that deep to just make use of that definition.

The problem I'm having is that it won't allow me to use that definition.

When I create the app with the new field, just as you did with minio, I type in a `1`, because I cannot type and I do not know what to type. I was thinking of typing `/etc/certificates/freenas_default` or `freenas_default`, but I struggled, it only lets me type certain characters.

Apart from that if I type a `1` and hit `Save`, it errors with the following:

```
Error: [EFAULT] Catalog item version is not supported due to following missing features: 1) definitions/certificate For 'Stable' train: Minimum SCALE version: 21.04-ALPHA Maximum SCALE version: Latest available 'Stable' release For 'Nightlies' train: Minimum SCALE version: 21.02-MASTER Maximum SCALE version: Latest available 'Nightlies' release
```

My current train is `Current Train: TrueNAS-SCALE-Angelfish-PRERELEASE`.
My current version is `OS Version:TrueNAS-SCALE-21.02-ALPHA.1`.

How could I keep developing?

Thank you.

**Comment by sonicaj** [comment]
@docwhite please update your TrueNAS Scale system to latest nightlies as that feature is not supported on your OS version. If the problem persists, please let me know, thank you.

**Comment by Ornias1993** [comment]
For quick reference:
TrueCharts already supports HTTPS for all Apps, using traefik Ingress. For the official plugins (as there won't be that many for some time), adding certificates manually is fine... but it's a rather non-standard way of doing things, in the long term and bigger scale ingress is the way to go :)

The new version (staging branch, will be merged into master as soon as 21.04 launches) also uses TrueNAS SCALE certificates to do so. 

https://github.com/truecharts/apps

also @sonicaj I think you can also just disable "wiki, projects and issues" from the settings page. But maybe you need @kmoore134 his admin credentials to do so.

**Comment by docwhite** [comment]
> The new version (staging branch, will be merged into master as soon as 21.04 launches) also uses TrueNAS SCALE certificates to do so.

That's great news to hear!

Is there any way I can test it before the 21.04 release? I am on the nightlies train. The `staging` branch I imagine it's the branch for the `truenas/apps` project. I know how to install specific branches of the `trenas/charts` projects. @sonicaj showed me how to install specific branches of a catalog, but I imagine, @Ornias1993 , that this changes in `staging` are in a higher up project? I don't want to bug you guys, so I can wait, but I'd be curious to jump in earlier and give it a whirl and help out with the testing.

Thank you!

**Comment by Ornias1993** [comment]
@docwhite 

> Is there any way I can test it before the 21.04 release? I am on the nightlies train.

A week ago you could, but currently we prepared for some changes to the UI that aren't merged into nightly yet. So currently our staging branch can not be added in the UI. More information is available in the PR:
https://github.com/truecharts/apps/pull/216

>  I know how to install specific branches of the trenas/charts projects. @sonicaj showed me how to install specific branches of a catalog

to be honest, @sonicaj showed you the most complicated way to do so...

- Go to you shell of choice (either SSH or the TrueNAS webui shell)
- enter `cli`
- enter app `catalog create repository="https://github.com/truecharts/truecharts" label="TrueCharts"`
or for the staging branch : 
`catalog create repository="https://github.com/truecharts/truecharts" label="TrueCharts" branch="staging"`

This CLI includes tools that help you find the right arguments, thats why it's easier...
To sync a catalog using the CLI (from the top of my head):
`catalog sync_all`

> that this changes in staging are in a higher up project?

Everything is ready on the staging branch, but we implemented some changes faster than the related UI changes got merged into TrueNAS this time... so give it a week or two and you'll be able to use the staging branch again on Nightly. ;-)

>  I don't want to bug you guys

Don't worry to do so, feel free to file a discussion, issue or report on the staging->master PR :)

**Comment by docwhite** [comment]
@Ornias1993 Thanks for the detailed response and for the second way of interacting with catalogs! I will wait and keep an eye on the PR! I'm so happy to see your work on that area coming soon.
