### ISSUE TITLE
172 ip address

### ISSUE THREAD

**Issue by dkuchay** [truenas/charts#430]
Trying to install a series of apps and while nextcloud works I cant get nzbget, sonarr, radarr, or lidarr to install. They all fail on a 172 ip address connection test that fails. Is it that nextcloud can rewite its url and the others cant? If my suspicion is right why the 172 hard coded? Never have seen that ip range in a residential setting. Usually 10.x.x.x or 192.x.x.x. Cant install any of the apps. Looking at docker on Synology and there is one check box for "use host network". Allegedly this gets the app the same IP as the host and the port maps. What would the equivalent setting in the settings panel and why is that area so complicated? Whats ingress? Cant adapt coming from synology. Just want an easy to use nas. This interface for installing apps in Truenas-Scale is far from. Ive seen documentation on linking these apps with URL as its not possible with IP? Sigh. How is this kubernetes stuff a step forward? Sorry, dont mean to be sour but after 5 hours of trying to get one of the above apps to install I think I am about done with truenas. Everything to this point was not bad. Charts has no documentation, just a series of circular click loops on three or four pages that all lead here.

**Comment by dkuchay** [comment]
Thank you for your reply. I will. Tinkered with more and in application advanced settings my node IP address was stuck on 0.0.0.0 and not changeable. Thinking this may have caused apps to take internal container address and fail on self check. Using two port intel nic card. Some tutorials I saw mentioned setting this node IP address to the ip of the host to map the app to host ip. If this is true and I couldn’t get this off 0.0.0.0 even after rebooting the problem may not be with truecharts.

**Comment by packruler** [comment]
To select a non 0.0.0.0 bind IP I think you will need to apply a static IP to those Network Interfaces in the TrueNAS UI. But for simplicity utilize the TrueCharts system and read over their documentation. Their systems will handle setting up a port binding for you without host binding.

**Comment by sonicaj** [comment]
@dkuchay kubernetes has a CIDR which it uses to deploy pods - you can configure that value via advanced settings in the UI. About the bind IP, @packruler statement is accurate that you need static IP in order to configure that.

Now about the apps failing, it seems like it's an app issue rather then a TrueNAS SCALE issue as nextcloud deployed fine for you. Can you provide more context about the failing apps ? Were they deployed via `Launch Docker Image` button in the UI or are you using some other catalog i.e TrueCharts perhaps ?

**Comment by dkuchay** [comment]
With static ip set on one nic I revisited apps settings advanced and still could not set ip for node. Stuck on 0.0.0.0. Tried each nic from dropdown. If I can not set this for host ip it would make sense that an app that can rewrite its url could discover that ip and the url I gave it matched at my local dns. Apps that did not have url rewrite module enabled / supported failed to deploy as their ip defaulted to internal. If this node IP address is stuck on 0.0.0.0 and even with static ip please let me know what you would like for me to ask of truecharts.

**Comment by sonicaj** [comment]
I'm sorry, i don't understand the problem. Is your problem that you are unable to set the statically configured IP for Apps or is it some thing else ?

**Comment by dkuchay** [comment]
The issue is that the ip for nodes in apps settings advanced is stuck on 0.0.0.0 and cannot be changed even with static ip set on both nics.

**Comment by sonicaj** [comment]
To confirm @dkuchay did you configure static IP via TrueNAS UI ?

**Comment by Ornias1993** [comment]
> even after rebooting the problem may not be with truecharts.

You still seem to think this is somehow related to TrueCharts.
These are **only** the official iX-Systems Apps, we're not present here nor can you get support for our Apps here (like sonarr, radarr etc), please carefully read our website if you still think this is related to TrueCharts.

**Comment by dkuchay** [comment]
As well as via MAC address at switch, yes.

**Comment by Ornias1993** [comment]
@sonicaj or @Qubad786 I think at this point IF it's a bug it needs to be -> Jira and closed here.
If it's not it needs to be closed anyway.

**Comment by sonicaj** [comment]
@dkuchay please create an issue at ixsystems.atlassian.net and do attach a debug of your system with the output of `midclt call interface.query | jq` command as well. Thanks!

**Comment by dkuchay** [comment]
Summery, when one reinstalls the operating system it does not check the array for previous data stores. When I reinstalled the data store went corrupted. Deleting and reinstalling works better however I am no longer with truenas installed. I’m not rich. Can’t buy all hdd’s in one swoop so I installed commercial Linux with btrfs file system that can be added to same array. Industrial kubernetes not desired for home use. Don’t like docker running as root. I could go on. Close this ticket please as it’s no longer relevant, I don’t and won’t use truenas again. Sent from my iPhoneOn Oct 11, 2022, at 10:25 AM, Waqar Ahmed ***@***.***> wrote:﻿
@dkuchay please create an issue at ixsystems.atlassian.net and do attach a debug of your system with the output of midclt call interface.query | jq command as well. Thanks!
