### ISSUE TITLE
Unhealthy charts break all TrueNAS chart updates

### ISSUE THREAD

**Issue by packruler** [truenas/charts#431]
In the last week or so I have noticed that a growing (though slowly) number of charts are unhealthy. I have a feeling that this is a local issue considering I have found no mention of anything similar in sporadic deep searching dives during this period.
I am getting this warning in my notifications:
```
WARNING
minio (charts train), netdata (charts train), collabora (charts train), chia (charts train), nextcloud (charts train) Applications in OFFICIAL Catalog are not healthy.
2022-04-20 08:56:17 (America/Denver)
```

When I check the Apps > Available Applications tab I see only the unhealthy apps mentioned:
![Screen Shot 2022-04-20 at 9 40 03 AM](https://user-images.githubusercontent.com/770373/164269681-a9044847-ee8a-407c-9c3e-336bcd7a404e.png)

Luckily I am able to view and update the existing instances of these apps that I setup prior to this issue arising.

I am happy to debug more but I have hit a limit on my knowledge and I am not sure what I can do to debug this issue. Is there a way to clear the cache of TrueNAS charts locally?

**Comment by sonicaj** [comment]
@packruler can you please create an issue at https://jira.ixsystems.com and kindly make sure to attach a debug of the system. Something seems amiss with your local cloned version of the catalog but we'll confirm ofc and go from there. Thanks!
