### ISSUE TITLE
Developer guide for this project would be very helpful

### ISSUE THREAD

**Issue by docwhite** [truenas/charts#44]
Hello :)

Could I ask how do you manage to iterate the development of this project? I would like to fork the project and have a little play with it to see if I could get Nextcloud to have HTTPS.

I am not familiarized with the development practices within the project.

Are there any resources out there that might help or point on how to test my changes in case I were to fork it?

I am reading https://www.truenas.com/docs/hub/scale/dev-notes/#deploying-kubernetes-workloads and they say:

> Here is an example of deploying the Plex docker image:

```
midclt call -job chart.release.create '{"catalog": "OFFICIAL", "train": "test", "item": "ix-chart", "values": {"image": {"repository": "plexinc/pms-docker"}, "portForwardingList": [{"containerPort": 32400, "nodePort": 32400}], "volumes": [{"datasetName": "transcode", "mountPath": "/transcode"}, {"datasetName": "config", "mountPath": "/config"}, {"datasetName": "data", "mountPath": "/data"}], "workloadType": "Deployment", "gpuConfiguration": {"nvidia.com/gpu": 1}}, "version": "2010.0.1", "release_name": "plex"}'
```

Where does it get it from? Could I point to a local checkout of that chart?

**Comment by sonicaj** [comment]
Hi @docwhite, thank you for your interest. So basically you can fork this repository and add your repository as a separate catalog with
```
midclt call catalog.create '{"label": "docwhite", "repository": "repo uri", "branch": "master"}'
```

So now it should show up in the UI and you can make adjustments to nextcloud chart. You can verify if TN recognizes your chart as valid wrt valid format and `questions.yaml`, you can run
```
midclt call catalog.validate DOCWHITE
```

You don't need to use CLI now to create the chart release and UI should render your `questions.yaml` automatically dynamically :) Let us know please if you run into issues. Thanks

**Comment by sonicaj** [comment]
Added this information in dev notes as well :) https://github.com/truenas/documentation/pull/704

**Comment by docwhite** [comment]
Thanks @sonicaj for your reply.

I will do that.

Is there any help commands to whatever else I can do with the catalog calls? `midclt call catalog.help` or any way I could see what commands does it offer.

Thanks for updating the dev notes!

**Comment by sonicaj** [comment]
@docwhite you can access documentation for TrueNAS at `http://SYSTEM_IP/api/docs/` and there please refer to `catalog.*` endpoints, they add more detail to the parameters in question and what the endpoint does.
