### ISSUE TITLE
 Launch Docker Image not exposing ports to node

### ISSUE THREAD

**Issue by exander77** [truenas/charts#440]
When I ran docker image through Launch Docker Image feature, the ports are not exposed to node or some internal routing issue is in play as I can't even access the application locally through ClusterIP.

```
$ sudo k3s kubectl get services -n ix-alpha

NAME              TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE

alpha-ix-chart   NodePort   172.17.213.61   <none>        9093:9093/TCP   36s

$ curl http://172.17.213.61:9093

curl: (7) Failed to connect to 172.17.213.61 port 9093: No route to host
```

When I expose application to dedicated IP then the connection through local network works, but TrueNAS cannot access the IP as well:

```
$ curl http://10.0.0.100:9093

curl: (7) Failed to connect to 10.0.0.100 port 9093: No route to host
```

**Comment by exander77** [comment]
Ok, for this to work, you need to "Provide access to node network" and disable rolling update.

**Comment by sonicaj** [comment]
@exander77 can you please create an issue at https://jira.ixsystems.com ? Please make sure you have reproduce the problem and clarified what your current configuration is. You should attach the output of the command `midclt call chart.release.get_instance 'APPNAMEHERE' | jq` and the debug of the system as well right after reproducing it. Thanks!
