### ISSUE TITLE
PLEX deployment stuck in loop when set to "Required Encryption" 

### ISSUE THREAD

**Issue by cdgriffith** [truenas/charts#50]
The deployment only checks on http https://github.com/truenas/charts/blob/master/charts/plex/1.1.0/templates/deployment.yaml#L51

In plex you can set network connects to force HTTPS (Settings > Network > Secure Connections > Required)

Which can result in the probe to continuously fail even on clean starts, will see messages like: 

```
Readiness probe failed: Get "http://<server>:32400/identity": dial tcp <server>:32400: connect: connection refused
```

It needs to have at least a fallback to `https` if `http` fails.

**Comment by sonicaj** [comment]
Thank you @cdgriffith for letting us know about it. This has been fixed by https://github.com/truenas/charts/pull/42 but hasn't made it to `charts` ( stable ) train yet.
