### ISSUE TITLE
How to install library to nextcloud app?

### ISSUE THREAD

**Issue by b10102016** [truenas/charts#51]
Hi,

I recently installed the Nextcloud, and it works like a charm, thanks for your great work!

However, when I trying to install app "Face Recognition", it said "App "Face Recognition" cannot be installed because the following dependencies are not fulfilled: The library pdlib is not available. The library bz2 is not available."

Could you give a guide to install these library?

Thanks
Ian

**Comment by sonicaj** [comment]
@b10102016 we are using official nextcloud docker image and it seems they would not have it available. I would advise you to create an issue with them so that they can include these in the official docker image. Please let me know if you think this might be an issue on our end. Thank you

**Comment by sonicaj** [comment]
Actually, can you please confirm if you are referring to an application "Face recognition" and not something which might be in nextcloud ? If yes, can you please confirm in which catalog the application is coming from as it's not provided with the OFFICIAL one ?

**Comment by b10102016** [comment]
The app is installed to the Nextcloud. For typical docker image, I can modify it (ex: install the dependency from apt or manual compile) and commit change to the image, but I don't know how to do that on Kubernetes. May I ask for a guide for this?

Thanks

**Comment by Ornias1993** [comment]
Also a note here:
PDLib is not supported by nextcloud 23 docker due to it not being available in binary form for php8
