### ISSUE TITLE
NextCloud: Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it

### ISSUE THREAD

**Issue by GitPullNow** [truenas/charts#528]
Please add the php-imagick SVG support.

`Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it.`
![image](https://user-images.githubusercontent.com/94388268/174147470-365fb640-2017-4cc8-9d48-8acbcd177dac.png)

Version
![image](https://user-images.githubusercontent.com/94388268/174147797-7eebe707-2943-4924-8aff-b8b53fcba8fb.png)

**Comment by sonicaj** [comment]
@GitPullNow we use official nextcloud image. Please create an issue upstream with nextcloud to add this in their docker image. Thanks!
