### ISSUE TITLE
NextCloud: Many cronjob containers keep spawning after restarting pods

### ISSUE THREAD

**Issue by GitPullNow** [truenas/charts#529]
After enabling the cronjob option that was added I see that it seems to keep spawning cronjob containers which results in cronjob no longer working for NextCloud.

![image](https://user-images.githubusercontent.com/94388268/174148011-51e601f6-e97c-4a59-90c8-a49b27cbc852.png)

Version:
![image](https://user-images.githubusercontent.com/94388268/174148177-e3e350bc-34ab-4869-9436-24ca327fa988.png)

**Comment by Ornias1993** [comment]
Every run of the Cronjob *should* spawn a new container. That's normal.

So it's not clear how you came to the conclusion that this would be breaking things.

**Comment by Ornias1993** [comment]
@sonicaj or @Qubad786 can be closed.

**Comment by sonicaj** [comment]
@GitPullNow we only keep failed cronjob pods around - if you are still seeing this behaviour on latest app version, please let us know on https://ixsystems.atlassian.net ( kindly make sure to attach a debug of your system ). Thanks!
