### ISSUE TITLE
Emby: 4.8.0.x are betas

### ISSUE THREAD

**Issue by alucryd** [truenas/charts#555]
Hi there, it looks like emby was bumped to 4.8.0.x, however these are betas and the last stable release is 4.7.5.0. In general, when the third digit is a 0 it means that it is a beta as far as emby is concerned.

Is it possible to downgrade to 4.7.5.0? I can make a PR if you'd like. Downgrading should not be a problem as databases are compatible across these 2 versions.

**Comment by Qubad786** [comment]
The version has been changed and upgrade strategy will be updated as well to account for the tag naming scheme wrt stable releases. Thanks @alucryd!
