### ISSUE TITLE
Missing the ability to define docker image version

### ISSUE THREAD

**Issue by Saberwolf64** [truenas/charts#60]
in the latest release of plex app user are now unable to define plex docker image version even after manually changing version number oh local copy

**Comment by sonicaj** [comment]
@Saberwolf64 that is desired behavior. We would be bumping docker image versions for users.

**Comment by Saberwolf64** [comment]
please provide a way for manual override you are behind by 4 days on current image to latest for user that like to be up to date

**Comment by sonicaj** [comment]
@Saberwolf64 we are looking to automate this so that we are not that far behind when upstream has newer tags available. I appreciate your concern, thank you for letting us know about it.

**Comment by Saberwolf64** [comment]
Thanks for clarification change tag to latest then you will always have the most current one
________________________________

**Comment by Saberwolf64** [comment]
Then you can add a known default as a backup or roll back
________________________________
