### ISSUE TITLE
Plex: not all Plex server ports are exposed

### ISSUE THREAD

**Issue by zacbrown** [truenas/charts#602]
Hi,

I'm having trouble with the Plex chart due to it not exposing all the ports that Plex supports[0](https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/).

As currently setup, it only exposes the primary port - 32400. However, Plex includes a DLNA server as well as some other auto-discovery ports:

```
UDP: 1900 (access to the Plex DLNA Server)
UDP: 5353 (older Bonjour/Avahi network discovery)
TCP: 8324 (controlling Plex for Roku via Plex Companion)
UDP: 32410, 32412, 32413, 32414 (current GDM network discovery)
TCP: 32469 (access to the Plex DLNA Server)
```

I'm not familiar with Helm charts and wasn't sure how to hack this into the chart.

**Comment by Ornias1993** [comment]
- DLNA cannot work out-of-the-box anyway (cannot do so cross NAT)
- The older discovery protocol also cannot work out-of-the-box (cannot do so cross NAT) and is depricated
- GDM discovery isn't really needed when a token is used on install. Simply put: Your client will fetch the announced url/ip from the plex servers and broadcasts to all of those, untill one responds which works quite well.

There are 3 types of discovery for plex:
- Old Discovery (wont work with kubernetes)
- GDM (Might technically work) discovery without being logged in
- Discovery using your Plex account

**Comment by Ornias1993** [comment]
@sonicaj or @Qubad786 can be closed.

**Comment by sonicaj** [comment]
@zacbrown i am closing this issue in light of the comments above, please feel free to create a suggestion ticket at https://ixsystems.atlassian.net if you think we are missing some aspect. Thanks!
