### ISSUE TITLE
Chia App Version Bump

### ISSUE THREAD

**Issue by bslavin** [truenas/charts#62]
It looks like Chia has bumped versions - 1.1.6

https://github.com/Chia-Network/chia-blockchain/releases

Would it be possible for you to bump the version of the official, or maybe allow us to do this on our local app? 

The request is related to known syncing issues in the earlier version. Reports here https://www.reddit.com/r/chia/comments/m674ea/full_node_stuck_in_not_synced/ state they are resolved in the new client.

**Comment by sonicaj** [comment]
@bslavin chia does has an updated docker image yet - https://github.com/orgs/chia-network/packages/container/package/chia

**Comment by sonicaj** [comment]
I had created an issue upstream about it https://github.com/Chia-Network/chia-docker/issues/58

**Comment by jfturcot** [comment]
1.1.6 docker image is now available, hopefully this will fix my Full Node which haven't been able to completely sync since I rebooted my server.
https://github.com/orgs/chia-network/packages/container/chia/2666209?tag=1.1.6
