### ISSUE TITLE
Nextcloud: possibility to allow bigger file uploads

### ISSUE THREAD

**Issue by Vrtak-CZ** [truenas/charts#691]
Currently webdav ending with `413 Request Entity Too Large`. It probably could be done by setting `PHP_UPLOAD_LIMIT` env variable.

**Comment by sonicaj** [comment]
@Vrtak-CZ can you please create a ticket at ixsystems.atlassian.net ? We can cater to this then by allowing users to configure this. Although iirc you should be able to set up that env variable right now yourself as required. Thanks!

**Comment by Vrtak-CZ** [comment]
fixed by https://github.com/truenas/charts/pull/722
