### ISSUE TITLE
Storj Chart needs to expose TCP and UDP 

### ISSUE THREAD

**Issue by Darkknight33** [truenas/charts#762]
With the storj app installed, I am unable to get Quic function because UDP is not being forwarded. Looking at the installed application indicates: Used Ports: 20909\TCP, 28967\TCP. It should be: 28967\TCP/UDP. There does not seem to be an obvious way to affect this change from the GUI.

**Comment by Qubad786** [comment]
@Darkknight33 `kubectl` correctly reports that relevant UDP ports are functioning
```
ix-storj-with-secrets   storj-with-secrets   NodePort    172.17.0.232     <none>        25939:25939/TCP,25388:25388/TCP,25388:25388/UDP   49d
```
![Screenshot 2022-09-29 at 8 02 23 PM](https://user-images.githubusercontent.com/7848408/193067691-f8b5f420-a28d-4053-8f48-b76f014277ec.png)


And QUIC is working nicely..

**Comment by Darkknight33** [comment]
![image](https://user-images.githubusercontent.com/571187/193093741-6acf6167-7b53-46f9-9e6d-817e5a7dab36.png)

There is no user control for which protocols are forwarded. So, I believe the error is in the orchestration. 

![image](https://user-images.githubusercontent.com/571187/193094127-86a2d3ac-6c7a-411a-8702-e76e7915d853.png)

**Comment by Ornias1993** [comment]
You can try the TrueCharts storj-node app and see if that works more like you prefer?

**Comment by Darkknight33** [comment]
> You can try the TrueCharts storj-node app and see if that works more like you prefer?

Well, it's not really so much as 'work as I prefer' rather that installing it from the GUI currently presents a problem. 

The code [here](https://github.com/truenas/charts/blob/master/charts/storj/1.0.0/templates/service.yaml ) includes an entry for UDP, so that being the case, why is it not exposing UDP protocol when deploying? I am not familiar enough with the product yet to troubleshoot this problem solo.

**Comment by Qubad786** [comment]
@Darkknight33 if you look at the code you pointed out
```
{{ $ports = mustAppend $ports (dict "name" "tcp" "port" .Values.nodePort "nodePort" .Values.nodePort "targetPort" 28967) }}
{{ $ports = mustAppend $ports (dict "name" "udp" "port" .Values.nodePort "nodePort" .Values.nodePort "targetPort" 28967 "protocol" "UDP") }}
```
both TCP and UDP are supported and as i shared in the screenshot in my earlier comment - kubernetes also correctly reports that both TCP/UDP are forwarded and storj QUIC is working nicely..

Can you confirm if this might be an issue on your router end perhaps where you are configuring port forwards to your SCALE machine?

**Comment by Darkknight33** [comment]
Here is the specific firewall rule:
![firewall rule](https://user-images.githubusercontent.com/571187/195340835-70147542-2c2a-481e-9233-a7d4f1d79fef.png)

Here is the same kubectl command you used, but showing UDP is _not_ forwarded:
![kubectl](https://user-images.githubusercontent.com/571187/195340842-a90ddbe6-f59d-429f-89aa-379f68715b16.png)

Here is docker environment variables from container showing no entries for UDP:
![environment](https://user-images.githubusercontent.com/571187/195340851-ee4eb14a-2871-4cb4-8d95-48d40e272ab4.png)

Not sure what else I can provide to demonstrate that UDP isn't being forwarded correctly. While I see that the code you posted does indeed include UDP, nevertheless when I deploy the app directly from the app catalog the result is that UDP isn't being forwarded.

**Comment by sonicaj** [comment]
@Darkknight33 can you share the output of the following command as well please ?
```
k3s kubectl describe -n ix-storj svc/storj
```

**Comment by Ornias1993** [comment]
> > You can try the TrueCharts storj-node app and see if that works more like you prefer?
> 
> Well, it's not really so much as 'work as I prefer' rather that installing it from the GUI currently presents a problem.
> 
> The code [here](https://github.com/truenas/charts/blob/master/charts/storj/1.0.0/templates/service.yaml) includes an entry for UDP, so that being the case, why is it not exposing UDP protocol when deploying? I am not familiar enough with the product yet to troubleshoot this problem solo.

What I meant with that is "It might not have this issue and you'll be off with less work involved"

**Comment by Ornias1993** [comment]
> > What I meant with that is "It might not have this issue and you'll be off with less work involved"
> 
> I appreciate that suggestion, but I do think the official application should work appropriately for other users as well. 

To be honest, that's somewhat a wrong expectation.
Considering they have a "not really functional" pihole app, because they don't want it exposed to port 53, which makes it useless for the VAST majority of users.

**Comment by sonicaj** [comment]
@Darkknight33 can you please create an issue at https://ixsystems.atlassian.net and kindly make sure to attach a debug of your system.

It's possible something might be wrong with the chart or your SCALE version and we might have to setup a teamviewer session if we can't spot it from the debug. Anyways, thank you for letting us know about it - looking forward to that ticket with debug. Thanks!
