### ISSUE TITLE
Nextcloud server app not configurable due to volume persistency

### ISSUE THREAD

**Issue by chrisfoster121** [truenas/charts#78]
I recently tired to install the Nextcloud app and was trying to set up https as per the documentation (Nextcloud documentation deems it mandatory). However, the files that need to be changed to do this are in docker volumes that are non-persistent. From what can tell there is no way to keep these files from being reset after a container restart. Please let me know if I am wrong or if there is a solution to this that I am unaware of.  

my system is as follows:

HP ProLiant 360e 16 core 32 thread server
4 drives (2 1tb mirrored, 2 2tb mirrored)
TrueNAS-SCALE-21.06-BETA.1

**Comment by sonicaj** [comment]
@chrisfoster121 can you please create a ticket at https://jira.ixsystems.com and please add information for what you tried ? We do not have added explicit https support yet for nextcloud but i think that would be good to move forward with.

**Comment by chrisfoster121** [comment]
Bug report added: https://jira.ixsystems.com/browse/NAS-111274

------------------

Additional info: 
The file that needs to be changed for this are the virtual host (VH) files for apache. Within the nexctcloud docker container, I believe the file resides in something like "/etc/apache/enabled-sites/". More information can be found here: https://docs.nextcloud.com/server/latest/admin_manual/installation/harden_server.html 

As the app is currently configured, the VH file is reset every time the container is restarted. This makes it difficult if not impossible to set up https as is required.
