### ISSUE TITLE
Is it possible to update docker images in these official charts?

### ISSUE THREAD

**Issue by jquiros2** [truenas/charts#808]
I'm using "official" Photoprism from these in Truenas Scale.

The docker image used seems rather old.  Is there a way to update the version while still using this catalog,  or should I use Truecharts which gives newer versions more quickly?  Or just use a regular docker image with "Launch docker image?"

Or should I fork this and edit version to be "latest" in the chart's yaml file?

**Comment by Qubad786** [comment]
@jquiros2 it should be fixed now - our update strategy was outdated for photoprism

**Comment by jquiros2** [comment]
Thank you @Qubad786!
I had made the same edits in ../ix-applications/releases/photoprism/charts but still worried about losing them on an update.  This seals it solid!
