### ISSUE TITLE
Plex Application failing to start

### ISSUE THREAD

**Issue by msdmcmurrian** [truenas/charts#810]
I have been getting this error for the last few weeks and have not found a solution to fixing it. No matter what I do Plex will not run.

s6-applyuidgid: fatal: unable to exec /usr/lib/plexmediaserver/Plex Media Server: No such file or directory

**Comment by LtDragon** [comment]
I'm having the same issue. I'm not sure what the issue is.
It was running correctly then just stopped working.

**Comment by sonicaj** [comment]
@LtDragon / @msdmcmurrian can you please create an issue at ixystems.atlassian.net ? ( kindly make sure to attach a debug of your system ) Thanks!
