### ISSUE TITLE
Nextcloud is missing SMB client.

### ISSUE THREAD

**Issue by johnhart96** [truenas/charts#843]
Hi Guys,
I use the nextcloud chart on my TrueNAS server for my business. I use the external storage with SMB but everytime I update it, it is missing the SMB extensions. I have to jump into the shell and run
`apt update`
`apt install samba smbclient cifs-utils`

Would it be possible to have this added to the docker image?

Thanks
John :)

**Comment by Ornias1993** [comment]
TrueNAS uses the official image without modifications.
It's actually kinda awkward that there is no official image with those modifications tbh.

The TrueCharts version (and image) does have those modifications included though :)

**Comment by sonicaj** [comment]
@johnhart96 we won't be maintaining a separate image for nextcloud - i would advise you to raise this issue upstream ( i have seen earlier reports of this there already though ), for us to maintain these packages and ensure they work out of the box with nextcloud is not something we are open to at the moment. Thank you :)

**Comment by Ornias1993** [comment]
> @johnhart96 we won't be maintaining a separate image for nextcloud - i would advise you to raise this issue upstream ( i have seen earlier reports of this there already though ), for us to maintain these packages and ensure they work out of the box with nextcloud is not something we are open to at the moment. Thank you :)

Agreed, it's an expodential amount of work...
