### ISSUE TITLE
[Syncthing] Sync does not work over IPv6 - Host Networking = ON

### ISSUE THREAD

**Issue by UnderEu** [truenas/charts#874]
Self explanatory title, the Syncthing (Official) app does not sync content over IPv6, the only thing working over v6 is the web interface (TCP 8384) and Listener (TCP 22000)

Port scanning from my computer to my server:

$ nmap -6 -p- ***SERVER***.local
Starting Nmap 7.80 ( https://nmap.org ) at 2022-11-20 12:07 -03
Nmap scan report for ***SERVER***.local (*** REDACTED ***)
Host is up (0.0025s latency).
Other addresses for ***SERVER***.local (not scanned): 192.168.15.101
Not shown: 65523 closed ports
PORT      STATE SERVICE
80/tcp    open  http
111/tcp   open  rpcbind
139/tcp   open  netbios-ssn
443/tcp   open  https
445/tcp   open  microsoft-ds
3493/tcp  open  nut
6443/tcp  open  sun-sr-https
8384/tcp  open  marathontp
10250/tcp open  unknown
20244/tcp open  unknown
22000/tcp open  snapenetio
32400/tcp open  plex

Nmap done: 1 IP address (1 host up) scanned in 13.93 seconds

-------------------------------------------------------------------------------------

$ nmap -4 -p- ***SERVER***.local 
Starting Nmap 7.80 ( https://nmap.org ) at 2022-11-20 12:07 -03
Nmap scan report for ***SERVER***.local (192.168.15.101)
Host is up (0.0070s latency).
Other addresses for ***SERVER***.local (not scanned): *** REDACTED ***
Not shown: 65499 closed ports
PORT      STATE    SERVICE
80/tcp    open     http
111/tcp   open     rpcbind
139/tcp   open     netbios-ssn
179/tcp   open     bgp
443/tcp   open     https
445/tcp   open     microsoft-ds
1280/tcp  open     pictrography
3493/tcp  open     nut
5357/tcp  open     wsdapi
6000/tcp  open     X11
6443/tcp  filtered sun-sr-https
6789/tcp  open     ibm-db2-admin
7472/tcp  open     unknown
7946/tcp  open     unknown
8080/tcp  open     http-proxy
8384/tcp  open     marathontp
8443/tcp  open     https-alt
8843/tcp  open     unknown
8880/tcp  open     cddbp-alt
9000/tcp  open     cslistener
10250/tcp open     unknown
12443/tcp open     unknown
16306/tcp open     unknown
18707/tcp open     unknown
20244/tcp open     unknown
20910/tcp open     unknown
20978/tcp open     unknown
21890/tcp open     unknown
22000/tcp open     snapenetio
32400/tcp open     plex
42160/tcp open     unknown
49921/tcp open     unknown
50051/tcp open     unknown
52381/tcp open     unknown
56976/tcp open     unknown
62464/tcp open     unknown

Nmap done: 1 IP address (1 host up) scanned in 3.24 seconds

OS: TrueNAS SCALE 22.02.4

**Comment by stavros-k** [comment]
Hello, can you please open a ticket in https://jira.ixsystems.com as "IPv6 is not supported yet in Apps"?

After that's handled, we can look into the specific app. 

Thanks

**Comment by stavros-k** [comment]
Hello, please test this on TrueNAS 24.10 which runs on Docker.
And if you encounter an issue. feel free to open a new issue on truenas/apps repo.

Thanks!
